### ISSUE TITLE
Kibana Simple Guide

### ISSUE THREAD

**Issue by MarioProjects** [cvat-ai/cvat#2647]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Display how much time users wasted labeling segmentation masks.

### Current Behaviour

Nothing :(

### Context

I followed the steps on analytics inclusion with CVAT through Kibana and I would visualize how much time spent users labeling, how much per image and so on but I don't know how to do it. As you included this tool maybe could share more info about his simple usage like these queries. I found past issues but without responses, could you help me, please?

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hi, thanks for the question, in general Kibana is very limited for such calculations (https://github.com/elastic/kibana/issues/4707), I think we will improve the analytics component in the future.
