### ISSUE TITLE
Creating a task with the same attributes name within the same label.

### ISSUE THREAD

**Issue by dvkruchinin** [cvat-ai/cvat#3113]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Probably need to show a notification that can't create attributes with the same name.

### Current Behaviour
Error with code 500

### Possible Solution
Probably to add the appropriate notification.

### Steps to Reproduce (for bugs)

1. Start creating a task
2. Add name, label with attributes with the same name (2 attributes are enough).
3. Add image, press ```Submit```.

### Your Environment

- Git hash commit (`git log -1`): adbc74fa29876ca625d178117129c8a834ea8463
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by KrishavRajSingh** [comment]
I think this issue is resolved.
![image](https://github.com/cvat-ai/cvat/assets/99531396/ac9d4f08-e59f-4c5e-a0e2-e84d451c1e55)

If there is something left, I would like to work on this.

**Comment by KrishavRajSingh** [comment]
I think i need to fix the server if duplicate values are coming. Right??
