### ISSUE TITLE
Report to calculate the number of annotations

### ISSUE THREAD

**Issue by nmanovic** [cvat-ai/cvat#350]
> Hi, I'm not really an elastic search / kibana / logstash power user. However I'm in the need to provide a report to calculate the number of annotated boxes on the day/week/month ? What would you recommend to do this? Elastic stack is not very intuitive and Im a poor C++ developer with no much grip

It is not possible to calculate the number of annotated boxes on the day/week/month now. Need to log more information. It should not be very difficult to implement. Extend logging with necessary events/counters. Aggregate such events in the table viz. Time period can be always be chosen in Kibana. ELK isn't very intuitive from my point of view but just look at the current code. It should be enough.

**Comment by RajatRasal** [comment]
I've done a bit of work on this.

Was wondering if you would still like PRs for this issue?

My design is as follows:
1. Added `annotation_type` to the log in the `finish` method in the `ShapeCreatorModel` class (`cvat/apps/engine/static/engine/js/shapeCreator.js`). The `annotation_type` will be one of either `['Box', 'Box by 4 points', 'Polygon'...]`.
![image](https://user-images.githubusercontent.com/20817781/87881377-c4d74e00-c9f0-11ea-8422-fb5f9be5f1f1.png)
2. Put an index-pattern on `annotation_type` in Kibana.
3. Added a visualisation, which is exactly the same as the `Number of events` vis, but with minor changes in the aggregation to use the newly created `annotation_type` field.
![image](https://user-images.githubusercontent.com/20817781/87881368-b1c47e00-c9f0-11ea-9d04-86d21b411e28.png)

**Comment by nmanovic** [comment]
@RajatRasal , please send a PR and we will look at it.

**Comment by lgg** [comment]
@RajatRasal hello, please - can you share your developments for this feature?

**Comment by azhavoro** [comment]
I believe this has already been implemented.
