### ISSUE TITLE
When I use CVAT for semantic segmentation some objects are missing when I export the dataset

### ISSUE THREAD

**Issue by mandyxiaomeng** [cvat-ai/cvat#4457]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

I have used CVAT for semantic segmentation labeling, I did the labeling like this; 
![image](https://user-images.githubusercontent.com/44643765/158157177-f6156083-6048-4f92-87a1-4235fcd889cc.png)

### Current Behaviour

However, when I export the dataset in CamVid or Cityscapes format, it exports the label like this: 
![cropped2_gtFine_color](https://user-images.githubusercontent.com/44643765/158157430-38114a02-bbcb-4466-bab5-a8ee9825a378.png)
In the image above the label of the object in the middle is missing. If I export the dataset again will be other objects missing. Like: 
![cropped2_gtFine_color](https://user-images.githubusercontent.com/44643765/158157741-8c973355-bb37-48f3-aa8b-6f3b91b70786.png)

Do you also face the same problem or have any idea why does this happen? 

### Your Environment

- Windows 10. I use cvat.org (the online tool) for labeling.

**Comment by nmanovic** [comment]
@mandyxiaomeng , could you please send us the link on the task? We will investigate. Thanks for the report!

**Comment by mandyxiaomeng** [comment]
> 
Hi,

Yes of course! The link to the job is: https://cvat.org/tasks/213658/jobs/308510 
I am not sure if you can open the link? So I also attached the backup of the job below:
[task_mandy2.0_backup_2022_03_14_10_34_54.zip](https://github.com/openvinotoolkit/cvat/files/8245068/task_mandy2.0_backup_2022_03_14_10_34_54.zip)

Thank you!!
Best Regards,
Mandy

**Comment by yasakova-anastasia** [comment]
Hi, @mandyxiaomeng 

Some objects are not displayed due to overlay of larger objects. The order in which objects are drawn during segmentation is important. After exporting to Cityscapes or Camvid, overlapping objects are not preserved because an image pixel can only store one label.

**Comment by felixcrazzolara** [comment]
I think this issue was resolved. I don't experience masks going missing despite them overlapping.
