### ISSUE TITLE
Count the number of annotated images

### ISSUE THREAD

**Issue by ArMaxik** [cvat-ai/cvat#4571]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

Hello! I need to count the number of annotated images (that has at least one annotation) in my tasks for proper workers analitic. 

### Current Behaviour

CVAT logs `Draw object`, `Delete object` and `Change frame` events to the elasticsearch db. `Change frame` contains image id, sum of `Draw object` and `Delete object` shows number of annotations. But it's quite tricky to combine this different events in Kibana to get the number of annotated images.

### Possible Solution

I think it will be much esier to solve this problem, if `Draw object` and `Delete object` evets have information about image id.

### Context

It is useful to know how much images workers have annotated for controling the annotation progress.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by ArMaxik** [comment]
Hello, @nmanovic!

Is there a chance this feature will be added in cvat in the future updates? What do you think?

**Comment by nmanovic** [comment]
@ArMaxik , For now I only can say that it is one of our priorities. If your team can contribute a prototype for the feature, please do.

**Comment by ArMaxik** [comment]
For now the issue doesm't seem very useful
