### ISSUE TITLE
Number of annotation on a single image

### ISSUE THREAD

**Issue by yaoguang97** [cvat-ai/cvat#4662]
Want to increase the number of annotation for viewing a single picture。

**Comment by bsekachev** [comment]
Sorry, you request is unclear. Try to keep issue template, provide more details and maybe screenshots.

**Comment by yaoguang97** [comment]
![微信截图_20220531110242](https://user-images.githubusercontent.com/76577121/171105044-8a746e80-9ce4-4808-96be-8f00f2df0d14.png)
For example, this image has a lot of target on it, and I want to quickly know how many annotations there are. At present, I can only view the annotations of the whole task.

**Comment by bsekachev** [comment]
@yaoguang97 

Oh, I got it. That is not implemented, but from my perspective it is quite easy to implement (for example to show number of objects in head of the right sidebar).

**Comment by KrishavRajSingh** [comment]
I would like to work on this.
