### ISSUE TITLE
Export COCO style annotation subsets from tasks with videos 

### ISSUE THREAD

**Issue by sarwasg** [cvat-ai/cvat#4993]
I have a project that contains tasks. Each task is one video. Tasks are indicated like train, test, and validation dataset. After "Export task dataset" with images to COCO format I received one folder with PNG images with presented video frames and one with annotations. For every dataset, I have different annotation JSON files, but I have only one "images" folder. 

The issue is that CVAT after exporting frames for each dataset (training, testing, and validation) starts naming the files from frame_000000.PNG. In effect files for the train dataset have the same names as files from the validation and test dataset. This means that when saving, the files will overwrite the others. I have the last version of CVAT and I see some improvements, that validation images have higher id's than for training but all these images' indicate image names started from frame_000000.PNG and all these frames are stored in this same folder.  

Can you solve this issue by creating subfolders for train, test, and validation frames?

**Comment by elloza** [comment]
Same here!

**Comment by zhiltsov-max** [comment]
Hi, I could reproduce the problem. It can be solved by changing [`merge_images=True`](https://github.com/opencv/cvat/blob/acb68a54d75456338802e2774ef0ffd388bad761/cvat/apps/dataset_manager/formats/coco.py#L22) to `=False` in the COCO export implementation in CVAT. I think, we should change it.
