### ISSUE TITLE
helm-chart: no TLS configuration for Analytics

### ISSUE THREAD

**Issue by turowicz** [cvat-ai/cvat#5071]
If using cert-manager it is currently impossible to get a LetsEncrypt certificate mounted for the `/analytics` route. Please add TLS configuration for it's ingress.

**Comment by turowicz** [comment]
I'm on nginx. The chart works with it but I guess this feature request is asking a lot. Not sure how you guys want to proceed but the fix is very easy:
```
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
```
Add the above in front of `rules:` in `templates/analytics/ingress.yaml`

**Comment by azhavoro** [comment]
Fixed in https://github.com/cvat-ai/cvat/pull/7132
