### ISSUE TITLE
Models Port change after PC restart

### ISSUE THREAD

**Issue by malfonso0** [cvat-ai/cvat#5509]
I have a problem on my deployed stack that every time i restart the server PC, the ports on the serverles models change, but nuclio port dont get update.

i have deployed cvat on a server pc i have.
clone dev repo and did

docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f components/serverless/docker-compose.serverless.yml -f components/analytics/docker-composeanalytics.yml up -d --build

have deployed some models
cd serverless
sh deploy_xxx.sh yyy/model x
nuctl get function show the deployed functions.. in ready state
everything is fine.. i can use the model on the page... so far so good

when i restart the PC.. the containers port get updated but nuclio ( cvat) is still pointing to the same old ports.
example.. when first deployed the container external port is 49178.. but after restart is 49175. 
when i do nuctl get function is still pointing to same 49178 and now when i call the model on cvat ui.. i get an error ( basically that the endpoint is unreachable)

how can i fix this behavior??
i have seen that i can put a static port on the yaml..., but is there another alternative?

**Comment by nmanovic** [comment]
@azhavoro , need to update the nuclio version. I hope they fixed that in a new version.

**Comment by prnr** [comment]
> @azhavoro , need to update the nuclio version. I hope they fixed that in a new version.

I updated nuclio to 1.11.20, but the port still changes due to PC reboot or container restart.

**Comment by azhavoro** [comment]
I beleave it's better to adress this issue to the nuclio team.

**Comment by azhavoro** [comment]
> when i restart the PC.. the containers port get updated but nuclio ( cvat) is still pointing to the same old ports.

CVAT does not store the function port number and gets this information from nuclio dashboard, so this problem is on the nuclio side.
As a workaround, I would suggest setting CVAT_NUCLIO_INVOKE_METHOD: 'dashboard' for the server and annotation services.

```yaml
services:
  cvat_server:
    environment:
      CVAT_NUCLIO_INVOKE_METHOD: 'dashboard'
  cvat_worker_annotation:
    environment:
      CVAT_NUCLIO_INVOKE_METHOD: 'dashboard'
```
