### ISSUE TITLE
Bug: Accounts with @ in the name can't login 

### ISSUE THREAD

**Issue by tvanderwal-lmco** [cvat-ai/cvat#5824]
### My actions before raising this issue
- [ x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x ] Searched [past issues](/issues)

In the admin panel it shows that a username should be able to have the following characters, which is fine when you create it. `Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.` However when that user tries to login they get a 400 Bad Request error. 

### Steps to Reproduce (for bugs)
1. Create a new username with email format (ie. tvanderwal-lmco@company.com
1. Give that user the correct permissions
1. Attempt to login with that user account

### Expected Behaviour
User exists in the admin panel and should be able to access the application

### Current Behaviour
Login error happens. If the @company.com is removed the account works fine. 

### Context
Trying to easily handle the user creation process using our UPN information. 

### Your Environment

- Are you using Docker Swarm or Kubernetes? Kubernetes
- Dev tag as of today

**Comment by klakhov** [comment]
@tvanderwal-lmco Is there a specific reason for username look like email? 
CVAT supports login with email, so you can use it as a sign in credential. If you create user with `tvanderwal-lmco@company.com` email and any username, user still can login.

**Comment by bsekachev** [comment]
Closed as there is no answer
