### ISSUE TITLE
Unble to edit Attribute name

### ISSUE THREAD

**Issue by phjae** [cvat-ai/cvat#5978]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. Create Project
2. Make label that has couple attributes
3. Annotate 
5. Edit attribute on project page 

### Expected Behaviour
It should be possible to change attribute name

### Current Behaviour
Unable to change attirubte name after i created

### Possible Solution
can add new attribute however, it's not possible to delete attribute either

### Context
when doing project, customers want to change attribute name on the middle of or at the end of the project.
it's pain to annotate all again just for the change of attribute name

Is there any reason why cvat disabled attribute edit box?

thanks so much for your help!

**Comment by zhiltsov-max** [comment]
Hi, there is no such option yet. As a workaround, you can export a backup, rename the attribute in the downloaded files, then recreate the project from the backup.

**Comment by donishyar** [comment]
hi , i would like to contribute please assign me .

**Comment by ritikraj26** [comment]
So currently we don't have the endpoint for deleting an attribute?

**Comment by zhiltsov-max** [comment]
Hi, I think, currently the attribute changes require all the attributes to be sent in the request. You can find tests [here](https://github.com/opencv/cvat/blob/acb68a54d75456338802e2774ef0ffd388bad761/tests/python/rest_api/test_labels.py#L586). Skeleton labels can also only be sent as a full list, specific sublabels cannot be changed separately. There are 2 ways to update labels now, one it changing a specific label via `/api/labels`, and another one is by sending the new list of labels in `/api/{projects|tasks}/<id>` endpoints. The implementation for these endpoints is located [here](https://github.com/opencv/cvat/blob/acb68a54d75456338802e2774ef0ffd388bad761/cvat/apps/engine/serializers.py#L323-L542).

**Comment by ritikraj26** [comment]
Yes, currently all the attributes are sent in the request. Currently updating an attribute name is creating a new one and not updating the previous one. That might have something to do with the serialization. Thanks for providing the reference.

**Comment by nmanovic** [comment]
@ritikraj26 , 

> the attribute name is being used as the primary key

Could you please explain why you think so? Please post a link on the code in the GitHub repo.

**Comment by ritikraj26** [comment]
@nmanovic ,
Let's say an attribute's name is updated in the front-end and the updated list of attributes is being passed in the request. Now to locate the same attribute in the database we will require the previous name as it is the primary key. However, we will receive the updated name which is not present in the database, and hence a new attribute will be created instead of updating the previous one.
Please find the reference [here](https://github.com/opencv/cvat/blob/8729f45a1b203201e6ae26e4579157c834aa4c18/cvat/apps/engine/serializers.py#L407-L423)

**Comment by ritikraj26** [comment]
@nmanovic 
Raised the PR [here](https://github.com/opencv/cvat/pull/7670)
