### ISSUE TITLE
REST API renaming an attribute does not work

### ISSUE THREAD

**Issue by bsekachev** [cvat-ai/cvat#6503]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
Try to rename existing attribute with ID 54:
![image](https://github.com/opencv/cvat/assets/40690378/e80b04d6-1819-400e-8794-ab8eb6e5def7)

Results:
![image](https://github.com/opencv/cvat/assets/40690378/983473e1-f20b-409e-8fb8-f5b48a8003dd)

### Expected Behaviour
I expect to be able to rename attributes like labels

### Current Behaviour
I am unable

### Your Environment

- Git hash commit (`git log -1`): v2.5.0
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
Related #5978

**Comment by ritikraj26** [comment]
Hi, I would like to contribute. Please assign this to me

**Comment by ritikraj26** [comment]
Raised the PR which fixes the rename attribute issue 
Please find it [here](https://github.com/opencv/cvat/pull/7670)
