### ISSUE TITLE
WIP Annotation gets small offset when changing to fullscreen

### ISSUE THREAD

**Issue by m101010** [cvat-ai/cvat#6957]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hello dear maintainers,

we found a small issue where work in progress (WIP) annotations get a small offset if one starts an annotation and then changes to fullscreen mode.

I've recorded a short video showing the problem:

[cvat_fullscreen_bug.webm](https://github.com/opencv/cvat/assets/17655752/428637de-4230-4226-a4f7-94ce7787762a)

Now that we know how to produce it, we can easily avoid this. 
Nevertheless, we wanted to inform you about this. 

### Expected Behavior

The WIP annotations should not be translated.

### Environment

```Markdown
We are using CVAT in the following version:

Server version: 2.4.5
Core version: 9.1.1
Canvas version: 2.16.6
UI version: 1.51.1
```

**Comment by bsekachev** [comment]
Can't reproduce in the current version. Let's close until further notice.
