### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by gronki** [cvat-ai/cvat#6959]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Try to upload .mpv video file which has decimal comma in the metadata
2. import fails with the error:

Could not create the task

Error: Could not create the task on the server. ValueError: could not convert string to float: '44,877000000'.

### Expected Behavior

Import should succeed

### Possible Solution

sed -i 's|float(_sec)|float(_sec.replace(",","."))|g' cvat/apps/engine/media_extractors.py

for example: https://github.com/opencv/cvat/pull/6923

### Context

Happens with mkv video exported from Networkoptix NX Witness VMS software. Works correctly for avi format.

### Environment

```Markdown
v2.4.4 tag in the container run via docker-compose
```

**Comment by ChanBong** [comment]
I think this is a pretty straightforward fix. Should I go ahead and write a solution ? 

I plan to change `cvat/apps/engine/media_extractors.py` so that the commas are replaced by dots

**Comment by nmanovic** [comment]
@ChanBong , please try to reproduce the issue first. It looks like the number of seconds can be encoded differently (depends on locale?). Need to understand what DURATION should have and how to decode it properly. I don't think it is right to replace ',' by a '.'. I'm not sure it will work always. Need to reproduce and understand the reason behind the problem.

**Comment by ChanBong** [comment]
You are right. This depends on the local encoding, mostly on your local computer language. I wasn't able to get/make such a video with commas in the duration. Maybe if @gronki can provide such video
