### ISSUE TITLE
Perhaps Paddleocr can be integrated for ocr detection and transcription

### ISSUE THREAD

**Issue by KTXKIKI** [cvat-ai/cvat#7130]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

https://github.com/PaddlePaddle/PaddleOCR
[paddlepaddle-GPU环境组件.zip](https://github.com/opencv/cvat/files/13328470/paddlepaddle-GPU.zip)
[PaddleOCR.zip](https://github.com/opencv/cvat/files/13328472/PaddleOCR.zip)
This is done by running script comments locally and uploading them, which may be integrated CVAT

**Comment by KTXKIKI** [comment]
#7628

**Comment by bsekachev** [comment]
Hello, looks interesting. Does it work on CPU as well? What is FPS performance? 
Generally, it would be great to add a good model for OCR, but actually there are not resources to do it now.

**Comment by KTXKIKI** [comment]
> 你好，看起来很有趣。它也适用于 CPU 吗？什么是 FPS 性能？一般来说，为 OCR 添加一个好的模型会很棒，但实际上现在没有资源来做。

of course  olso support CPU and GPU

**Comment by KTXKIKI** [comment]
https://github.com/PaddlePaddle/PaddleOCR

**Comment by KTXKIKI** [comment]
> 你好，看起来很有趣。它也适用于 CPU 吗？什么是 FPS 性能？一般来说，为 OCR 添加一个好的模型会很棒，但实际上现在没有资源来做。

cpu inference  for hundreds of milliseconds
gpu inference Decades of milliseconds

**Comment by KTXKIKI** [comment]
Paddleocr is a universal ocr model that supports both Chinese and English as well as various special symbols
I found some dockers to create image files for it： https://github.com/PaddlePaddle/PaddleOCR/tree/main/deploy/docker
I think the development of the main.py file should become easier

**Comment by KTXKIKI** [comment]
I think we can learn from it：https://github.com/cvat-ai/cvat/tree/develop/serverless/openvino/omz/intel/face-detection-0205/nuclio
