### ISSUE TITLE
Challenges deploying helm chart with Analytics enabled

### ISSUE THREAD

**Issue by isabelleHPE** [cvat-ai/cvat#7256]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hi, I was using the helm chart published in this repo, with analytics enabled. I had quite some issues to get clickhouse running... Am I the only one? I had to adapt things in the init container, I set volume permissions to enabled true, so it created the init container and helm was stating that the command defined in the init-container was not correct, the /bin/sh was missing. Also the security context was not working for me (the chmod commands could not been executed as the user that was stated there)...

### Possible Solution

     initContainers:
        {{- if and $.Values.tls.enabled (not $.Values.volumePermissions.enabled) }}
        - name: copy-certs
          image: {{ include "clickhouse.volumePermissions.image" $ }}
          imagePullPolicy: {{ $.Values.volumePermissions.image.pullPolicy | quote }}
          {{- if $.Values.resources }}
          resources: {{- toYaml $.Values.resources | nindent 12 }}
          {{- end }}
          # We don't require a privileged container in this case
          {{- if $.Values.containerSecurityContext.enabled }}
          securityContext: {{- omit $.Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          command:
          - "/bin/sh -ec 'cp -L /tmp/certs/* /opt/bitnami/clickhouse/certs/ && chmod 600 {{ include "clickhouse.tlsCertKey" $ }}'"
          volumeMounts:
            - name: raw-certificates
              mountPath: /tmp/certs
            - name: clickhouse-certificates
              mountPath: /opt/bitnami/clickhouse/certs
        {{- else if and $.Values.volumePermissions.enabled $.Values.persistence.enabled }}
        - name: volume-permissions
          image: {{ include "clickhouse.volumePermissions.image" $ }}
          imagePullPolicy: {{ $.Values.volumePermissions.image.pullPolicy | quote }}
          command: 
          - /bin/sh
          - -c
          - |
            mkdir -p /bitnami/clickhouse/data
            chmod 700 /bitnami/clickhouse/data
            {{- if $.Values.keeper.enabled }}
            mkdir -p /bitnami/clickhouse/keeper
            chmod 700 /bitnami/clickhouse/keeper
            {{- end }}
            chown {{ $.Values.containerSecurityContext.runAsUser }}:{{ $.Values.podSecurityContext.fsGroup }} /bitnami/clickhouse
            find /bitnami/clickhouse -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
            xargs -r chown -R {{ $.Values.containerSecurityContext.runAsUser }}:{{ $.Values.podSecurityContext.fsGroup }}
            {{- if $.Values.tls.enabled }}
            cp /tmp/certs/* /opt/bitnami/clickhouse/certs/
            {{- if eq ( toString ( $.Values.volumePermissions.containerSecurityContext.runAsUser )) "auto" }}
            chown -R `id -u`:`id -G | cut -d " " -f2` /opt/bitnami/clickhouse/certs/
            {{- else }}
            chown -R {{ $.Values.containerSecurityContext.runAsUser }}:{{ $.Values.podSecurityContext.fsGroup }} /opt/bitnami/clickhouse/certs/
            {{- end }}
            chmod 600 {{ include "clickhouse.tlsCertKey" $ }}
            {{- end }}
            exit 0
          
          securityContext: 
            allowPrivilegeEscalation: true
            runAsUser: 0
            runAsNonRoot: false

### Environment

```Markdown
K8s
```

**Comment by azhavoro** [comment]
Please address the issue to bitnami helm chart repo, CVAT team does not manage clickhouse chart
