### ISSUE TITLE
Error export annotation YOLO 1.1

### ISSUE THREAD

**Issue by AnSMru** [cvat-ai/cvat#7354]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I'm sorry right away that I'm not writing in English.
Я использую локальный CVAT 2.9.1

Ошибка заключается, в том, что при экспорте задачи или работы в формате YOLO 1.1 в файле аннотации появляются лишние строчки с данными.
Ошибка повторялась несколько раз, и кажется я понял ее причину. Если я создал два прямоугольника "OpenCV Tracking" (3 object), разметил, например 10 видеокадров из 1000. Затем вернулся на 5 кадр, удалил сам кадр (Alt+Del) №5. Потом, например, на 6-7 кадре, у номера "2 RECTANGLE TRACK" , сделал скрытие "Switch outside property". И возможно после этого удалил кадры 8-10. А оставшиеся кадры 1000 оставил как есть и продолжал размечать.
То при экспорте возникает такая ситуация, с 1-4 кадр, все хорошо. 5 кадра не будет. А начиная с 6 кадра, может появится в файле frame_00005.txt ... frame_00999.txt фантомная строчка с одинаковыми данными о типе и координатах.
Как пример, из двух файлов ниже.
frame_00010.txt
0 0.525781 0.441801 0.332917 0.332306
0 0.164583 0.212963 0.184375 0.153704 - error
0 0.875055 0.402880 0.091161 0.129907

frame_00011.txt
0 0.682857 0.472731 0.628974 0.381759
0 0.164583 0.212963 0.184375 0.153704 - error

frame_00012.txt
0 0.679281 0.458606 0.631688 0.372769
0 0.164583 0.212963 0.184375 0.153704 - error
И даже если например будет пустой, не размеченный кадр, то при экспорте у  пустого кадра (где нет объектов) будет эта строчка.

### Possible Solution

Выход был один. Приходилось полностью удалять "2 RECTANGLE TRACK" и размечать заново, но не применять "Switch outside property" между кадрами, а только финишировать этот тег.

**Comment by AnSMru** [comment]
Еще дополнение, все фреймы с активным keyframe property. Пробовал повторить специально эту ситуацию, пока не вышло.

**Comment by Eldies** [comment]
fixed in https://github.com/cvat-ai/cvat/pull/8834
