### ISSUE TITLE
Related images are not included when exporting 3D datasets

### ISSUE THREAD

**Issue by SpecLad** [cvat-ai/cvat#7375]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Create a task from the `cvat/apps/engine/tests/assets/test_canvas3d.zip` archive in the CVAT repository.
2. Export the task in the Datumaro 3D format.
3. Observe that the related images are missing from the resulting archive.

### Expected Behavior

Related images should be included in the export result.

### Possible Solution

Most likely, the problem is here:

https://github.com/opencv/cvat/blob/a5669aa1ba81c335693383015b65884794685a0d/cvat/apps/dataset_manager/bindings.py#L1462

and here:

https://github.com/opencv/cvat/blob/a5669aa1ba81c335693383015b65884794685a0d/cvat/apps/dataset_manager/bindings.py#L1582

Datumaro doesn't use the `related_images` parameter if the `media` parameter is specified. Instead of `media=PointCloud(dm_image[0]), related_images=dm_image[1]`, it should say `media=PointCloud(dm_image[0], extra_images=dm_image[1])`.

### Environment

```Markdown
Reproducible on app.cvat.ai.
```

**Comment by bargav-bunny** [comment]
I am interested in this issue. Can you please assign it to me.
