### ISSUE TITLE
navigate over unresolved issues

### ISSUE THREAD

**Issue by ArMaxik** [cvat-ai/cvat#7443]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

There are a some resolved issues in the job. I've gone through the annotations and added some new issues. Now annotator to fix them should somehow find all frames with unresolved issues.

In the latest version of cvat (2.10.2) this is impossible. There is only a way to navigate over frames with issues (both resolved and unresolved):
![image](https://github.com/opencv/cvat/assets/7460322/2875061c-da2e-4060-ba7a-9db1d8b23008)

If there are a lot of resolved issues, it's hard and annoying to find frames with new issues.

### Describe the solution you'd like

Cheking show/hide resolved issue should also hide frames with them:
![image](https://github.com/opencv/cvat/assets/7460322/0bf540fa-f909-4409-b91e-05d8d6f784d0)

This will allow you to skip frames with unresolved issues.

**Comment by tahamukhtar20** [comment]
@nmanovic can you assign please me this issue?

**Comment by tahamukhtar20** [comment]
@ArMaxik can you please help me recreate the issue?

**Comment by ArMaxik** [comment]
@tahamukhtar20 Glad to hear you are working on this issue!
Small steps:
1) As a reviewer open a job and create some issues.
2) As an annotator fix issues and resolve them. Or the reviewer can resolve them, it doesn't matter
3) As a reviewer you found new mistakes, so create some new issues on the same job.
4) As an annotator, I want to find new issues and skip already resolved. Now it is impossible, I should look through all of them.

There is a perfect button "show/hide resolved issues", but buttons "find the next/previous frame with issues" ignore it

**Comment by thekavikumar** [comment]
@nmanovic @bsekachevv is the issue still open, if so can you please assign it to me

**Comment by tahamukhtar20** [comment]
@nmanovic you can unassign. I am not able to work on this currently. Thanks

**Comment by nmanovic** [comment]
@thekavikumar , please let me know if you want to take the issue.

**Comment by thekavikumar** [comment]
@nmanovic yeah, I will take the issue

**Comment by thekavikumar** [comment]
@nmanovic @klakhov please close this issue as it has been resolved!

**Comment by klakhov** [comment]
Resolved in #7653
