### ISSUE TITLE
WebGUI: Finding out the name of the running model in an automatic annotation

### ISSUE THREAD

**Issue by RoseDeSable** [cvat-ai/cvat#7480]
Hi,
 I see in the webgui, that an annotation is running.

![grafik](https://github.com/opencv/cvat/assets/42828799/d4e14450-a37c-40dc-8652-c88f329b952e)

Where can I see the name of the model, that is used ?

Best Regards
Rose

**Comment by bsekachev** [comment]
I do not really think you can..

**Comment by RoseDeSable** [comment]
an in future ?

**Comment by KTXKIKI** [comment]
> 未来呢？

The model that you should choose before you make inferences

**Comment by RoseDeSable** [comment]
Ok,
 I run several models in several jobs over night. The other morning I control the annotations. In such a case I wish, that I see the model's name, that made the annotation in a specific job. Nowadays I must make a list with the name of the jobs and the used models, if I start the annotations.
