### ISSUE TITLE
Can't install AI Tools (macOS)

### ISSUE THREAD

**Issue by Kappasama** [cvat-ai/cvat#7563]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

Mac Pro M3 (MacOS 14.1)

**1)** pull cvat
**2)** install nuclio
`user@MacBook-Pro-Urij cvat % nuctl version
Client version:
"Label: 1.11.24, Git commit: f2a3900d23b92fd3639dc9cb765044ef53a4fb2b, OS: darwin, Arch: amd64, Go version: go1.19.10"`

3) docker compose up 
<img width="1315" alt="Снимок экрана 2024-03-07 в 16 49 50" src="https://github.com/opencv/cvat/assets/3257133/8cfd89f0-b1d2-4207-a2ee-b89407587a8b">

**3)** from https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
<img width="1017" alt="Снимок экрана 2024-03-07 в 16 50 44" src="https://github.com/opencv/cvat/assets/3257133/14625d55-6c3d-48da-bd33-25d7f3d420c2">

**4)** In docker:
<img width="1505" alt="Снимок экрана 2024-03-07 в 16 51 26" src="https://github.com/opencv/cvat/assets/3257133/abb10b4f-9155-45dc-885a-55628af6f57b">

but AI Function not show in chat
<img width="184" alt="Снимок экрана 2024-03-07 в 16 48 12" src="https://github.com/opencv/cvat/assets/3257133/3d1f753e-c6b2-4164-8679-f3777f277e9c">

**Comment by Kappasama** [comment]
It looks like the models have not been added

```
image=$(curl https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png --output - | base64 | tr -d '\n')
cat << EOF > /tmp/input.json
{"image": "$image"}
EOF
cat /tmp/input.json | nuctl invoke openvino-omz-public-yolo-v3-tf -c 'application/json'
```

Logs:
```
Error - Function not found: openvino-omz-public-yolo-v3-tf @ nuclio
    /nuclio/pkg/nuctl/command/invoke.go:119

Call stack:
Failed to enrich function invocation options
    /nuclio/pkg/nuctl/command/invoke.go:119
```

**Comment by Kappasama** [comment]
The problem is partially solved.

There were 2 problems. The first one is related to "shopt -s globstar"
The solution was taken from https://apple.stackexchange.com/questions/291287/globstar-invalid-shell-option-name-on-macos-even-with-bash-4-x

Second problem with "func_rel_path="$(realpath --relative-to="$SCRIPT_DIR" "$(dirname "$func_root"))""
A similar issue was addressed in "https://github.com/mirage335-colossus/ubiquitous_bash/issues/1"

Solution: Specify the required path directly in the script code

But at the moment there is an error:

`> [internal] load metadata for docker.io/library/cvat.openvino.base:latest:
------
Dockerfile:30
--------------------
  28 |     RUN mo --input_model=/root/dextr.onnx --model_name=dextr --output_dir=/root
  29 |     
  30 | >>> FROM cvat.openvino.base
  31 |     
  32 |     COPY --from=build --chown=root:root /root/dextr.xml /root/dextr.bin /opt/nuclio/
--------------------
ERROR: failed to solve: cvat.openvino.base: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
`

**Comment by Kappasama** [comment]
add `--platform=linux/amd64` to local Dockerfile and docker find it.  But it looks like it won’t work for Mac M3

<img width="1185" alt="Снимок экрана 2024-03-08 в 03 56 49" src="https://github.com/opencv/cvat/assets/3257133/f711c001-4812-4a21-af4e-3f549b9da335">

**Comment by bsekachev** [comment]
M1/M2/M3 cpus are not supported by us. 
CVAT itself is only python and JS code, but with many 3rdparty dependencies. And the problem with these CPUs are in 3rdparty dependencies.
