### ISSUE TITLE
Detection error occurred Request failed with status code 504

### ISSUE THREAD

**Issue by arunima-pirllabs** [cvat-ai/cvat#7658]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

I am trying to use Automatic Annotation on my task
![image](https://github.com/opencv/cvat/assets/162993962/2bd7e712-d2a5-42c5-a67e-ac2be92d21f9)
Upon selecting the model deployed via `./serverless/deploy_cpu.sh serverless/onnx/WongKinYiu/yolov7 --platform local` I am clicking on "Annotate"
![image](https://github.com/opencv/cvat/assets/162993962/1e1a8442-751b-45bf-83ec-4014168d8259)
![image](https://github.com/opencv/cvat/assets/162993962/fd284db0-0c94-46fb-b874-1f94a631fade)
I keep getting this error: 
![image](https://github.com/opencv/cvat/assets/162993962/cc87ae80-3b0a-4588-b8c0-f678332f6fe3)
This is the detailed error message in Browser Console: 
`
The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
:8080/api/user-agreements?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions?org=&page_size=500&page=1:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/lambda/functions/onnx-wongkinyiu-yolov7?org=:1 
       Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/functions/requests/?org=:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
cvat-app.tsx:356 Uncaught Error: Inference status for the task 2 is failed. Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7dbc90f63ca0>, 'Connection to host.docker.internal timed out. (connect timeout=120)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=32768): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7dbc90f63ca0>, 'Connection to host.docker.internal timed out. (connect timeout=120)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 793, in __call__
    cls._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 586, in _call_detector
    annotations = function.invoke(db_task, db_job=db_job, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 333, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 104, in invoke
    return invoke_method[settings.NUCLIO['INVOKE_METHOD']](func, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 122, in _invoke_directly
    reply = session.post(url, timeout=NUCLIO_TIMEOUT, json=payload)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='host.docker.internal', port=32768): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7dbc90f63ca0>, 'Connection to host.docker.internal timed out. (connect timeout=120)'))

    at models-actions.ts:180:25
    at lambda-manager.ts:154:54
    at Array.forEach (<anonymous>)
    at lambda-manager.ts:154:34 `

### Expected Behavior

![Screenshot from 2024-03-22 17-52-27](https://github.com/opencv/cvat/assets/162993962/af10fb2a-abc4-4c59-96c9-948bbb41d337)

### Possible Solution

![Screenshot from 2024-03-22 17-56-30](https://github.com/opencv/cvat/assets/162993962/2f695ba7-11b5-41dd-8505-0d5e61c2f1f3)

### Context

The above *Possible solution* was achieved from this discussion: 
https://github.com/opencv/cvat/issues/2189#issuecomment-1105985517

### Solution
![image](https://github.com/opencv/cvat/assets/162993962/dc74f52f-90fa-4409-8400-5e6b4413824f)
and then pass this command in your terminal:
`sudo ufw allow proto tcp from any to 172.17.0.1`

### Environment

```Markdown
- Django version 4.2.4
- Git version 2.34.1
- CVAT_VERSION:-v2.7.4
- nuctl version: Label: 1.13.0
- Python 3.11.8
```

**Comment by bsekachev** [comment]
I suspect this is duplicate for this issue: https://github.com/opencv/cvat/issues/5509

**Comment by AVISIX** [comment]
> ### Actions before raising this issue
> * [x]  I searched the existing issues and did not find anything similar.
> * [x]  I read/searched [the docs](https://opencv.github.io/cvat/docs/)
> 
> ### Steps to Reproduce
> I am trying to use Automatic Annotation on my task ![image](https://private-user-images.githubusercontent.com/162993962/315917858-2bd7e712-d2a5-42c5-a67e-ac2be92d21f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzUyNTEsIm5iZiI6MTcxNzk3NDk1MSwicGF0aCI6Ii8xNjI5OTM5NjIvMzE1OTE3ODU4LTJiZDdlNzEyLWQyYTUtNDJjNS1hNjdlLWFjMmJlOTJkMjFmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTQ1OGFhOTE0MTc3YmQxMzA4NWZkOTYwNjIyMWNjNjQ3NjY5Yzg4NGEzYzJkYzBmMjQxMmYzMjkwZWEyN2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fbCFMXEl9nXx9RB4OTQ9rOkrQc3X01YX-QlnQR8PK-g) Upon selecting the model deployed via `./serverless/deploy_cpu.sh serverless/onnx/WongKinYiu/yolov7 --platform local` I am clicking on "Annotate" ![image](https://private-user-images.githubusercontent.com/162993962/315917959-1e1a8442-751b-45bf-83ec-4014168d8259.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzUyNTEsIm5iZiI6MTcxNzk3NDk1MSwicGF0aCI6Ii8xNjI5OTM5NjIvMzE1OTE3OTU5LTFlMWE4NDQyLTc1MWItNDViZi04M2VjLTQwMTQxNjhkODI1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWMxODQ1MGY5NmMzMzg1MmI4ZmUxODliMjBlYWUxMWY4MDYyYzAyYjJmZjU4ZTQ0OTI0YjU4OTIzMDkyOWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cwSt_fd97ddTE6PATFAp7_q4ntKygEqSqZbwFTrtle4) ![image](https://private-user-images.githubusercontent.com/162993962/315918459-fd284db0-0c94-46fb-b874-1f94a631fade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzUyNTEsIm5iZiI6MTcxNzk3NDk1MSwicGF0aCI6Ii8xNjI5OTM5NjIvMzE1OTE4NDU5LWZkMjg0ZGIwLTBjOTQtNDZmYi1iODc0LTFmOTRhNjMxZmFkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGYwYjNjZmI0ZmRlMzUxYjIyMDdjODU4N2U5NjI3NzQxMmY3ZTNmYmU2YjYyM2I2NTk4OWRiNWIxNzM4YzRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XH5-VcxZU3nmxDj7Ec0mp0FMjeGDzsU9nLnoeLM-88Q) I keep getting this error: ![image](https://private-user-images.githubusercontent.com/162993962/315918556-cc87ae80-3b0a-4588-b8c0-f678332f6fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzUyNTEsIm5iZiI6MTcxNzk3NDk1MSwicGF0aCI6Ii8xNjI5OTM5NjIvMzE1OTE4NTU2LWNjODdhZTgwLTNiMGEtNDU4OC1iOGMwLWY2NzgzMzJmNmZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGIyYzc3MzE0NjU0MWMzM2ZhMjc3NDE3NjljMmE0ZTNiN2VhOGRhNTdiOTc3NTgzNGFkY2IwNzQzZTU1MzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nmBhRJCfkl3QwMoUyPeP263cPHhTr53hxENp5Y-NI-c) This is the detailed error message in Browser Console: ` The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header. :8080/api/user-agreements?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions?org=&page_size=500&page=1:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/lambda/functions/onnx-wongkinyiu-yolov7?org=:1 Failed to load resource: the server responded with a status of 504 (Gateway Timeout) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) :8080/api/functions/requests/?org=:1 Failed to load resource: the server responded with a status of 404 (Not Found) cvat-app.tsx:356 Uncaught Error: Inference status for the task 2 is failed. Traceback (most recent call last): File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) TimeoutError: timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen httplib_response = self._make_request( File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request conn.request(method, url, **httplib_request_kw) File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/usr/lib/python3.10/http/client.py", line 1283, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output self.send(msg) File "/usr/lib/python3.10/http/client.py", line 976, in send self.connect() File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect conn = self._new_conn() File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn raise ConnectTimeoutError( urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7dbc90f63ca0>, 'Connection to host.docker.internal timed out. (connect timeout=120)')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen retries = retries.increment( File "/opt/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=32768): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7dbc90f63ca0>, 'Connection to host.docker.internal timed out. (connect timeout=120)'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 936, in perform_job rv = job.perform() File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 684, in perform self._result = self._execute() File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 690, in _execute return self.func(*self.args, **self.kwargs) File "/home/django/cvat/apps/lambda_manager/views.py", line 793, in **call** cls._call_detector(function, db_task, labels, quality, File "/home/django/cvat/apps/lambda_manager/views.py", line 586, in _call_detector annotations = function.invoke(db_task, db_job=db_job, data={ File "/home/django/cvat/apps/lambda_manager/views.py", line 333, in invoke response = self.gateway.invoke(self, payload) File "/home/django/cvat/apps/lambda_manager/views.py", line 104, in invoke return invoke_method[settings.NUCLIO['INVOKE_METHOD']](func, payload) File "/home/django/cvat/apps/lambda_manager/views.py", line 122, in _invoke_directly reply = session.post(url, timeout=NUCLIO_TIMEOUT, json=payload) File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 637, in post return self.request("POST", url, data=data, json=json, **kwargs) File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 507, in send raise ConnectTimeout(e, request=request) requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='host.docker.internal', port=32768): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7dbc90f63ca0>, 'Connection to host.docker.internal timed out. (connect timeout=120)'))
> 
> ```
> at models-actions.ts:180:25
> at lambda-manager.ts:154:54
> at Array.forEach (<anonymous>)
> at lambda-manager.ts:154:34 `
> ```
> 
> ### Expected Behavior
> ![Screenshot from 2024-03-22 17-52-27](https://private-user-images.githubusercontent.com/162993962/316013406-af10fb2a-abc4-4c59-96c9-948bbb41d337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzUyNTEsIm5iZiI6MTcxNzk3NDk1MSwicGF0aCI6Ii8xNjI5OTM5NjIvMzE2MDEzNDA2LWFmMTBmYjJhLWFiYzQtNGM1OS05NmM5LTk0OGJiYjQxZDMzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzFhYzEyMDk2MWFhNjQzYWRmMmIyNDFjNmE5NWM4NTJkOTdlMDBlZDMyNGU4NTY1MTk5MzMxYWEyYTNmODdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vjKg1ufMSlE_aHnIObQIYwBd9C1asUx0bI2MW7bYvw8)
> 
> ### Possible Solution
> ![Screenshot from 2024-03-22 17-56-30](https://private-user-images.githubusercontent.com/162993962/316012642-2f695ba7-11b5-41dd-8505-0d5e61c2f1f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzUyNTEsIm5iZiI6MTcxNzk3NDk1MSwicGF0aCI6Ii8xNjI5OTM5NjIvMzE2MDEyNjQyLTJmNjk1YmE3LTExYjUtNDFkZC04NTA1LTBkNWU2MWMyZjFmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTMwYjcyZGVkODg1OWNiNDA2Mjk2NTdhZDcxM2I4MDMzNDUzZDQzNzhiZjQ1ZTc0ZTFjNTJiYjcwMmE4YmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d-picXedXvQwI3rw5YMFj-z-rs8e_btZPjq6o7xWlng)
> 
> ### Context
> The above _Possible solution_ was achieved from this discussion: [#2189 (comment)](https://github.com/cvat-ai/cvat/issues/2189#issuecomment-1105985517)
> 
> ### Solution
> ![image](https://private-user-images.githubusercontent.com/162993962/316014141-dc74f52f-90fa-4409-8400-5e6b4413824f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzUyNTEsIm5iZiI6MTcxNzk3NDk1MSwicGF0aCI6Ii8xNjI5OTM5NjIvMzE2MDE0MTQxLWRjNzRmNTJmLTkwZmEtNDQwOS04NDAwLTVlNmI0NDEzODI0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWI1OTk0NDZjZGMyMjI5MWZhMGFiZTUzMWFmMTYyYTY1Y2RiYjBjZjU1ZDE4NjJhZTUwNjMxZjM4OTZhNmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yb-PQFpqQeMY0wOcE8tJlVjUQ8B-BYV3Po2B4XrRQeM) and then pass this command in your terminal: `sudo ufw allow proto tcp from any to 172.17.0.1`
> 
> ### Environment
> ```
> - Django version 4.2.4
> - Git version 2.34.1
> - CVAT_VERSION:-v2.7.4
> - nuctl version: Label: 1.13.0
> - Python 3.11.8
> ```

This worked for me, thanks for all the details! 

However, I didn't do `network = cvat_cvat` and instead did `network: cvat_cvat`.

**Comment by arunima-pirllabs** [comment]
@AVISIX Apologies, you are right - 
`network: cvat_cvat`
that's the correct format.

**Comment by suryapantam-creator** [comment]
3?page=1:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.Understand this error
:8080/api/user-agreements?org=:1  Failed to load resource: the server responded with a status of 404 (Not Found)Understand this error
cvat-app.tsx:385 Uncaught Error: Inference status for the task 3 is failed. Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 969, in __call__
    cls._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 790, in _call_detector
    annotations = function.invoke(db_task, db_job=db_job, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 432, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 106, in invoke
    return invoke_method[settings.NUCLIO['INVOKE_METHOD']](func, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 109, in _invoke_via_dashboard
    return self._http(method="post", url='/api/function_invocations',
  File "/home/django/cvat/apps/lambda_manager/views.py", line 85, in _http
    reply.raise_for_status()
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations

    at models-actions.ts:135:25
    at lambda-manager.ts:139:54
    at Array.forEach (<anonymous>)
    at lambda-manager.ts:139:34

Getting the error while running the automatic annottaion for yolov5,v7,v8 models
