### ISSUE TITLE
Cannot access to CVAT in Local Lan Machine

### ISSUE THREAD

**Issue by dattv** [cvat-ai/cvat#7667]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. Open Terminal in Ubuntu: ```export CVAT_HOST=192.168.1.93``` (```192.168.1.93``` is host IP address)
2. Get into CVAT cloned: ```cd cvat```
3. docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
4. Open browser in the host and type ```localhost:8080``` (OK, I can access to CVAT annotation framwork)
5. From another computer in local Lan network ```ping 192.168.1.93``` (OK).
6. Open browser in this computer and typing ```192.168.1.93:8080``` it throw out 404 error

### Expected Behavior

I want to do semi-atomatic annotation in the local lan, but i cannot access to cvat. even i already export the host IP address in both terminal and bash.rc file.
I there any one got same issue or already fixed this problem?

**Comment by azhavoro** [comment]
please provide output of `docker inspect cvat_server` and `curl -Lv http://192.168.1.93:8080`

**Comment by umangapatel123** [comment]
@dattv I think there is an issue with exporting CVAT_HOST. try to put it into the /etc/environment file

**Comment by airhao3** [comment]
I do encountered this as well, if I ran this server without set CVAT_HOST , I can connect localhost:8080 with cvat content show correctly, while if I set CVAT_HOST to my ip address or domain name,  I lost my ssh connection every time.

**Comment by airhao3** [comment]
> I do encountered this as well, if I ran this server without set CVAT_HOST , I can connect localhost:8080 with cvat content show correctly, while if I set CVAT_HOST to my ip address or domain name, I lost my ssh connection every time.

I've already fixed this by set  `cvat_host: - <ip>or <domain name>` in the docker-compose.yml file.

**Comment by roboticlemon** [comment]
see https://github.com/cvat-ai/cvat/issues/3526
