### ISSUE TITLE
How to change the user invitation email?

### ISSUE THREAD

**Issue by arnaghizadeh** [cvat-ai/cvat#7707]
Hi, I installed cvat with docker compose, and could successfully create email settings so the the invitations can be sent sent to the users but I cant find a way online that explains how to change the invitation template online.  There are two places that need  to be changed,
1- subject which starts with "[example.com] You're invited to join", here the example.com should be changed to the real domain.
2- the setup button starts with "http://example.com/auth/login?email=", here also the example button needs to change to the correct **domain** and **port**.

Can anyone help?

**Comment by bsekachev** [comment]
Email templates may be found there: `cvat_enterprise/cvat/cvat/apps/organizations/templates`.

Info for template is grabbed from this file `cvat_enterprise/cvat/cvat/apps/organizations/models.py`, Invitation class, `send` method.

It uses django function to get site domain. Perhaps is something wrong in this place, like django's `get_current_site` returns `example.com`.

**Comment by YaoJusheng** [comment]
It seems to be to create the `site` first and then modify the `SITE_ID` in file `base.py`?

Why not consider using environment variables? @bsekachev

**Comment by azhavoro** [comment]
> It seems to be to create the `site` first and then modify the `SITE_ID` in file `base.py`?

or just to modify existing default site `example.com` in the django admin page.

> Why not consider using environment variables? @bsekachev

If you see a potential improvement, you can always send a pull-request

**Comment by CodeWracker** [comment]
currently on commit `2c5cef6149ff36b63cae6b7bf1d34974b7b65e94`


I followed those steps, but the subject remais as `[example.com]` and there is absolutelly no reference for where this might being setted...

I have the following envs:
```
CVAT_HOST=annotation.tdlreis.dev.br
CVAT_BASE_URL=https://annotation.tdlreis.dev.br
CVAT_UI_HOST=annotation.tdlreis.dev.br
CVAT_SITE_NAME=Annotation GD # Just trusted what Gemini told me, this didn't do anything
```

and changed in the admin pannel

<img width="1105" height="644" alt="Image" src="https://github.com/user-attachments/assets/fad0a76b-d7ac-4cb3-89af-d00fcb8fb11a" />

But the problem persists
`[example.com] You're invited to join the GD organization in CVAT!`
