### ISSUE TITLE
Error when trying to export task dataset

### ISSUE THREAD

**Issue by katab** [cvat-ai/cvat#7712]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

We are trying to export a task dataset in the "CVAT for video 1.1" format. However, after 4 hours it times out and an error message is printed, see below:
`File "/opt/venv/lib/python3.10/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value '
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (14400 seconds)`

This is a screenshot of the error message in the UI:
<img width="1434" alt="CVAT export fail" src="https://github.com/opencv/cvat/assets/17437613/e2e69af2-591a-40ac-bfdc-09acc1b97a97">
We have also tried to export the annotations in the "CVAT for images 1.1 format" (for debug purposes) but this isn't working either. 

The task consists of 790 frames with a segment size of 25 and an overlap size of 5, resulting in 32 jobs with 30 frames per job. 
The task is annotated with tracks and each job has between 50 and 110 unique tracks resulting in between 1400 and 3000 boxes/polygons (mostly boxes) in total per job. The whole task has around 55 000 boxes/polygons. All these annotations have been imported. 

We are able to export the annotations from one job at a time, but since we need the tracks to be consistent between the jobs this isn't a feasible option. 

For debug purposes we have tried to remove all annotations from 60-70% of the jobs and then export the task in the "CVAT for video 1.1" format which works. 

Is there a known limit regarding the number of tracks or objects that you are able to export? Do you have any suggestions on how we can solve this issue? Is it worth trying to extend the timeout limit beyond 4 hours? 

### Expected Behavior

We should be able to successfully export the task in the "CVAT for video 1.1" format. 

### Environment

```Markdown
Server version: 2.6.1
Core version: 11.0.3
Canvas version: 2.17.4
UI version: 1.55.4
```

**Comment by katab** [comment]
Thanks for your response @bsekachev! We will try to increase the timeout as a first attempt, if that doesn't work we'll try to upgrade to the latest release. I will get back to you with an update of our progress.

**Comment by S-kewen** [comment]
Hello, I encountered the same problem when importing annotations. I also modified the timeout in base.py (and restarted the service), but it doesn't seem to have any effect.

CVAT Server: 2.41.1
