### ISSUE TITLE
Can we have access to user annotations in Semi-automatic and Automatic Annotation? 

### ISSUE THREAD

**Issue by arnaghizadeh** [cvat-ai/cvat#7721]
Hi, in the [Semi-automatic and Automatic Annotation](https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/) and [Serverless tutorial](https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/)  we see that 
how it is possible to have access to various information from user that triggered the serverless function such as image and threshold:
data = event.body
buf = io.BytesIO(base64.b64decode(data["image"]))
threshold = float(data.get("threshold", 0.5))
image = convert_PIL_to_numpy(Image.open(buf), format="BGR")

but I want to know that if it is possible to have access to the annotations as well? I could not find any reference that exactly what type of information event.body holds within itself and whether the annotations are part of it? If not what is the best way to approach it? Should I use rest API, or specific part of the code I can change?

**Comment by bsekachev** [comment]
Hello,

You may also use cvat-sdk to access data if necessary from the model handler.
Transfer annotations data directly from CVAT to handler is not supported
