### ISSUE TITLE
Empty labels from a big task 

### ISSUE THREAD

**Issue by suzuki1994** [cvat-ai/cvat#7737]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I did the labels of 700 images, but when i exported the datashet the labels was empty ( have all the files of the 700 labels, but don't have any anotation inside)
I exported the datashet on format of YOLO 1.1
When the annotation was made on small patchs (100 for example) it worked fine
The task number is:
#585018

![image](https://github.com/cvat-ai/cvat/assets/51233986/2b907bc5-97ba-4229-a073-2f8116d545e5)

### Expected Behavior

The expected behavior is something like the next image, the annotation be exported and appearing on the file 

![image](https://github.com/cvat-ai/cvat/assets/51233986/6719ad83-03cc-4534-8806-199bb0fd4f27)

### Possible Solution

I'd like the hours of labeling don't be wasted, so if you guys could send me on email or make the annotation appear when i download it i would be really happy

### Context

How has this issue affected you? What are you trying to accomplish?

Well i will train the IA and need the labels, so they need appear on the file.

### Environment

```Markdown
didn't appear any error the download was normal and all the files are on the place, but they are empty inside
```

**Comment by suzuki1994** [comment]
So, i was trying to see what i did worng... and i saw the when i make the label with a rectangle the label appear when i download it
![image](https://github.com/cvat-ai/cvat/assets/51233986/a3e59f3e-790c-43ee-b18c-5cccb1288071)
But when i make it with polygon it don't appear...
![image](https://github.com/cvat-ai/cvat/assets/51233986/0a27f561-068f-4506-8dac-58a72c218a78)

and i to make the label of the 700 images i used almost always polygon

**Comment by bsekachev** [comment]
YOLO1.1 supports only bounding boxes.

Please, refer: https://www.cvat.ai/post/cvat-ai-exporting-annotations-from-cvat-to-yolov8-format-on-windows
