### ISSUE TITLE
Could not import dataset : No media data found 

### ISSUE THREAD

**Issue by irmo322** [cvat-ai/cvat#7758]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a new project
2. Add class TrainGate
3. Actions > Import dataset > pascal voc 1.1 [provide samples.zip] 

### Expected Behavior

The dataset is imported.

### Context

[samples.zip](https://github.com/cvat-ai/cvat/files/14958043/samples.zip)
![image](https://github.com/cvat-ai/cvat/assets/11430779/be89e8fc-ff59-4b92-9717-4bb4a1ac35a0)

### Environment

Tried on https://app.cvat.ai/.

**Comment by irmo322** [comment]
Should I expect any return on this problem ?
It's easy to reproduce it with the provided `samples.zip`.

**Comment by O-J1** [comment]
I believe I am also facing this issue. I similarly have a a COCO dataset I exported from roboflow and tried to import, no bueno.

Also tried converting it to CVAT using datumaro and the site rejected it too.

**Comment by maxi-askui** [comment]
I'm also facing this issue with an ICDAR Localization 1.0 dataset. Any updates?

**Comment by bsekachev** [comment]
You may only import project with images.

**Comment by zhiltsov-max** [comment]
Hi, you can find supported import file layouts on the [format documentation page](https://docs.cvat.ai/docs/manual/advanced/formats/format-voc/#pascal-voc-export). The simplified VOC format (flat) is only supported for annotation import in an existing task. For dataset import you need to use the full layout.
