### ISSUE TITLE
Automatic annotation failed: model running change to unhealthy after automatic annotation

### ISSUE THREAD

**Issue by soohwanlim** [cvat-ai/cvat#7780]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. I trained yolov8 from scratch by own dataset and make pytorch model
2. I upload into nuclio by using function.yaml, main.py and own_model.pt
3. I checked that model status is running
4. Then i clicked automatic annotation, but it has error and model status change to unhealthy

Can i get some help?
![cvat1](https://github.com/cvat-ai/cvat/assets/55626513/b87d663f-b56b-4459-8e48-59977b214a1a)
![cvat2](https://github.com/cvat-ai/cvat/assets/55626513/64245c98-2a80-4587-b2d5-eca4090b96a0)
![cvat3](https://github.com/cvat-ai/cvat/assets/55626513/eeec92cf-01f3-4950-8806-dcfc8fa326cb)

[chrome_console_error_message.txt](https://github.com/cvat-ai/cvat/files/15005063/chrome_console_error_message.txt)

### Environment

```Markdown
Ubuntu 20.04.1
docker version 25.0.3
```

**Comment by bsekachev** [comment]
Hello,
Please, check the serverless function container logs. We can't help with custom models.

**Comment by soohwanlim** [comment]
Does that mean I can't use custom model for automatic annotation in cvat?
Thank you for your answer.

**Comment by soohwanlim** [comment]
thankyou for answer i solved it

**Comment by dharagg07** [comment]
how did you solve it?
