### ISSUE TITLE
Question : is cvat support video annotation for action recognition (like 0:30 to 1:02 drinking water)

### ISSUE THREAD

**Issue by sourabCV** [cvat-ai/cvat#7782]
I am not able to find how to annotate a video for action recognition. In a video, I need to specify from this time to this time person talking with someone like this. 

![image](https://github.com/cvat-ai/cvat/assets/144662563/af8bd7c1-0ae7-43b5-bc18-423af6f408ba)

Pls someone guide me if this features is available

**Comment by bsekachev** [comment]
You may use rectangle tracks for that. Please, refer to the documentation.
