### ISSUE TITLE
CVat lags with more than 1000 annotations

### ISSUE THREAD

**Issue by Jefjaica** [cvat-ai/cvat#7790]
Hello, I have images with annotations that exceed 1000. Every time we make annotations past 1000 the tool lags and this slows down the speed. Kindly help

**Comment by bsekachev** [comment]
Duplicate https://github.com/cvat-ai/cvat/issues/3875

**Comment by Jefjaica** [comment]
This has been closed as a duplicate. Is there any update on the previous tickets by the other users?

**Comment by bsekachev** [comment]
Nobody is working on the issue
