### ISSUE TITLE
It take too long for the first click on a image using SAM deployed with GPU

### ISSUE THREAD

**Issue by gwengusc** [cvat-ai/cvat#7793]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

CVAT is deployed on AWS ec2 instance of Ubuntu, I run Chrome locally on MAC to remotely connect to the ec2 instance. SAM is deployed with GPU.

For the first click on a element in a image, it can always be more than 6 seconds and up to 10+ seconds. After that, it is much faster.
 
Image embedding only takes 2 seconds.
I print out duration of runtime for every line in cvat/serverless/pytorch/facebookresearch/sam/nuclio/main.py and cvat/serverless/pytorch/facebookresearch/sam/nuclio/model_handler.py, check the log using command: docker logs [container id]. Other than initializations, self.predictor.set_image(np.array(image)) in model_handler.py takes 2 seconds. 

I do not know where can be the root cause that takes such a long time for the first click. 

I thought it is the network bottleneck. However, in network traffic, a file of size 7.3MB only took 275ms.
Those request to SAM, which is http://localhost:8080/api/lambda/functions/pth-facebookresearch-sam-vit-h?org=, takes 8-9 seconds with file size of 4.2MB
![Screenshot 2024-04-22 at 4 20 44 PM](https://github.com/cvat-ai/cvat/assets/32805596/09de4429-cdca-4e6c-a1c8-6cf1912368b5)
 

### Describe the solution you'd like

Can we identify where can be the root cause for high latency? It must be something other than SAM being called, other modules in CVAT. But I do not know where it can be. Is there a way to make it faster?

**Comment by gwengusc** [comment]
@bsekachev Thanks god, you are there! This issue is so urgent for me. Really appreciate if you can help.

**Comment by gwengusc** [comment]
Chrome runs on MAC. I notice that handle() in ModelHandler only returns features of image_embedding. Where is the code for the next step? It should be the step for segmentation, right?

**Comment by bsekachev** [comment]
The next step for segmentation is in the browser, implemented with onnx decoder: https://github.com/cvat-ai/cvat/tree/develop/cvat-ui/plugins/sam

That is why following clicks are quick.

**Comment by gwengusc** [comment]
I am confused. So where is the code takes so long for the first click? image embedding only takes 2 seconds. 4.2MB network traffic should not take such long time...

**Comment by gwengusc** [comment]
Where is the code calls handler() in main.py? Can those steps before this method takes a long time?

**Comment by bsekachev** [comment]
There may be many things: receiving data from cloud storage, preparing original data chunk, sending images from CVAT server to the server where the function is deployed, getting everything back to client. Need to investigate you specific case.

**Comment by gwengusc** [comment]
which method is the first one get called in backend when this link http://localhost:8080/api/lambda/functions/pth-facebookresearch-sam-vit-h?org= is invoked?

**Comment by gwengusc** [comment]
> There may be many things: receiving data from cloud storage, preparing original data chunk, sending images from CVAT server to the server where the function is deployed, getting everything back to client. Need to investigate your specific case.

No cloud storage is used. All the data is within ec2 instance.  CVAT and SAM are deployed on the same instance.

**Comment by bsekachev** [comment]
> which method is the first one get called in backend when this link http://localhost:8080/api/lambda/functions/pth-facebookresearch-sam-vit-h?org= is invoked?

https://github.com/cvat-ai/cvat/blob/b6886dd0c2831cb3f845bb3ad056cc05f289636f/cvat/apps/lambda_manager/views.py#L1053

**Comment by gwengusc** [comment]
> > which method is the first one get called in backend when this link http://localhost:8080/api/lambda/functions/pth-facebookresearch-sam-vit-h?org= is invoked?
> 
> https://github.com/cvat-ai/cvat/blob/b6886dd0c2831cb3f845bb3ad056cc05f289636f/cvat/apps/lambda_manager/views.py#L1053

My understanding is that handler() in main.py is the last step in backend for this call, it is returning the data of image embedding to frontend. The data is 4.2MB.

**Comment by gwengusc** [comment]
> > which method is the first one get called in backend when this link http://localhost:8080/api/lambda/functions/pth-facebookresearch-sam-vit-h?org= is invoked?
> 
> https://github.com/cvat-ai/cvat/blob/b6886dd0c2831cb3f845bb3ad056cc05f289636f/cvat/apps/lambda_manager/views.py#L1053

Which container has the log for this method if I add print?

**Comment by bsekachev** [comment]
> Correct me if I am wrong. My understanding is that handler() in main.py is the last step in backend for this call, it is returning the data of image embedding to frontend. The data is 4.2MB.

Not directly to frontend, proxied via the server. 

> Which container has the log for this method if I add print?

`cvat_server`

**Comment by gwengusc** [comment]
> > Correct me if I am wrong. My understanding is that handler() in main.py is the last step in backend for this call, it is returning the data of image embedding to frontend. The data is 4.2MB.
> 
> Not directly to frontend, proxied via the server.

Does the server has any post process to the response from here before it returns to frontend?

Thank you so much for your response!

**Comment by gwengusc** [comment]
I found that the root cause is that the data transfer from ec2 instance to local machine is too slow. However, I use scp to download data from ec2 instance to local machine is much faster than this. I think it must be something about software instead of hardware. Do you think is there any code in CVAT may slow down the speed for http response downloading? Nginx.conf or something else?
<img width="698" alt="Screenshot 2024-04-24 at 5 59 30 PM" src="https://github.com/cvat-ai/cvat/assets/32805596/087ec9a2-631f-4e74-8044-cc8b4fdc60b3">

**Comment by DModjeski** [comment]
So currently there is no way to speed this up as its a call and response wait that is slowing the return down? Is there any work going toward https://github.com/cvat-ai/cvat/issues/6217 which would also make this issues root problem vanish?

**Comment by gwengusc** [comment]
I found the root cause. It is my bad. I used a third party service for secure connection, which increases the latency of network.

**Comment by li-jiping** [comment]
> I found the root cause. It is my bad. I used a third party service for secure connection, which increases the latency of network.

May I ask if you can tell me some details? I have also encountered this problem and have been searching for a long time without any clues.

**Comment by zhanghaihangandliuli** [comment]
请问一下如何实现使用GPU推理SAM模型，我在serverless使用sudo nuctl deploy --project-name cvat --path "`pwd`/pytorch/facebookresearch/sam/nuclio/"  --file "`pwd`/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml" --platform local指令但是出现以下错误
```
nuctl.platform.docker (W) Failed to run container {"err": "stdout:\nd174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n\nstderr:\n", "errVerbose": "\nError - exit status 125\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\n\nCall stack:\nstdout:\nd174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n\nstderr:\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\nstdout:\nd174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n\nstderr:\n", "stdout": "d174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n", "stderr": ""}
24.08.31 13:31:40.265                     nuctl (W) Failed to create a function; setting the function status {"err": "Failed to run a Docker container", "errVerbose": "\nError - exit status 125\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\n\nCall stack:\nstdout:\nd174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n\nstderr:\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\nFailed to run a Docker container\n    /nuclio/pkg/platform/local/platform.go:905\nFailed to run a Docker container"}

Error - exit status 125
    /nuclio/pkg/cmdrunner/shellrunner.go:114

Call stack:
stdout:
d174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.

stderr:

    /nuclio/pkg/cmdrunner/shellrunner.go:114
Failed to run a Docker container
    /nuclio/pkg/platform/local/platform.go:905
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:227
```
我的 NVIDIA 驱动版本为以下：
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A4000    Off  | 00000000:3B:00.0 Off |                  Off |
| 41%   43C    P8    16W / 140W |   8672MiB / 16376MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A4000    Off  | 00000000:AF:00.0 Off |                  Off |
| 41%   41C    P8    16W / 140W |      8MiB / 16376MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
NVIDIA Container Toolkit为如下：
```
(base) ubuntu@cvat:~/cvat-han$ dpkg -l | grep nvidia-docker
ii  nvidia-docker2                   2.14.0-1                                all          NVIDIA Container Toolkit meta-package

```
docker的daemon.json为：
```
{
  "runtimes": {
    "nvidia": {
      "path": "nvidia-container-runtime",
      "runtimeArgs": []
    }
  }
}

```
请问我该如何解决这个问题，万分感谢解答
