### ISSUE TITLE
automatic backup of annotations and datasets on TFS or Git

### ISSUE THREAD

**Issue by Oceane4973** [cvat-ai/cvat#7794]
Hello,

I would like to automatically store my annotations and dataset on TFS or Git. I would like to know if there is a way to configure it?

Here is what I would like to do: 
- User opens a task and annotates its data
- There must be an automatic backup
- The server receives the request and sends a new request to Git or TFS to store the dataset

This would allow me to manage the versionning of annotations, so I will need to access them later to retrieve and modify them.

I found another similar outcome but this one did not help me : [https://github.com/cvat-ai/cvat/issues/1118](https://github.com/cvat-ai/cvat/issues/1118)

**Comment by bsekachev** [comment]
Hello,

Please, use webhooks to write any customizations around CVAT.
