### ISSUE TITLE
Change analytics port

### ISSUE THREAD

**Issue by jloebl** [cvat-ai/cvat#7795]
Hey, easy question but i cant find information on this:

According to the doc (https://docs.cvat.ai/docs/contributing/development-environment/#cvat-analytics-ports) i need to open the ports 8282 and 8123 to access the analytics web ui. 

How do i change the analytics ports?  

I only found the clickhouse port in the docker-compose.dev.yml. Correct me if i am wrong but as long i dont use the dev version (i am using v2.12.0) this file gets ignored. So where are they defined?

**Comment by bsekachev** [comment]
In production analytics is not exposed outside as far as I remember. 
To access it you just enter `http://localhost:8080/analytics` and nginx proxies you to the right container within the docker network. 
So, the request is not really clear.
