### ISSUE TITLE
I can't create ground truth jobs via API error 500

### ISSUE THREAD

**Issue by claudiasofia18** [cvat-ai/cvat#7798]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Endpoint: /api/jobs
2. POST
3. Parameters
`{ "assignee": user_id - integer, "stage": "annotation", "state": "new", "type": "ground_truth", "task_id": task_id - integer, "frame_selection_method": "random_uniform", "frame_count": 5, "seed": 0, "frames": [ 0 ] }`
.... 

### Expected Behavior

I need to create ground truth jobs of several tasks in an automated way. I tried individually but I couldn't create it with the api.

### Environment

```Markdown
- Jupyter Notebook
```

**Comment by bsekachev** [comment]
`docker logs cvat_server`?

**Comment by claudiasofia18** [comment]
Oh Sure, 
Server version: 2.11.3

Core version: 15.0.2

Canvas version: 2.20.0

UI version: 1.63.4.

<img width="625" alt="image" src="https://github.com/cvat-ai/cvat/assets/66740354/4f588c31-46b0-41c4-8d02-6af6f18fec85">

**Comment by bsekachev** [comment]
Documentation is wrong. 
Try to send ``assignee_id`` instead.

If it does not work:

- Firstly create the job
- Secondly patch the job to set assignee

**Comment by claudiasofia18** [comment]
1. Trying with assignee_id gives me the same 500 error.

2. When creating a job:
type annotation
 I get the following:
<img width="1167" alt="image" src="https://github.com/cvat-ai/cvat/assets/66740354/1b8ae86e-b0b7-4e5a-bb77-53d5d2035356">

**Comment by bsekachev** [comment]
You may only create ground truth job.

**Comment by claudiasofia18** [comment]
Yes, I need to create ground truth jobs in an automated way, but it does not allow me to create any type of job. How to attach above.

**Comment by bsekachev** [comment]
At the your message above, I see you are trying to create annotation job, not ground truth job. See type field. 
Also, please create a ground truth job from the browser and in Network tab of Dev Tools look at the parameters that sent to the server.

**Comment by claudiasofia18** [comment]
In point 2 it was another test because changing the assigne_id did not work. So I tried to create a normal job, but if you take a look at the steps to reproduce it number 3, it does send the type ground_truth :). I have also tried to send only the required parameters such as the type and the task_id, there is no difference, the same error appears.

**Comment by claudiasofia18** [comment]
The parameters sent by the browser were:: 
`frame_count=5,
 frame_selection_method="random_uniform",
 task_id=7066,
 type="ground_truth`

Yes, the job was created.

But if I pass` assignee`, an error or the other parameters appear.

With `assignee_id` it created the job, but it was not assigned to the corresponding user, I will do it with the patch.

Thanks a lot for you help and time.
