### ISSUE TITLE
Can't read ContextImage in React Debug

### ISSUE THREAD

**Issue by valGavin** [cvat-ai/cvat#7799]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a 3D task with several `relatedImage`s
2. Open the task, and open the _React Component Debugger_ from the _Developer Mode_
3. Under `f key=".$relatedImage"`, look for `hAe` or simply search for `ContextImage`; and it'll show
![Screenshot from 2024-04-24 13-39-17](https://github.com/cvat-ai/cvat/assets/54397015/c066d7f0-6836-4e96-82e9-5dd9864a1126)
In the _console_, it says `Caused by: Error: Context reads do not line up with context dependencies. This is a bug in React Debug Tools.`

### Context

I'm trying to create a feature related to the `ContextImage`, and I need to check the _states_.

### Environment

```Markdown
Whatever in `app.cvat.ai`
```

**Comment by bsekachev** [comment]
If "This is a bug in React Debug Tools", please address the issue to React team
