### ISSUE TITLE
Is there a Frame Tagging interpolation in Video frames, until it is changed by the user.

### ISSUE THREAD

**Issue by ss21alb** [cvat-ai/cvat#7809]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I am trying to interpolate the tag to the next frame on the online version.

### Describe the solution you'd like

 Is it possible to interpolate the tag to the next frames.

### Additional context

NA

**Comment by bsekachev** [comment]
Duplicate #5716
