### ISSUE TITLE
"working_time" analytics caluculated incorrectly

### ISSUE THREAD

**Issue by PMazarovich** [cvat-ai/cvat#7816]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create the task
2. Annotate something
3. Change the frame and measure the timing of the frame change process (do it via "play" button)
4. Annotate something
5. go to point 3
6. etc.....
7. Check "/events" message in browser UI
8. Find "change:frame" event and see the "duration" field.
This value is much higher then the actual time of "change:frame" measurement. 
The time of change frame is around 2-3 seconds while in "duration" you may found 5-7s.
In the provided video you may see that the timestamp of the "change:frame" is 18:43.513, next event is at 18:45.517, whereas the "duration" of the "change:frame" is 5723ms which is not true. The actual difference is 2000ms.

https://github.com/cvat-ai/cvat/assets/57707673/40feb1ec-7d2a-4f5c-bd9d-25e7da0782d0

### Expected Behavior

The time should be calculated correctly
This behavior is corrupting the "working_time" property of the "payload" and this makes the "working_time" field in clickhouse "payload" field unusable and misleading.

### Possible Solution

Comment out this section:
if event["scope"] in self._COLLAPSED_EVENT_SCOPES:
    ....

or fix somehow the time measurement on the client side.

### Context

Taking in account the way how it is implemented in cvat. apps. events. serializers. ClientEventsSerializer , for one minute for one person working on the task we are getting > then 1 minute of work which is impossible.

In this document you see the dump from the clickhouse DB for 1 minute of work.
The total working time is 82 seconds out of 60 seconds in 1 minute. I was the only person who used this account for this task (so no parallel working with the same account on the same task)
[minute_annotation.xlsx](https://github.com/cvat-ai/cvat/files/15143586/minute_annotation.xlsx)

### Environment

```Markdown
local CVAT 2.9.2
```

**Comment by bsekachev** [comment]
Hello, 
Thanks for the report.
