### ISSUE TITLE
"project/task data loss

### ISSUE THREAD

**Issue by goodluck2q** [cvat-ai/cvat#7821]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1.docker-compose -f docker-compose.yml -f docker-compose.override.yml down
2.docker volume rm $(docker volume ls )---"Before the command finished executing, I entered Ctrl+C to terminate the command."
3.docker volume ls | grep cvat --- "The volume of cvat_cvat_data/db/keys/logs/share still exists."
4.docker-compose -f docker-compose.yml -f docker-compose.override.yml  up -d
5.When I re-entered the task, I found that the data of all tasks could not be loaded, and there was no data in /home/django/cvat/data/task.

### Environment

```Markdown
Docker version 20.10.17, build 100c701
Cvat version  <2.12
```

**Comment by bsekachev** [comment]
After this command:

``docker volume rm $(docker volume ls )---"Before the command finished executing, I entered Ctrl+C to terminate the command."`` 

Please, do not expect your data to exist.
Even if it not finished, it is not clear what happened with the data.
