### ISSUE TITLE
Could not receive image data Open the Browser Console to get details

### ISSUE THREAD

**Issue by Indirarajan** [cvat-ai/cvat#7822]
I am getting "Could not receive image data Open the Browser Console to get details" error message when uploading the jpg images for annotation. 

What could be the issue?

**Comment by bsekachev** [comment]
How can we reproduce it?

**Comment by bsekachev** [comment]
If that is local installation, you may check docker logs (e.g. `docker logs cvat_server`), but the command depends on CVAT version. 

If that is app.cvat.ai, we need job id and we may check logs on our side. 

Generally it is an error on the server.

**Comment by Indirarajan** [comment]
@bsekachev I am facing this error from today morning

**Comment by Indirarajan** [comment]
Job ID: #638014: OCR
Kindly check the logs and resolve the issue asap.

Thank you.

**Comment by bsekachev** [comment]
Access to the bound cloud storage is forbidden. Perhaps secrets are expired. 
The data can not be fetched.

**Comment by bsekachev** [comment]
So, please, try to update access/secret keys: https://app.cvat.ai/cloudstorages/update/1238

**Comment by Indirarajan** [comment]
How to update access/secret keys?

**Comment by bsekachev** [comment]
1. Go to cloud storage page
2. Select a cloud storage from the list
3. Open actions menu

![image](https://github.com/cvat-ai/cvat/assets/40690378/d4be4616-9ffa-4606-a05b-e8a3bf3d905a)


4. Click "Update"
5. Provide new keys

**Comment by Indirarajan** [comment]
Nothing is shown in cloud storage page for me, its empty for me..

**Comment by bsekachev** [comment]
Please, send the screenshot.

**Comment by bsekachev** [comment]
Perhaps you enabled the organization (I can't see because you drawn this information). When organization enabled, you see only the organization resources. So, go to personal workspace first.

**Comment by Indirarajan** [comment]
How to go to the personal workspace and what should I do next?

**Comment by bsekachev** [comment]
username?

**Comment by Indirarajan** [comment]
Username: Indirarajan

**Comment by bsekachev** [comment]
This username does not have access to the job, you specified before.

> Job ID: #638014: OCR

**Comment by Indirarajan** [comment]
I have deleted the older Job ID and currently working in the below job ID.

Job ID: #638498: Number Plate OCR

**Comment by bsekachev** [comment]
- You shared Task ID, not Job ID.
- Data in the shared task can be accessed

**Comment by Indirarajan** [comment]
Does it depend on the screen size? Because both of the screen sizes differ.

**Comment by bsekachev** [comment]
No, it does not.

**Comment by Indirarajan** [comment]
But I can open it in larger screen size devices but not in the smaller ones.
