### ISSUE TITLE
CVAT Can not connect to server

### ISSUE THREAD

**Issue by rps-COPT** [cvat-ai/cvat#7826]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

• Logged into [CVAT.ai](https://app.cvat.ai/)

### Expected Behavior

Project and task would open

**Comment by bsekachev** [comment]
Apologize for the inconvenience, the issue was resolved.

**Comment by rps-COPT** [comment]
Thank you for fixing. Appreciate it.
