### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by Sandesh-Rprocess** [cvat-ai/cvat#7827]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. https://app.cvat.ai/
2. Login with your ID
3. after login we are receiving the issue
4. Issue Pop-up : Cannot connect to server (screenshot attached)
![Screenshot 2024-04-30 083156](https://github.com/cvat-ai/cvat/assets/113497605/88f11d8d-fa3c-483c-a7b9-497496972ef9)

### Expected Behavior

Requesting to resolve the issue as soon as possible.

**Comment by lIlIAn-chAngwww** [comment]
encountering the same issue :/

**Comment by bsekachev** [comment]
Apologize for the inconvenience, the issue was resolved.

**Comment by Sandesh-Rprocess** [comment]
Thank you for your update and response.
