### ISSUE TITLE
Cannot open images on device with 1920 x 1080 display resolution, getting "Could not receive image data, Open the Browser Console to get details" Error message. 

### ISSUE THREAD

**Issue by Indirarajan** [cvat-ai/cvat#7831]
For annotating images, I can open the images on device with 1368 x 768 display resolution, but I cannot open it in on device with 1920 x 1080 display resolution I am getting "Could not receive image data Open the Browser Console to get details" Error message.

When I changed the device with higher display resolution, to the lower resolution, then also I cannot be able to open the image for annotation. Kindly look into this ASAP I am trying to annotate images for two days on CVAT.

**Comment by bsekachev** [comment]
Did you try to follow the advice in the error message? "Open the Browser Console to get details"
