### ISSUE TITLE
Update login form for self hosted CVAT installation

### ISSUE THREAD

**Issue by mdtraining05** [cvat-ai/cvat#7835]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Background and requirement :We have a self hosted CVAT server v2.11 with docker on Ubuntu. We have Active directory enabled for login.
There is a need to customize the login form to meet Organization standard. One specific detail is "Email or username" needs to be replaced by "<Org login ID>".

Steps taken:

1. Navigate to <install directory>/cvat
2. perform export of environment variables : CVAT_HOST & ACME_EMAIL
3. Perform CVAT_VERSION=v2.11.0 docker compose down
4. Navigate to <install directory>/cvat/cvat-ui/src/components/login-page
5. edit login-form.tsx with vi editor
6. locate the text "Email or username" and alter the text and save the changes
7. Perform export of environment variables and execute CVAT_VERSION=v2.11.0 docker compose up -d

**Inquiry** : 
Other than changes to login-form.tsx, are there any other file changes needed for login form to be altered?

### Expected Behavior

Result / Issue faced : the login page is yet the same. Ideally it is expected that altered text is reflected instead of "Email or username" in the user input of login fporm.
Changes are not reflecting.

### Possible Solution

 I also tried performing docker compose build before up and deleting the cache db container to refresh the cache. These options are not changing the result.

**Comment by bsekachev** [comment]
After changing source code you have to rebuild images. `docker compose up -d` does not rebuild images, only starting containers.

Also you specified release version in `CVAT_VERSION`, saying docker compose to ignore any changes, using release pre-built images. 

Try `docker compose up -f docker-compose.yml -f docker-compose.dev.yml -d --build` instead.
