### ISSUE TITLE
Export Project As Dataset Not an option

### ISSUE THREAD

**Issue by jacobadodge** [cvat-ai/cvat#7841]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Go to projects
2. Select desired project
3. Select 'Actions' with the 3 dots at top right
4. Only available action is 'Delete'. No option to export project as dataset

### Expected Behavior

Be able to export project as dataset

### Context

I have multiple tasks within a single project project that I want to export as a single COCO dataset

**Comment by bsekachev** [comment]
Which CVAT version do you use?
