### ISSUE TITLE
Color Error during uploading of segmentation mask 1.1

### ISSUE THREAD

**Issue by t0wgster** [cvat-ai/cvat#7847]
Hi everyone,

I'm using CVAT for my master thesis and I am currently encountering a problem during uploading my own segmentation mask 1.1 into CVAT. Due to various reasons, i created my own segmentation masks and want to upload them back into CVAT because I want to edit them. 

```
This is the error code that I encounter:
Could not import dataset to the [project 1](......)
Error: Request failed with status code 500. "datumaro.components.errors.AnnotationImportError: Failed to import item ('images/20230308_111122-111552 SurfaceDefect/004116_20230308_111134.796912', 'default') annotation: Undeclared label '255'\n"..
```

The class that I'm uploading is depicted as white in my segmentation masks. I already changed its color to white in the labelmap.txt file as well as in the constructor but I'm still encountering the same error.

![unnamed](https://github.com/cvat-ai/cvat/assets/125188064/edc07b5e-dc1a-499c-acae-f1e7ba7e6839)

Is there anything else I could try out?

Thanks in advance for your help!

**Comment by bsekachev** [comment]
How many classes you have in labelmap?

**Comment by t0wgster** [comment]
Thanks for the response, 8 i think, but then i changed it to 10. Do i also have to adjust that in my labelmap file?

**Comment by zhiltsov-max** [comment]
Hi. The error should indicate that there are some class mask pixels with the value 255, which are not found in the `labelmap.txt`.

**Comment by t0wgster** [comment]
Hi Max, thanks for responding. Yeah that makes sense, because I was using binary masks (for a good reason). I thought that by converting the numpy array into a .png file, the colors would automatically assume RGB values. I will report whether by changing the masks to a 3-channel image helped.
