### ISSUE TITLE
How to attach manifest.jsonl with task

### ISSUE THREAD

**Issue by PushpakBhoge512** [cvat-ai/cvat#7849]
I want to skip the time it takes to attach data to a task (where I assume it download all the images and prepare manifest.jsonl)
 I read here that an task level manifest jsonl can be attached https://docs.cvat.ai/docs/manual/advanced/data_on_fly/
 
 but did not find a way to do that

**Comment by bsekachev** [comment]
Add this file to the list of uploaded files. 
That is about creating tasks from cloud storages.
