### ISSUE TITLE
Chrome browser tab page consumes lots of memory

### ISSUE THREAD

**Issue by zldrobit** [cvat-ai/cvat#7850]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

After opening and closing several annotation jobs, the memory consumption rises from several hundred MBs (e.g., 200MB) to several GBs (e.g., 4GB).

### Expected Behavior

The memory consumption does not enlarge when switching to another annotation job on the same tab page.

### Possible Solution

After manually refreshing the tab page, the memory consumption drops to several hundred MBs.

### Environment

```Markdown
- Git hash commit (`git log -1`): aecaba66db8c3a7cd5f17947318fa277471648f6
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.1
- Are you using Docker Swarm or Kubernetes?
No, I'm using Docker compose.
- Operating System and version (e.g. Linux, Windows, MacOS):
Linux: Ubuntu 20.04.3 LTS
```

**Comment by bsekachev** [comment]
From code level we can't enforce JS garbage collector to be called. 
Does it work infinitely until crashing Chrome tab?

**Comment by zldrobit** [comment]
Yes, the browser crashed after the memory consumption went up to more than 10GB. Closing the crashed tab page, the browser works again.

**Comment by bsekachev** [comment]
I believe this pull request will help https://github.com/cvat-ai/cvat/pull/7995
