### ISSUE TITLE
Connected file sharing with thumbnails

### ISSUE THREAD

**Issue by davy-blavette** [cvat-ai/cvat#7858]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I'm seriously thinking of taking over cvat to add a lot of features, I'd have to join the team but for the moment I'm still discovering the project. I'd like to add a thumbnail to files (share mount), but I'm not sure where to start. components > file-manager.tsx? I'm a bit lost for adding the img tag and finding the filename, if you could help me a bit ^^

![image](https://github.com/cvat-ai/cvat/assets/3437490/78b30a75-18d9-41bd-9337-df5a13b31fc2)

### Describe the solution you'd like

Have an image thumbnail instead of the file name

**Comment by bsekachev** [comment]
Hello,

This minor improvement is gonna be very difficult.
And here you need to start from the server part. Client does not attach to a cloud storage directly.

**Comment by davy-blavette** [comment]
Thanks for your answer.
Yes, it's server-side, I see there's an API call: 
http://192.168.2.46:8080/api/server/share?org=&directory=20240422_163814%2F

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/vnd.cvat+json
Vary: Accept

[
    {
        "name": "product _20240506_001.png",
        "type": "REG",
        "mime_type": "image"
    },
    {
        "name": "product _20240506_002.png",
        "type": "REG",
        "mime_type": "image"
    },

Just add "base64/img": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQ"?

...so on http://192.168.2.46:8080/api/docs/#tag/server/operation/server_list_share and to modify this it's with cvat-cli!?

**Comment by bsekachev** [comment]
I do not think we will work on this.
