### ISSUE TITLE
[QUESTION] Different COCO annotation IDs between raw JSON and CVAT interface

### ISSUE THREAD

**Issue by astringfield** [cvat-ai/cvat#7866]

**Comment by astringfield** [comment]
I've noticed that for an COCO object that's annotated as multiple polygons, the raw JSON file and the CVAT, they display slightly differently between the JSON labels file and the CVAT interface. 

In the raw JSON file, the annotation will be assigned a single ID, e.g.:
```json
        {
            "id": 212,
            "image_id": 70,
            "category_id": 1,
            "bbox": [
                121.0,
                518.0,
                23.0,
                21.000000000000004
            ],
            "segmentation": [
                [
                   ...
                ]
                [
                   ...
                ]
            ],
            "area": 483.00000000000006,
            "iscrowd": 0,
            "supercategory": ""
        },
```

while in the CVAT GUI, there will be a unique ID for each of the polygons in the "grouped" annotation. As a result, the annotation IDs in the raw JSON file won't always match those shown in CVAT. Is this behaviour expected, and is there a way to ensure the IDs always match between the file and the GUI? 

Thanks!

**Comment by bsekachev** [comment]
Hello,

There is not any correlation between IDs you see on UI interface and COCO exported annotations.

**Comment by astringfield** [comment]
Thanks @bsekachev :+1:
