### ISSUE TITLE
CVAT on AWS EC2 not working.

### ISSUE THREAD

**Issue by nikste** [cvat-ai/cvat#7870]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

open new ec2 instance
with following security rules:
![security_rules_aws](https://github.com/cvat-ai/cvat/assets/11996097/fd2e4d41-4686-4b9f-9b2b-0256aba80e8b)

install docker
clone cvat
run cvat with:
CVAT_HOST=<ec2address>.compute-1.amazonaws.com sudo docker compose up

### Expected Behavior

going to <ec2address>.compute-1.amazonaws.com in your browser shows cvat ui.
instead shows:
![unable_to_connect](https://github.com/cvat-ai/cvat/assets/11996097/4eee6c63-147e-441b-ae90-0ddf7a80d512)

### Possible Solution

serving a simple http page with python works.
Am i doing something wrong here ?

### Environment

```Markdown
current master (9dcba6a55e4978e69530606ef4e356a876c88e5f)
```

Thanks for your input

**Comment by bsekachev** [comment]
Unfortunately we can't help with custom infrastructure on AWS deployment.
