### ISSUE TITLE
Azure Kubernetes Service: Helm Chart w/ External Port

### ISSUE THREAD

**Issue by ifTaylor** [cvat-ai/cvat#7871]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I'm not able to access the application from a service with an external port. I have deployed the cluster to an Azure Kubernetes Service by setting the cluster subscription, downloading cluster credentials, and following the [deployment](https://docs.cvat.ai/docs/administration/advanced/k8s_deployment_with_helm/#deployment) process. I am not able to attribute the `nginx` external loadbalancer IP that ASK provides within the `values.override.yaml`. Services are running, but I am not able to access the application.

### Describe the solution you'd like

1. Provide a LoadBalancer service.
2. Help attributing the AKS `nginx` external IP.

### Describe alternatives you've considered

`docker-compose up -d` using the `docker-compose.yaml` works flawlessly. I tried to convert the file using `kompose`, but was not able to get that working either.

**Comment by IWang20** [comment]
Did you ever find out the solution to the 404? I'm encountering a similar error on my end.
