### ISSUE TITLE
Could not save annotations (seems like cross referencing of attributes to other classes)

### ISSUE THREAD

**Issue by PushpakBhoge512** [cvat-ai/cvat#7875]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I was not able to find any solid lead but I think it could be happening because of following
if project is created and then the labels config is modified of earlier labels then this is observed (but this also not consistent sometime happen sometime does not)
e.g. if I create project with 10 labels then after some time I realized I want to add few attrbute to label with id 3 after this issue occur this also incosistent sometimes occur sometime does not 

### Expected Behavior

I think if an attribute A is attached to label_id1  then in the attribute should only be assigned to that but here attribute A get attached to label C and that not allows me to save

### Possible Solution

not sure I don't know javascript so not exactly sure what's happening here

### Context

![image](https://github.com/cvat-ai/cvat/assets/80240057/5e5675f3-632a-45dd-bced-75a817b2e39d)
this is the error I get, this seems like cross reference of the attributes as explained above 
if there are 5 labels attribute which is of label 3 is assigned to label 5, this cross referencing happening randomely with any attribute any label

when I inspect the body of save API and based on dataset I find out the frame on whihc this cross reference is occuring then I go to that frame delete all annotation and do it again then it solves (but it comes back later randomly)
as in image the spec_id (i,e, attribute id 106 is attached to some other class )

this has also been observed in database some time attribute id is mapped with label to which it does not belong this also causing weird saved annotations. This happening for some projects not all, this project have one thing in common that extra values were added later in attribute of input type `radio` and mutable is set to false

### Environment

```Markdown
using linux
using cvat 2.11.0
```

**Comment by PushpakBhoge512** [comment]
# *update*
I forgot to mention one important thing
I am using MySQL database instead of PostgresSQL, I do get some warning that some constratints are not supported
is the issue could be caused due to this ? the data is also wrongly saved in following tables 

engine_labeledshapeattributeval
engine_labeledshape

please help could this be the issue? if yes then how can the support added ?

**Comment by bsekachev** [comment]
That is not clear how to reproduce the issue on standard configuration. 
We can't help with customizations. A lot of information and access to the instance is required to investigate such issues. Sorry.
