### ISSUE TITLE
CVAT video playback extremely slow when more than 1000 labels are defined.

### ISSUE THREAD

**Issue by apiszcz** [cvat-ai/cvat#7876]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

When using > 1000 labels the playback speed of videos is not viable.

### Expected Behavior

Ideally the speed would be the same when there are no labels defined.

**Comment by bsekachev** [comment]
Duplicate of #3875
