### ISSUE TITLE
Cache interactor

### ISSUE THREAD

**Issue by davy-blavette** [cvat-ai/cvat#7885]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

On a job I'm using SAM interactor to delimit areas to be labeled with polygons. I've noticed that for each new image there's a loading of the model...I don't understand why this 4mo model is loaded each time and not cached (?).

![image](https://github.com/cvat-ai/cvat/assets/3437490/fc82ecbc-0cfd-4156-8fa0-8047e499dffe)

**Comment by bsekachev** [comment]
SAM is encoder-decoder based model. 

What you see, are embeddings for the image, encoded on the server side. Not the model weights.
Then these embeddings together with clicks are decoded on client into binary masks.
