### ISSUE TITLE
I can not export the dataset after I labeling the rectangle dataset today. I can export successfully before.

### ISSUE THREAD

**Issue by wydilearn** [cvat-ai/cvat#7887]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

![屏幕截图 2024-05-14 150234](https://github.com/cvat-ai/cvat/assets/104293103/aa265f1c-3c54-448e-938e-1624b5d61c9d)

### Expected Behavior

export the dataset successfully. I have checked the network, but i can not find any error.

**Comment by bsekachev** [comment]
There were some server-side issues this morning. We apologize for that.
Now the instance is working. Please, try export one more time .
