### ISSUE TITLE
Unable to Login app.cvat.ai Today

### ISSUE THREAD

**Issue by oycTechV** [cvat-ai/cvat#7888]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1.  Go to https://app.cvat.ai/auth/login
2. Click [Create an account](https://app.cvat.ai/auth/register)
3. Error Appeared
TypeError
r.map is not a function

TypeError: r.map is not a function
    at Qx (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:7340470)
    at Xi (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5843017)
    at zo (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5851864)
    at Fo (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5851683)
    at Lo (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5851366)
    at ws (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5892591)
    at xl (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5881823)
    at El (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5881748)
    at hl (https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5878771)
    at https://app.cvat.ai/assets/cvat-ui.6cd38ef4eb8ad59e17c6.min.js:2:5830426
![Untitled](https://github.com/cvat-ai/cvat/assets/126563185/182837cd-5109-44bd-b147-850835838612)

### Expected Behavior

https://app.cvat.ai/auth/login should allow user to login using google account

### Possible Solution

Possibly login credential management server died

### Context

Trying to start a new annotation. Suddenly server is unreachable and then when reachable this happened

### Environment

```Markdown
Visit using google chrome, google company account
```

**Comment by bsekachev** [comment]
There were some server-side issues this morning. 
Now the instance is working.

**Comment by O-J1** [comment]
> There were some server-side issues this morning. We apologize for that. Now the instance is working.

I dont believe this is correct, even now, for the last 3-ish hours I have not been able to annotate. Right now when I log in it just infinitely loads and 9/10 my projects will not show up and I get error messages like:

"Could not get models from the server

e.response is undefined"

"Could not fetch models meta information

Network Error."

"Error during fetching a job

Network Error."

and "Could not fetch tasks

Network Error."

**Comment by bsekachev** [comment]
Hello,

1. Please, do not hide URL. Your date are protected by permissions system. Anybody from the internet will not be able to open the link. And we need this URL to reproduce the issue.
2. Please, follow this link https://speedtest.globalaccelerator.aws/#/ amd try to perform speed tests in different regions. Share us with results.

**Comment by oycTechV** [comment]
Hi @bsekachev , thanks for following the thread. 
This is the screenshot
![testFromMalaysia](https://github.com/cvat-ai/cvat/assets/126563185/97cb9317-33a3-4d9f-92ed-53c8ce5ade6b)

**Comment by bsekachev** [comment]
Our server is in Ireland. 

With your internet provider 100KB, took 1.9 seconds to download.
Data chunk with image 613 is 9.2 Megabytes (the chunk contains 68 images overall). 

From this, it will be approximately downloaded in 175 seconds.

**Comment by oycTechV** [comment]
Noted, thanks you @bsekachev 
I found that it tooks more than 10 minutes without changes at the page
Following the investigation I found this at the error console
![image](https://github.com/cvat-ai/cvat/assets/126563185/a90af7f6-383e-4770-9359-d21cd7230d8b)
                        try {
                            const o = await yr.get(`${i}/jobs/${t}/data`, {
                                params: {
                                    ...fr(),
                                    quality: r,
                                    type: "chunk",
                                    number: n
                                },
                                responseType: "arraybuffer"
                            })
                              , s = +(o.headers || {})["content-length"];
                            if (Number.isInteger(s) && o.data.byteLength < +s) {
                                if (a < 10)
                                    return setTimeout((()=>{
                                        throw new Error(`Truncated chunk, try: ${a}. Job: ${t}, chunk: ${n}, quality: ${r}. Body size: ${o.data.byteLength}`)
                                    }
                                    )),
                                    await e(t, n, r, a + 1);
                                throw new Error(`Truncated chunk. Job: ${t}, chunk: ${n}, quality: ${r}. Body size: ${o.data.byteLength}`)
                            }
                            return o.data
                        } catch (e) {
                            throw vr(e)
                        }

**Comment by bsekachev** [comment]
This is not an error actually. This is special exception that we log to understand how popular the following problem is.

When network is unstable, chunk transmission from server to client may get broken and chunk is not fully downloaded (truncated, as message says).

In this case, CVAT client does one more try to download the chunk from scratch. And we throw this exception to see it in our analytics.

**Comment by oycTechV** [comment]
![image](https://github.com/cvat-ai/cvat/assets/126563185/3eb2dff9-2344-4146-85c8-09ac3119269b)
My previous load of annotation is from 800.
Now when I refresh, it seems that my annotation from 700 to about 900 (my latest progress) is wiped out
