### ISSUE TITLE
Automattic annotations

### ISSUE THREAD

**Issue by zloykaban** [cvat-ai/cvat#7891]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

Hello team,

I hope this message finds you all in good spirits. I apologize if this question has already been answered; I've searched but haven't found anything relevant on the web. I'm currently using CVAT and would like to integrate auto-annotation using my own pre-trained YOLOv8 model, which is deployed through Nuclio. At the moment, I am setting up new tasks through some ETL automation, but I can't seem to find any API endpoints that would allow me to execute auto-annotation programmatically. Does anyone in the community know the proper way to achieve this?

Thank you!

### Describe the solution you'd like

api endpoint like tasks/{task_id}/auto_annotation/start

**Comment by bsekachev** [comment]
`<CVAT_HOST>/api/swagger` - shows all API endpoints
`POST lambda/requests` responsible for async automatic annotation on a task (in a background)
`POST /api/lambda/functions/{func_id}` is responsible for automatic annotation on a frame (online)
