### ISSUE TITLE
Provision for assigning single task to multiple users 

### ISSUE THREAD

**Issue by shreshthasingh00** [cvat-ai/cvat#7895]
I am looking for a feature where I can assign a job to multiple users and they are able to annotate the task independently and simultaneously. Does this feature already exist in cvat? Please share the relevant documentation if already exits.

**Comment by bsekachev** [comment]
One job cannot be annotated by multiple users. 

If you mean something like annotation consensus (when several users annotate the same frames to achieve higher annotations quality), we are participating in Google Summer of Code and it is gonna be implemented this year.
