### ISSUE TITLE
Task Filter & Quick Filter Return Nothing When Filtering On Assignee

### ISSUE THREAD

**Issue by Michael-Blackwell** [cvat-ai/cvat#7896]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Using Docker, pull the latest CVAT release and create a project/task
2. Assign the task to a user
3. Using either the quick filter or rules-based, filter for tasks assigned to that user

No tasks will show as a result. 

### Expected Behavior

Tasks assigned to the filtered user should be returned.

### Context

We are unable to annotate as a team if workers cannot easily find tasks assigned to them.

### Environment

```Markdown
- CVAT release: 2.13.0
 - Docker Version: 23.0.4
 - Deployment: Docker Compose
 - OS: RHEL 8.7
```

**Comment by bsekachev** [comment]
I can't reproduce the issue from these steps.
Please, provide a screencast.

**Comment by Michael-Blackwell** [comment]
After some experimentation, I realize that I was assigning jobs instead of tasks, which is why nothing was being returned. Therefore, this issue is not a bug, but an opportunity to improve the filtering mechanisms. It might make sense to add a filter field which specifies between filtering on jobs , tasks, or both.

**Comment by bsekachev** [comment]
- On jobs page you are filter jobs
- On tasks page you filter tasks
- On projects page you filter projects
