### ISSUE TITLE
Wrong task status in task_api

### ISSUE THREAD

**Issue by cile98** [cvat-ai/cvat#7900]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a task in the project
2. Change stage to `acceptance`
3. Change status to `Completed`
4. List tasks using task_api and check the status
5. Status won't always be 'completed' (in my case it was 'validation')

### Expected Behavior

The task status is 'completed'. If you use the 'Finish the job' button from the dropdown menu then the status in the API is  actually reflected properly.

### Context

I'm trying to get a list of tasks that are completed.

**Comment by bsekachev** [comment]
Hello, 

> Change status to Completed

What do you mean here? **Status** is outdated and read-only property for jobs. You need to use **State**.

Please, try to reproduce on `app.cvat.ai` and send us a task id.

**Comment by cile98** [comment]
> Hello,
> 
> > Change status to Completed
> 
> What do you mean here? **Status** is outdated and read-only property for jobs. You need to use **State**.
> 
> Please, try to reproduce on `app.cvat.ai` and send us a task id.

Sorry, I did mean `State`. Here's the id: `676168`

**Comment by cile98** [comment]
Here is the screenshot from `app.cvat.ai` 
![image](https://github.com/cvat-ai/cvat/assets/23198302/c7ee73f6-31da-43f8-8500-783ee4aeed78)

**Comment by cile98** [comment]
And here's the response from API (deleted irrelevant fields): 
```
({'assignee': None,
 'bug_tracker': '',
 'created_date': datetime.datetime(2024, 5, 16, 10, 11, 11, 471423, tzinfo=tzutc()),
 'data_chunk_size': 24,
 'data_compressed_chunk_type': 'imageset',
 'data_original_chunk_type': 'imageset',
 'dimension': '2d',
 'guide_id': None,
 'id': 676168,
 'image_quality': 70,
 'jobs': {'completed': 1,
          'count': 1,
          'url': 'https://app.cvat.ai/api/jobs?task_id=676168',
          'validation': 0},
 'labels': {'url': 'https://app.cvat.ai/api/labels?task_id=676168'},
 'mode': 'annotation',
 'name': 'test cvat',
 'overlap': 0,
 'segment_size': 1,
 'size': 1,
 'status': 'validation',
 'subset': '',
 'updated_date': datetime.datetime(2024, 5, 16, 10, 11, 20, 994846, tzinfo=tzutc()),
 'url': 'https://app.cvat.ai/api/tasks/676168'}

**Comment by bsekachev** [comment]
Okay, thanks, we will take a look

**Comment by bsekachev** [comment]
In couple of days the new release will be deployed on app.cvat.ai
