### ISSUE TITLE
Invitation Emails are sent with example.com as sitename even though CVAT_HOST is configured.

### ISSUE THREAD

**Issue by sahil-chachad-qure** [cvat-ai/cvat#7904]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

downloaded repo and used the existing docker-compose to build the images. Post this deploy on AWS

export CVAT_HOST=mydomain.com

docker-compose up -d

### Expected Behavior

Emails received should be received through mydomain.com but instead are being received by example.com
![Screenshot 2024-05-17 143704](https://github.com/cvat-ai/cvat/assets/113027442/f1417f28-2403-4071-b7f8-0f73b592e9af)

### Environment

```Markdown
- AWS hosted
- Docker images
```

**Comment by bsekachev** [comment]
Duplicate https://github.com/cvat-ai/cvat/issues/7707
