### ISSUE TITLE
RAM consumption 

### ISSUE THREAD

**Issue by cile98** [cvat-ai/cvat#7909]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

When labeling on `app.cvat.ai` using `SAM` after some amount of samples RAM consumption gets quite high and the page regularly crashes. 
![image](https://github.com/cvat-ai/cvat/assets/23198302/e271f025-05e8-4a4d-87c4-b88624f92cf0)

### Possible Solution

My theory is that extracted image embeddings are stored in the cache, so I'd propose limiting the number of kept embeddings if that's the case

**Comment by bsekachev** [comment]
> My theory is that extracted image embeddings are stored in the cache, so I'd propose limiting the number of kept embeddings if that's the case


Number of embeddings already stricted by 32 (about 128 MB). 
But we will check.

**Comment by cile98** [comment]
Hard to say, but approx every ~100 labeled images

**Comment by bsekachev** [comment]
May you please share a task ID on app.cvat.ai?

**Comment by cile98** [comment]
I was just able to recreate it. First I did task 672159 where I annotated 46 out of 106 images. By the end of the task RAM consumption was at 4.6Gb. Then I've started task 672162 and labeled 30 out of 154 (was at image 56) and RAM consumption reached 6.6Gb and the tab crashed.  So apparently RAM doesn't get released once the task is switched

**Comment by bsekachev** [comment]
I believe this pull request will help https://github.com/cvat-ai/cvat/pull/7995
