### ISSUE TITLE
BufferedReader API SDK works every other time

### ISSUE THREAD

**Issue by davy-blavette** [cvat-ai/cvat#7925]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I use the command line API with a script like :
`parser.add_argument("pid", help="Project ID (CVAT)", type=int)
parser.add_argument("--export", default=True,  help="Export projet CVAT")
parser.add_argument("--format", default='COCO 1.0', help="Format export", choices=['COCO 1.0', 'b', 'c'])
parser.add_argument("--model", default='yolov8', help="Model type", choices=['yolov8', 'b', 'c'] )
parser.add_argument("--epochs", default=100, help="Total number of training epochs.")
parser.add_argument("--imgsz", default=350, help="Target image size for training.")
args = parser.parse_args()

def main(args):
    if args.export:
        export_Project(args.pid, args.format)
        sys.exit()
    if args.model:
        print(args.model)
        sys.exit()

def export_Project(pid, format):
    with ApiClient(CONFIGURATION) as api_client:
        id = pid  # int | A unique integer value identifying this project.`

....and I use python Train.py 1 where 1 is the ID Project...

### Expected Behavior

I would like to take this opportunity to tell you that you have done an excellent job and that I am satisfied with CVAT! I'm currently using your API (SDK) to export a project dataset. and it's quite surprising, I have a cache buffer problem every other time...the project only exports well every other time, otherwise I have a tmp file at 0k0...and it doesn't cause any errors.

https://docs.cvat.ai/docs/api_sdk/sdk/reference/apis/projects-api/#retrieve_dataset

![image](https://github.com/cvat-ai/cvat/assets/3437490/18314ef7-4a84-49e3-b348-2408c9cc08ed)

### Possible Solution

I think there's a buffer close missing somewhere :

```
class TestReader(BufferedReader):
    def close(self):
        self.closed = True
```

**Comment by davy-blavette** [comment]
It's not very clean, I re-run the function if the temporary file isn't the right one...which works.

```
            if tmpFile == data.name:
                unzip_Project(filename, tmpFile)
            else:
                os.remove(data.name)
                export_Project(pid, format)
```

**Comment by zhiltsov-max** [comment]
Hi, could you be more specific about the SDK APIs used? I can see there is some custom code used. The `retrieve_dataset()` function mentioned doesn't cache datasets on the client side.

**Comment by davy-blavette** [comment]
Hi @zhiltsov-max 

I used the code indicated in the documentation :

```
from pprint import pprint

from cvat_sdk.api_client import Configuration, ApiClient, exceptions
from cvat_sdk.api_client.models import *

# Set up an API client
# Read Configuration class docs for more info about parameters and authentication methods
configuration = Configuration(
    host = "http://localhost",
    username = 'YOUR_USERNAME',
    password = 'YOUR_PASSWORD',
)

with ApiClient(configuration) as api_client:
    id = 1 # int | A unique integer value identifying this project.
    action = "download" # str | Used to start downloading process locally after annotation file has been created (optional)
    cloud_storage_id = 1 # int | Storage id (optional)
    filename = "filename_example" # str | Desired output file name (optional)
    format = "format_example" # str | Desired output format name You can get the list of supported formats at: /server/annotation/formats (optional)
    location = "cloud_storage" # str | Where need to save downloaded dataset (optional)
    rq_id = "rq_id_example" # str | rq id (optional)
    use_default_location = True # bool | Use the location that was configured in project to import dataset (optional) if omitted the server will use the default value of True

    try:
        (data, response) = api_client.projects_api.retrieve_dataset(
            id,
            action=action,
            cloud_storage_id=cloud_storage_id,
            filename=filename,
            format=format,
            location=location,
            rq_id=rq_id,
            use_default_location=use_default_location,
        )
    except exceptions.ApiException as e:
        print("Exception when calling ProjectsApi.retrieve_dataset(): %s\n" % e)
```

this code exports the project in the zip format /tmp/filename.

then I do :

` unzip_Project(tmpFile, project)``

**Comment by zhiltsov-max** [comment]
Ok, thank you for reporting the problem. Please try to use the `_parse_response=False` parameter as described [here](https://docs.cvat.ai/docs/api_sdk/sdk/lowlevel-api/#receiving-data) or use the higher-level API [function](https://github.com/cvat-ai/cvat/blob/8d4c42e16e03ab618705f9d12b4d2b34b1553a47/cvat-sdk/cvat_sdk/core/proxies/projects.py#L69) (the usage is similar to [this for tasks)](https://github.com/cvat-ai/cvat/blob/8d4c42e16e03ab618705f9d12b4d2b34b1553a47/tests/python/sdk/test_tasks.py#L284-L294).
