### ISSUE TITLE
Modify imported ellipses

### ISSUE THREAD

**Issue by alfakat** [cvat-ai/cvat#7928]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I really like that ellipse figure in annotation and had some project to annotate with it. I have my detected areas, converted them to mask and RLE format, but once uploaded to CVAT I can not move whole ellipse or resize it. 

### Describe the solution you'd like

Save full ellipse functionality while importing json.

**Comment by bsekachev** [comment]
- Masks can still be dragged, and edited. But can't be resized. 
- Ellipses can be dragged/resized. Why do you convert them to masks if you want to work with them as with ellipses?

**Comment by alfakat** [comment]
I import my ellipses in same format I exported from CVAT in RLE format, to get it I need convert to binary mask. 
Please suggest another way/format to save my GT, upload as ellipse and use full functionality.

**Comment by bsekachev** [comment]
Export as Datumaro/CVAT formats, for example. Thus you may import them back and get ellipses. 
If you need masks for your deep learning model, you may export in both formats.

**Comment by alfakat** [comment]
No, still importing as mask. 

What I am doing wrong? For both CVAT images/Datumaro: mark iris > export > import the same file (no modified) > tried both Convert masks to polygons True and False > label type: 'Mask shape'

**Comment by bsekachev** [comment]
Please, provide full steps to reproduce.

- If on app.cvat.ai, share task id. 
- If on your own server, share a minimal task backup to reproduce.  Also, share CVAT version.

**Comment by alfakat** [comment]
Task #683626 
Currently, I've imported the exported json.

You can try on you side: 
- annotate image with ellipse type;
- save and export as one of format you suggested;
- import again. 
For me it imported as 'Mask shape'.

**Comment by bsekachev** [comment]
In the provided task you already have masks (_precisely speaking, you had, because I rewritten them when tried to reproduce_) drawn and saved in CVAT database. 
In general, masks can not be converted to ellipses. 

Annotate ellipses, export in CVAT/Datumaro, import, you should get ellipses.

**Comment by bsekachev** [comment]
CVAT and Datumaro export ellipses as ellipses, not as RLE.

**Comment by alfakat** [comment]
Appreciate your help!
