### ISSUE TITLE
Issue annotation creating tasks from mp4 files

### ISSUE THREAD

**Issue by camkisailus** [cvat-ai/cvat#7936]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Navigate to a project and select "Create multi tasks"
2. Upload mp4 files 
3. In advance config section, set segment size to 100 and frame step to 5. I want every 5th frame and 100 frames per job. Leave all other values as default (i.e. empty).

### Expected Behavior

I have an mp4 that I expect to have 600 frames after taking every 5th frame. When CVAT creates the task, there are 7 jobs created and the first 6 jobs have 100 frames and the last has 30 frames. That gives me a total of 630 frames, even though the frame range goes from 0-599. I am confused about where the additional 30 frames are coming from?

![image](https://github.com/cvat-ai/cvat/assets/47364146/40c1f1b2-8aa0-4465-a879-b549a2963ee7)

### Environment

```Markdown
- Hosting cvat locally using version 2.5.2
```

**Comment by bsekachev** [comment]
Try to specify overlap == 0. 
As far as I remember default overlap for videos is 5. 
For images is 0.

**Comment by camkisailus** [comment]
Ah yes, that seemed to fix it. It would be nice if the default values were populated or at least specified in the documentation. Thanks!

**Comment by camkisailus** [comment]
@bsekachev Do you know if it's possible to retroactively adjust the Tasks to have overlap = 0. Or will I have to create a new project?
