### ISSUE TITLE
SAM doesn't work

### ISSUE THREAD

**Issue by cile98** [cvat-ai/cvat#7940]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

When I try to use SAM I get the next error message: `Interaction error occurred
500 Server Error: Internal Server Error for url: http://nuclio-dashboard.internal.cvat.ai:8070/api/function_invocations` after reloading the page it disappears from the list of available models and appears only once reloaded again

**Comment by bsekachev** [comment]
We are upgrading SAM till the newest version, there may be some outages within an hour.
