### ISSUE TITLE
Some issues with UI

### ISSUE THREAD

**Issue by KTXKIKI** [cvat-ai/cvat#7946]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

![屏幕截图_26-5-2024_195924_192 168 0 2](https://github.com/cvat-ai/cvat/assets/135221549/4f547442-9e21-4e49-81ca-f92549b980d4)
Button occlusion at the bottom of the page

**Comment by bsekachev** [comment]
Hello, 

What is your screen resolution? 
Did you enabled any scaling (system wide or in the browser)?

**Comment by KTXKIKI** [comment]
Yes, I can adjust the screen zoom to solve the problem

**Comment by bsekachev** [comment]
I mean what is the screen resolution / scale necessary to reproduce the problem?

**Comment by KTXKIKI** [comment]
Oh,Oh， I misunderstood   
I haven't enabled any extensions
![image](https://github.com/cvat-ai/cvat/assets/135221549/0e09ca72-5a8d-48b0-a917-f9910d019b8d)
and
Zoom webpage to 90%
