### ISSUE TITLE
Custom img model and metadata (UI) with serveless

### ISSUE THREAD

**Issue by davy-blavette** [cvat-ai/cvat#7961]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I couldn't find anything in the serveless documentation to customize this image or metadata.
```
  annotations:
    name: P0005 Baguette Scarring
    type: detector 
```

![image](https://github.com/cvat-ai/cvat/assets/3437490/02e24d5c-7091-4cad-a766-1d4ad4f478bc)

The same goes for this topic, I don't know how to choose the documentation label. 
![image](https://github.com/cvat-ai/cvat/assets/3437490/d0be337d-9a3c-446e-b0f5-7fcdf8791c40)

### Describe the solution you'd like

I'd like to be able to enrich the metadata, description, date, algorithm, image, for example.

![image](https://github.com/cvat-ai/cvat/assets/3437490/3527f01f-a5e3-4763-8441-e65cb07d7e35)

**Comment by bsekachev** [comment]
Hello,

> customize this image

No way here. 

> or metadata.

What metadata? All things are configured in corresponding .yml files for the function, e.g. serverless/pytorch/mmpose/hrnet32/nuclio/function.yaml

**Comment by davy-blavette** [comment]
Ok, that was easier than I thought:
${model.version}
${model.description}
etc...depending on what's in function.yaml.
It works. And if I want to add more, I go to the MLModel...class.
