### ISSUE TITLE
Very high consumption of storage for cvat_cvat_cache_db

### ISSUE THREAD

**Issue by subhamagrawal1** [cvat-ai/cvat#7968]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

When running cvat on a self-hosted format on ec2 instance with 32gb ram and 250gb storage, the docker logs of cvat_server show high usage of disk > 90.9% and keeps crashing the server, the screenshot below shows the error on docker logs.
![Screenshot from 2024-05-30 14-43-28](https://github.com/cvat-ai/cvat/assets/149759205/879d0bfa-35bb-4a10-9003-b5aad36ea682)

The below shows my df - h output for storage size
![Screenshot from 2024-05-30 14-43-40](https://github.com/cvat-ai/cvat/assets/149759205/8f3d7bd1-f9b9-4c25-ad5a-680920f52436)

Docker stats screenshot
![Screenshot from 2024-05-30 14-47-00](https://github.com/cvat-ai/cvat/assets/149759205/a77dd0dd-7fc5-4675-a567-ec75c64ad6b6)

On stopping the containers around 15gb of storage gets freed
![Screenshot from 2024-05-30 14-47-49](https://github.com/cvat-ai/cvat/assets/149759205/79fdd25b-2539-4bee-9785-6ea27e1921ef)

On deleting the cache db around 35Gb of storage gets free
![Screenshot from 2024-05-30 14-48-21](https://github.com/cvat-ai/cvat/assets/149759205/55d00386-c676-437a-8077-8ef07caf8ed0)

After starting the containers back up, the storage is at good levels, on using the app for 1 - 2 days and doing anntotaions same issue repeats
![Screenshot from 2024-05-30 14-49-05](https://github.com/cvat-ai/cvat/assets/149759205/c2700e0d-590a-4abb-8103-383dbdbbb52a)

### Expected Behavior

The containers don't crash at 90.9% warning and notify of storage issue, cache_db should not consume for e.g more than 20Gb of storage. 

### Environment

```Markdown
- cvat_version: v2.14.0
- docker version: 20.10.22
- environment : AWS t3.2xlarge
- Linux: Ubuntu 18.04
```

**Comment by bsekachev** [comment]
> The containers don't crash at 90.9% warning and notify of storage issue

If you accidentally get 100% disk space usage, you may have big problems with the instance.
So, just warning will not work. You may disable this check if you believe it is not necessary for you. Please, refer to: https://github.com/cvat-ai/cvat/pull/7180 

> cache_db should not consume for e.g more than 20Gb of storage.

I agree, that size has to be limited somehow, but it should be configurable. Now keys are from this database are removed after 24 hours. You may try to decrease the value.

**Comment by subhamagrawal1** [comment]
@bsekachev agree on the warning and that it is necessary, i would definitely retain the warning to avoid big problems. 
Regarding cache db settings, could you guide me on how to decrease the time value for the keys? 
Thanks a ton for the quick response!

**Comment by bsekachev** [comment]
https://github.com/cvat-ai/cvat/blob/483502ad44295047d2ac5ee3ae910d577d7bb8a4/cvat/settings/base.py#L543

**Comment by subhamagrawal1** [comment]
@bsekachev after making the required changes, what steps do i need to take to build and deploy it back? And what are the data that is stored in cache, does it affect annotations in any way?

**Comment by bsekachev** [comment]
> does it affect annotations in any way

Not, it is only temporary cache to store ready chunks with images.

`docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

**Comment by subhamagrawal1** [comment]
@bsekachev I made the changes and when trying to build get the error shown below. Could you please guide me on next steps?

![Screenshot from 2024-05-31 09-39-31](https://github.com/cvat-ai/cvat/assets/149759205/9678d7fd-4e1a-46d9-80ce-3f568b0cc0ce)

**Comment by subhamagrawal1** [comment]
@bsekachev could you please guide me on the next steps.

**Comment by azhavoro** [comment]
@bsekachev please use a latest docker and docker compose plugin instead of docker-compose v1

**Comment by bsekachev** [comment]
@subhamagrawal1 FYI
