### ISSUE TITLE
No logs in Analytics when using keyboard shortcuts

### ISSUE THREAD

**Issue by thmegy** [cvat-ai/cvat#7988]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Annotate an object using AI-tool (SAM), using the mouse for all steps (start annotation, finish annotation, save)
2. Annotate another object using AI-tool, using keyboard shortcuts to start (`N`) and finish (`N`) annotation, and to save (`Ctrl-s`)
3. Check corresponding logs in Analytics > Dashboards > All events
![Capture d’écran du 2024-06-05 13-50-55](https://github.com/cvat-ai/cvat/assets/14315003/4bb52a0a-1f70-4f03-befd-e2ac2be10226)
As can be seen, keyboard shortcuts are not recorded in the logs...

### Expected Behavior

Equivalent of `click:element` event for keyboard shortcuts.

### Context

I'm trying to keep track of the working_time for some subsets of actions (e.g. for use of AI-tools, of brush tool), so I need a log event indicating when each tool is used.

**Comment by bsekachev** [comment]
That is true that we do not store pressed shortcuts. 
But why do you consider it as a bug?

**Comment by thmegy** [comment]
I find it confusing to have different behaviours when using shortcuts and when using the mouse, while the same actions are being made.

For instance, I thought I could keep track of the time spent using AI-tools by finding `click:element` events with `obj_val=Interact`. But this is not true if the annotator uses the shortcut to open the tool.

But okay, if this is on purpose, I will try to think of another approach.

**Comment by bsekachev** [comment]
I think logging shortcuts will not useful in your case as we are going to add shortcuts customization soon and knowing that user clicks shortcut `N` will not give you understanding that user created shape with AI tools. 

Actually, even now it will not work as this shortcut is for drawing any shape (manually, or by interactor, or by detector). 

In your case event `object:drawn` will be useful, with extra information in payload (e.g. this object has been created using specific detector or interactor). 

You are welcome to contribute the feature.

**Comment by thmegy** [comment]
Okay, thanks for the explanation.
I will close the issue then.
