### ISSUE TITLE
Down CVAT don't down docker serveless (function image)

### ISSUE THREAD

**Issue by davy-blavette** [cvat-ai/cvat#7990]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

Hello!

Nuclio serveless docker images quickly take up a lot of space and can cause out-of-memory situations, for example if you're also training on the same machine. So you need to remember to manually put Nuclio models on standby:

![image](https://github.com/cvat-ai/cvat/assets/3437490/12122662-de4a-42ce-8086-3c1aadb7ab09)

which is not done automatically if you do a simple :

docker compose -f docker-compose.yml -f docker-compose.override.yml -f components/serverless/docker-compose.serverless.yml down

![image](https://github.com/cvat-ai/cvat/assets/3437490/958f7aa8-202f-46fd-bda6-79891f5a34c8)

`docker ps
`
![image](https://github.com/cvat-ai/cvat/assets/3437490/5b8dc15c-a3b1-4807-82ca-d5f7b51dd137)

...the less patient (like me) end up doing a kill and we end up with the communication error message: “HTTPConnectionPool(host=‘host.docker.internal’, port=32783): Max retries exceeded with url: / (Caused by NewConnectionError(‘<urllib3.connection.HTTPConnection object at 0x7f3730196d30>: Failed to establish a new connection: [Errno 111] Connection refused’))”

It's virtually impossible to correct except by reinstalling the function, but you need to know this because nuclio copies a pseudo image during a mount and the error remains present (with nothing in the logs).

### Describe the solution you'd like

The ideal solution, if possible, would be to down CVAT and therefore nuclio to standby before hand, so as to free up memory.

**Comment by bsekachev** [comment]
`docker compose` is not related somehow to nuclio.
Please, use `nuctl` tool to handle serverless functions. 

```
Nuclio command-line interface

Usage:
  nuctl [command]

Available Commands:
  build       Build a function
  create      Create resources
  delete      Delete resources
  deploy      Build and deploy a function, or deploy from an existing image
  export      Export functions or projects
  get         Display resource information
  help        Help about any command
  import      Import functions or projects
  invoke      Invoke a function
  update      Update resources
  version     Display the version number of the nuctl CLI
```

**Comment by Abdul-Mukit** [comment]
@bsekachev can you give an example of how to use the `nuctl` to handle the serverless function?
