### ISSUE TITLE
When we look at the CVAT task, we see that the order of the labels is different from the one we created.

### ISSUE THREAD

**Issue by youth123-c** [cvat-ai/cvat#7991]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Figure 1 shows the label order I set when I created the task, and Figure 2 shows the label order I saw when I opened the task. They are inconsistent
![1](https://github.com/cvat-ai/cvat/assets/152575079/a0baf25b-8996-4596-ab63-484ce372fcdb)
![2](https://github.com/cvat-ai/cvat/assets/152575079/bb1951b4-4277-40cc-9987-664445c75b7f)

### Expected Behavior

The order of tags you see when annotating is not the order of tags you create.

### Context

I want the labels to be in the same order as when I created the task.

### Environment

```Markdown
CVAT V2.1.0
```

**Comment by bsekachev** [comment]
Duplicate #7370
