### ISSUE TITLE
Total duration of zoom, change attributes and resize events

### ISSUE THREAD

**Issue by mmoyano-sigmacognition** [cvat-ai/cvat#7994]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I'm working with CVAT 2.14.0, I've labeled some images using zoom, changing attributes and resizing some polygons. When I checked the events in analytics, I saw that the duration column of those events was set to 0. I can get an approximation with the ```working_time``` field in the payload, but the time of those events may be distorted if I don't label in less than [100 seconds](https://docs.cvat.ai/docs/administration/advanced/analytics/#working-time-calculation), as the difference between timestamps is computed and not the duration itself. In the case of not labeling for more than 100 seconds, the ```working_time``` is also set to 0.

![excel1](https://github.com/cvat-ai/cvat/assets/171227840/0f70457a-1ee8-4b64-b7b9-4e1a3e2a3e88)
![excel2](https://github.com/cvat-ai/cvat/assets/171227840/f1f1889e-9244-4c07-90d1-66b7343bcfe8)

Are both behavours expected to be this way? Otherwise, is it planned to be fixed in next releases?

Thanks in advance. Cheers,
Manuel

**Comment by bsekachev** [comment]
I recently documented how working time calculated, please read here: https://docs.cvat.ai/docs/administration/advanced/analytics/#working-time-calculation

Briefly speaking, duration of zoom and resize are not considered at all. 

The only difference is that in v2.14.0 working_time appended to the following event payload.
Starting from v2.14.1 we have a dedicated event to store working time.

**Comment by mmoyano-sigmacognition** [comment]
Hi @bsekachev,

Thanks for the quick response. Would it make sense to include the duration of such events in next releases?

**Comment by bsekachev** [comment]
Yep, it makes sense, but that is not a priority. 
Anybody is welcome to contribute :)
