### ISSUE TITLE
Lost Annotations

### ISSUE THREAD

**Issue by jmarshh** [cvat-ai/cvat#7996]
I was working on annotations for three days and had annotated around 700 frames. I saved my progress throughout, but today all of my annotations were lost. Is there any way to recover these annotated frames? (username: jm5679, Job #709547)

**Comment by bsekachev** [comment]
Hello,

Probably you mean **task** with ID 709547, as the specified user never worked on **job** with this ID.

I see there were annotations activitiy starting from beginning of June. 
But last time you saved this job was on 2024-05-31 17:17:52.605 (UTC)

So, you just did not save any of your annotations on the server.
There is no way from our side to restore it somehow.

Please, enable auto-save in settings if you need that, or save manually when necessary.
