### ISSUE TITLE
How does CVAT display images on GUI?

### ISSUE THREAD

**Issue by natanaels12** [cvat-ai/cvat#7998]
I want to ask about how CVAT displays the images on GUI, particularly from connected file share. 

The reason I ask is because I created a task from connected file share, and when I unmounted the connected file share, the Image can still be displayed on the GUI, but does not work with automatic annotation.

**Comment by bsekachev** [comment]
- CVAT has cache on the server, expiring in 24 hours by default. 
- app.cvat.ai has one more level of caching in the browser (using IndexedDB)
