### ISSUE TITLE
Server run out of disk space when cloud storage is used.

### ISSUE THREAD

**Issue by Tom1204** [cvat-ai/cvat#8009]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Deploy CVAT with docker
2. Create project and attach cloud storage
3. Create task from cloud storage images(where image quality is maximum 70%)

Disk space 300GB

### Expected Behavior

Now I am facing issue where CVAT is crashing due to health check for disk space > 90%. So, when I create task it download original images and use them for annotations. When I have look for directories I have seen that it saves original and compressed images. 
<img width="213" alt="image" src="https://github.com/cvat-ai/cvat/assets/17402086/938eacfa-a817-4445-947f-84578ee509c3">
<img width="249" alt="image" src="https://github.com/cvat-ai/cvat/assets/17402086/ce60fd91-d635-4c86-998c-ab26e56856c7">
I have around 1TB data on cloud. So, I can't create task for rest of them. Or even use it.

### Possible Solution

It should clean images when disk space runs out or after compressing. Or after defined period it should clean downloaded cloud images.

### Context

<img width="331" alt="image" src="https://github.com/cvat-ai/cvat/assets/17402086/9c3708d0-452b-44ee-9695-35a164d75324">
<img width="1234" alt="image" src="https://github.com/cvat-ai/cvat/assets/17402086/7e4f17a2-6f19-4687-9e36-6fcacc9dd4b7">
<img width="562" alt="image" src="https://github.com/cvat-ai/cvat/assets/17402086/cffdc5de-ecbb-4e07-9c65-75b2cfd517c7">

**Comment by bsekachev** [comment]
Hello, 
Please, try to reproduce the problem in the latest version of CVAT before submitting the issue.

**Comment by Tom1204** [comment]
I have updated to 2.14.3, however it did not cleaned disk. CVAT did not launch. I have cleaned it by myself. I wanted to ask have you thought about automatic cleaning disk, if it  is using cloud? 

What should I do if I have TB data in cloud, but have 300GB in server which is installed CVAT? What is best practice for such situation? @bsekachev

**Comment by bsekachev** [comment]
1. If you create tasks from a cloud storage with enabled "Use cache" option, it will not copy all the data from the cloud storage to local disk. 
2. But when you request frames from the browser, it creates data chunks in cache. Default lifetime of this cache is 24 hours. This cache is stored on the local disk. 
3. Upgrading CVAT will not remove something automatically.
