### ISSUE TITLE
When default rotation is 0，can't exec update

### ISSUE THREAD

**Issue by kkju** [cvat-ai/cvat#8013]
https://github.com/cvat-ai/cvat/blob/d7cbf8c9ed31cb307b100d65ff7dd783fc29d3b4/cvat-canvas/src/typescript/canvasView.ts#L2067

when the state.rotation === 0，shape.rotate can not exec。
for example:
   1、draw a rectangle，rotate it;
   2、undo the action；
   3、the rectangle can't undo to default。

**Comment by bsekachev** [comment]
Hello, thanks for the report.
Try to do `undo` twice as a temporary workaround

**Comment by KrishavRajSingh** [comment]
> Hello, thanks for the report. Try to do `undo` twice as a temporary workaround

I would like to work on this.
