### ISSUE TITLE
How to update nginx.conf

### ISSUE THREAD

**Issue by patcharees** [cvat-ai/cvat#8023]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I got an error _504 Gateway Time-out_ from ai tools. I tried to update timeout in nginx.conf, but my changes was not used in the cvat_server container.

1. Edit cvat/cvat/nginx.conf
2. Restart all container
`docker compose -f cvat/docker-compose.yml -f cvat/components/serverless/docker-compose.serverless.yml up -d --force-recreate`
3. Check the nginx.conf in the cvat_server container. Still the same before editing
`docker exec -it cvat_server cat etc/nginx/nginx.conf`

### Expected Behavior

nginx.conf should be updated

### Environment

```Markdown
- Git hash commit 
Date:   Wed Jun 12 08:56:18 2024 +0300
Fixed: Cannot read properties of null (reading 'draw') (#7997)
```

**Comment by azhavoro** [comment]
you have to rebuild backend image after change: https://github.com/cvat-ai/cvat/blob/v2.14.3/Dockerfile#L186
`docker compose -f cvat/docker-compose.yml -f docker-compose.dev.yml build`
