### ISSUE TITLE
AI tools won't appear on Windows 10

### ISSUE THREAD

**Issue by XenMil** [cvat-ai/cvat#8050]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

I've followed the instructions for installing CVAT on a Windows 10 machine ([https://docs.cvat.ai/docs/administration/basics/installation/]) and all works great, except the AI tools for segmentation which don't appear on the GUI. Following the instructions in the same page on a Mac makes the AI tools visible. Why is that? Perhaps there are other instructions elsewhere for that?
Thanks

### Environment

```Markdown
Windows 10 Business 22H2
Docker 4.26.1 (131620)
CVAT Server version: 2.15.0
  Core version: 15.0.6
  Canvas version: 2.20.3
  UI version: 1.63.11
```

**Comment by azhavoro** [comment]
Please follow this https://docs.cvat.ai/docs/administration/advanced/installation_automatic_annotation/.
The guide you mentioned does not have steps to deploy nuclio fucntions
