### ISSUE TITLE
Last updated filter field does not work for tasks/projects/jobs

### ISSUE THREAD

**Issue by bsekachev** [cvat-ai/cvat#8054]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

![error](https://github.com/cvat-ai/cvat/assets/40690378/c2a39ce7-4fff-48b5-8937-f75a861ccb89)

Related #https://github.com/ukrbublik/react-awesome-query-builder/issues/1033

### Environment

```Markdown
release v2.14.3
```

**Comment by cile98** [comment]
@bsekachev also noticed that filtering in tasks doesn't work as expected. When I filter by `Label` the only thing that happens is that the `Label` disappears, but the image is still shown 
![image](https://github.com/cvat-ai/cvat/assets/23198302/f68870ba-812e-4de5-834e-ddea3be432af)
![image](https://github.com/cvat-ai/cvat/assets/23198302/ff4ee477-0bb0-440f-b35b-cbd977fe0bcd)
![image](https://github.com/cvat-ai/cvat/assets/23198302/d561b639-dda7-4d83-9dfd-960eaec09b6a)

**Comment by bsekachev** [comment]
@cile98 

That is expected behavior.
This is annotations filters, not frames filter.

**Comment by cile98** [comment]
> @cile98
> 
> That is expected behavior. They are annotations filters, not frames filters.

I see. Is there a way to filter frames?

**Comment by bsekachev** [comment]
@cile98 

Perhaps you want to use filtered frames navigation to visit only frames with objects, corresponding to specific filters
Right click navigation button

![image](https://github.com/cvat-ai/cvat/assets/40690378/f895e8d8-10c1-4ae0-b43e-7ec63698f5df)

**Comment by cile98** [comment]
@bsekachev that's great thanks! Couldn't find this in the docs actually https://docs.cvat.ai/docs/manual/advanced/filter/

**Comment by bsekachev** [comment]
@mdacoca 

Let's add a piece of documentation

**Comment by bsekachev** [comment]
The issue closed by #8055
