### ISSUE TITLE
Can't Move Projects Between Workspaces

### ISSUE THREAD

**Issue by JoaoCioffi** [cvat-ai/cvat#8066]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I've created a personal project but it was supposed to be inside my organization workspace.
Now I can't move it to that workspace (my personal account is free and my workspace has a paid plan, wich is required for exporting annotated images.

**Comment by bsekachev** [comment]
Duplicate #4202
