### ISSUE TITLE
Could not restore project backup

### ISSUE THREAD

**Issue by kailash-delvify** [cvat-ai/cvat#8078]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Dear team I am trying to upload a backup from another server while doing so i am getting file size exceeds the max limit of 25GBPlease help, as I have annotated videos for the last 4 to 5 months and it is not working.Please help me solve this problem. It requires me to be ready to pay for support.

**Comment by kailash-delvify** [comment]
I also tried to upload an individual task, but I'm getting an error saying "task.json not found."

**Comment by kailash-delvify** [comment]
task folder structure is:
.
    ├── data
    │   └── {user uploaded data}
    ├── task.json
    └── annotations.json

**Comment by bsekachev** [comment]
Original issue #8073
