### ISSUE TITLE
task.json not found error while uploading backup task

### ISSUE THREAD

**Issue by kailash-delvify** [cvat-ai/cvat#8079]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I am having trouble restoring a project backup as I'm encountering a media data entry error. 

When attempting to restore individual tasks, I am also getting a "task.json not found" error, even though the file is present in the folder structure. Here's the layout:
    ├── data
    │   └── {user uploaded data}
    ├── task.json
    └── annotations.json

**Comment by bsekachev** [comment]
Original issue #8073
