### ISSUE TITLE
can't access property "length", e is undefined

### ISSUE THREAD

**Issue by VeyDlin** [cvat-ai/cvat#8086]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

I am trying to create a clothing segmentation module based on U2NET. It works well, but it seems that the frontend is not processing the response correctly.

I used the SAM example and based my module on it - https://github.com/VeyDlin/cvat-clothing-segmentation.

However, I continue to receive an error when trying to create the mask.

Interaction error occurred
can't access property "length", e is undefined

**Comment by bsekachev** [comment]
Unfortunately we can't help with issues in custom code

**Comment by VeyDlin** [comment]
The api documentation would be enough for me, what is expected from the function?

**Comment by bsekachev** [comment]
In case with SAM nuclio only encodes server and returns binary blob with image embeddings. 
These embeddings with user input (mask clicks) are decoded on client using onnx javascript module. You may find decoder code here: cvat-ui/plugins/sam.

In case with other interactors, client expects the following structure: 

```
export interface InteractorResults {
    mask: number[][];
    points?: [number, number][];
    bounds?: [number, number, number, number]
}
```
