### ISSUE TITLE
How to change the location where uploaded images are saved

### ISSUE THREAD

**Issue by Songpenglei123** [cvat-ai/cvat#8092]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

![屏幕截图 2024-06-27 111303](https://github.com/cvat-ai/cvat/assets/46895437/67f6dc33-caa7-4c20-853f-033403f89fe2)
When I modified all the cvat_data, it didn't work

**Comment by azhavoro** [comment]
Please provide any details, it's not clear what you want to do
