### ISSUE TITLE
Access Error: 404 -- Not Found

### ISSUE THREAD

**Issue by ultranationalism** [cvat-ai/cvat#8094]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

root@DESKTOP:~/cvat# docker-compose up -d
![image](https://github.com/cvat-ai/cvat/assets/69612673/a2921104-83a1-418f-941d-bca90f424b19)

### Expected Behavior

Successfully accessed

### Context

![image](https://github.com/cvat-ai/cvat/assets/69612673/38e19836-3dd5-4cd4-ad89-4ccc67e4ec78)
![image](https://github.com/cvat-ai/cvat/assets/69612673/c2124747-e0bb-439d-8393-0adf6106541c)
I cannot find 8080 port
![image](https://github.com/cvat-ai/cvat/assets/69612673/f2e1f94e-a565-45b5-ae60-5597e59c93ca)

### Environment

```Markdown
-wsl2 windows11
```

**Comment by bsekachev** [comment]
Just deployed cvat on `wsl2` using `docker compose up -d`, so, steps to reproduce do not work.
Or you have some specific in your environment.

**Comment by ultranationalism** [comment]
> Just deployed cvat on `wsl2` using `docker compose up -d`, so, steps to reproduce do not work. Or you have some specific in your environment.
> 
> ```
>  sudo lsof -i :8080
> 
> COMMAND    PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
> docker-pr 3864 root    4u  IPv4 13837685      0t0  TCP *:http-alt (LISTEN)
> docker-pr 3872 root    4u  IPv6 13840456      0t0  TCP *:http-alt (LISTEN)
> ```

`Error: ✗ failed to download plugin archive: Get "https://github.com/grafana/clickhouse-datasource/releases/download/v4.0.8/grafana-clickhouse-datasource-4.0.8.linux_amd64.zip": EOF
`
well，I found error

**Comment by ultranationalism** [comment]
> Just deployed cvat on `wsl2` using `docker compose up -d`, so, steps to reproduce do not work. Or you have some specific in your environment.
> 
> ```
>  sudo lsof -i :8080
> 
> COMMAND    PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
> docker-pr 3864 root    4u  IPv4 13837685      0t0  TCP *:http-alt (LISTEN)
> docker-pr 3872 root    4u  IPv6 13840456      0t0  TCP *:http-alt (LISTEN)
> ```

I finally solved this problem, and the download failure was not the cause of my problem. Even if the download was successful, it still did not solve the problem. The real reason is that I enabled the mirror network mode of WSL, which prevented it from opening port 8080 properly.

**Comment by bsekachev** [comment]
Nice to hear that
