### ISSUE TITLE
wrong bbox height and width values on coco kp export for single keypoints

### ISSUE THREAD

**Issue by CourchesneA** [cvat-ai/cvat#8098]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a project
2. Setup a skeleton with 1 keypoint
3. Annotate one image with any amount of objects
4. Export to COCO keypoints 1.0

### Expected Behavior

The annotation file should contain bbox information computed from the keypoints. I.e.:
```
{"id":10,"image_id":1,"category_id":21,"segmentation":[],"area":0.0,"bbox":[1279.65,185.18,111.53,112.85],"iscrowd":0,"attributes":{"occluded":false,"keyframe":false},"keypoints":[1279.65,185.18,2],"num_keypoints":1}
```
What I get is `0.0,0.0` for bbox width and height

### Context

On CVAT, a bbox is properly displayed around the keypoint. I would expect it to be exported as well, as it is the case when num_keypoints > 1

### Environment

```Markdown
- cvat cloud
```

**Comment by bsekachev** [comment]
Please, refer to my answer in existing issue #6158

**Comment by bsekachev** [comment]
A point itself is infinitely small  object, it does not have width and height. So, everything is correct in your case.
