### ISSUE TITLE
Import Images with annotations

### ISSUE THREAD

**Issue by marco0913** [cvat-ai/cvat#8104]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I labelled some images on cvat and exported the dataset in YOLO 1.1. So now that I have the images and the .txt annotations, how can I upload the labelled image back?

**Comment by bsekachev** [comment]
Please, try to refer to documentation first.
