### ISSUE TITLE
Created CVAT ID's but did not received any confirmation email

### ISSUE THREAD

**Issue by Sandesh-Rprocess** [cvat-ai/cvat#8114]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Expected Behavior

Greetings,

I Created multiple Cvat account for my teammates but they did not receive the verification email. For this reason, team cannot log in to their respective account and use Cvat online. Can you please send again the email. Besides, I tried to recover the passwords, but the system do not let me because my email is not verified. Please can you help me.

Best regards,
Sandesh Pavan

**Comment by zhiltsov-max** [comment]
Hi, please write to the Contact us form on the https://cvat.ai site for further discussion. 
https://youtrack.cvat.ai/form/447d9c98-ab4b-466e-bf9d-004f01b22f73
