### ISSUE TITLE
Cannot export Datumaro 1.0

### ISSUE THREAD

**Issue by ChristianIngwersen** [cvat-ai/cvat#8115]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

From the web UI, i.e. app.cvat.ai, export either a project, task or job to the Datumaro format.

### Expected Behavior

Functional export

### Context

When trying to export from the web GUI to the Datumaro format I get a NotImplementedError.

It works fine exporting to CVAT for video, but would prefer the json format from Datumaro. The project contains videos with 1 bbox and 2 skeleton annotations.
![image](https://github.com/cvat-ai/cvat/assets/16038219/232095cd-e5f9-466a-ba98-484d3fbe6183)

### Environment

```Markdown
Web app through app.cvat.ai
```

**Comment by zhiltsov-max** [comment]
Hi, skeletons are not supported in the Datumaro format yet. Consider using COCO Person Keypoints instead if you want a json output, it's more or less similar.

**Comment by ChristianIngwersen** [comment]
> Hi, skeletons are not supported in the Datumaro format yet. Consider using COCO Person Keypoints instead if you want a json output, it's more or less similar.

Hi @zhiltsov-max thanks for the answer. The "issue" is that I have both skeleton and bbox annotations. I guess COCO Keypoints wont work then?

**Comment by zhiltsov-max** [comment]
It's not simple at the moment, but here is what is available now. Suppose you have a CVAT task with 2 labels: "skeleton" and "skeleton_bbox". There are several options:

1. Group corresponding skeletons and boxes using the "Group annotations" tool in UI, then export as COCO keypoints. You can check current groups by using the group coloring button. 
![Screenshot from 2024-07-05 13-37-10](https://github.com/cvat-ai/cvat/assets/13832349/7b50a670-a3ec-4172-83fb-eb6c59b2d83b)
![Screenshot from 2024-07-05 13-38-11](https://github.com/cvat-ai/cvat/assets/13832349/d73f1a1a-17c5-4f71-9926-909cde3d8a5a)

COCO Keypoints will include bbox information in the "bbox" field, if the boxes are grouped with skeletons. If you parse the resulting annotations with Datumaro, these boxes will be parsed as separate annotations automatically. Keep in mind that you will have no simple way to import this back together if it's needed later, so a backup may be useful.

1. You can export boxes and skeletons separately in different formats (e.g. COCO for boxes, COCO person keypoints for skeletons), then merge them using some tool (e.g. Datumaro). Note that this way Datumaro will produce bbox annotations for each skeleton parsed as well, but this bbox will be constructed just from the skeleton points, if saved without groups, so you'll need to deduplicate the boxes.

1. Export in CVAT for * format. You'll probably need to write a custom parser, but you'll have an option to import the results back.

**Comment by zhiltsov-max** [comment]
@ChristianIngwersen, now it should be possible to import both skeletons and boxes via the Datumaro format.

**Comment by ChristianIngwersen** [comment]
Thanks, great work!
