### ISSUE TITLE
Segment Anything container constantly writes to disk (constant 100% disk usage)

### ISSUE THREAD

**Issue by ranni-follower** [cvat-ai/cvat#8120]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Ran `./serverless/deploy_cpu.sh ./serverless/pytorch/facebookresearch/sam/`
2. Got `nuctl Function deploy complete`
3. SAM eating up disk usage at 100% and freezing everything.

### Expected Behavior

Segment Anything container not eating disk usage.

### Context

I'm having problem with container "nuclio-nuclio-pth-facebookresearch-sam-vit-h" (Segment Anything cpu, whose image is "cvat.pth.facebookresearch.sam.vit_h:latest"). 
Whenever it run the vmmemWSL process always took up 100% disk usage and froze everything. Stopping "nuclio-nuclio-pth-facebookresearch-sam-vit-h" could temporarily solve the high disk usage problem.

Below are some logs from this container.
[SAM_log.txt](https://github.com/user-attachments/files/16104136/SAM_log.txt)

Note that I'm not an experienced Linux/Docker user. For context I'm a Data analyst and mostly use Windows.
Let me know if you need more info.

**Comment by bsekachev** [comment]
Hello,

CVAT code (model_handler.py) does not write anything to the disk. 
If you have problems with setup self-hosted solution, you always may use online platform.
