### ISSUE TITLE
Could not export dataset

### ISSUE THREAD

**Issue by weertman** [cvat-ai/cvat#8130]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

exported dataset to COCO 1.0 format and the export fails and throws this code:

Could not export dataset for the [project 155255](https://app.cvat.ai/projects/155255)

datumaro.components.errors.ItemExportError: Failed to export item ('10__b1z1', 'default')

### Expected Behavior

The dataset should export successfully as a zip file.

**Comment by zhiltsov-max** [comment]
Discussed privately.
