### ISSUE TITLE
CVAT upgrade of a clone EC2 instances

### ISSUE THREAD

**Issue by ilya-sha** [cvat-ai/cvat#8132]
I have CVAT running on an EC2 instance with an S3 mount serving as the file system (hosting the data Docker volume).

I want to ensure a successful upgrade of CVAT from version 2.10.2 to 2.15.0. To achieve this, I have created a clone of the production CVAT EC2 instance. My plan is to upgrade the clone first. If the upgrade is successful, I will switch the clone to production and stop the current instance.

My question is:
What will happen if two CVAT instances point to the same S3 data Docker volume?

**Comment by bsekachev** [comment]
Data layout was not changed, but there will be some problems with shared database. 

Newest instance will run database migration (first causing PostgreSQL locks) and after migrations, ORM on older instance will not correspond to the upgraded database scheme. So, the older instance will not work properly.

**Comment by ilya-sha** [comment]
@bsekachev How would you suggest to make an upgrade and confirm success migration and full functionality before start using it?
Would you suggest to clone the S3 bucket as well?

**Comment by bsekachev** [comment]
Prepare [backups](https://docs.cvat.ai/docs/administration/advanced/backup_guide/) and upgrade original instance.
