### ISSUE TITLE
Uninitialized text content.

### ISSUE THREAD

**Issue by Zero2Success** [cvat-ai/cvat#8133]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

![화면 캡처 2024-07-08 171039](https://github.com/cvat-ai/cvat/assets/126643066/4436c630-76e0-4af3-b4dc-81e69df5ad7c)
this is my settings.
This is a bug when using Always show object details.

":" is included, the contents of the text preview are not initialized and are not properly reflected even if the text is cleared.

![화면 캡처 2024-07-08 171001](https://github.com/cvat-ai/cvat/assets/126643066/42f96016-cd49-4346-8f69-53869433b066)

**Comment by bsekachev** [comment]
Hello, Thanks for the report
