### ISSUE TITLE
Upload multiple mp4 files to same task

### ISSUE THREAD

**Issue by yuvalamar75** [cvat-ai/cvat#8138]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I connected CVAT to shared file storge and that works properly.
When I tried to upload a folder with several mp4 file I got this error.
![image](https://github.com/cvat-ai/cvat/assets/44939281/1c183ee7-facc-454d-8f17-1053df38d989)
I read that another issues that posted in 2020 and 2021 and 2022 that asked about that and you said that it will be implemented in next versions.

### Describe the solution you'd like

when upload folder with multiple videos it will works . 

### Additional context

There is a way to create new task that contains multiple mp4 files ??

**Comment by bsekachev** [comment]
> I read that another issues that posted in 2020 and 2021 and 2022 that asked about that and you said that it will be implemented in next versions.

I do not think that is true. That is againist core concepts. One task can not contain more than one videofile.
