### ISSUE TITLE
Exported environment variables are not seen by docker-compose.external_db.yml

### ISSUE THREAD

**Issue by IoanaCristescu15** [cvat-ai/cvat#8140]
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Go to https://github.com/cvat-ai/cvat/blob/develop/docker-compose.external_db.yml for source code
2. Go to https://docs.cvat.ai/docs/administration/basics/installation/#deploy-cvat-with-an-external-database to see the steps I follow

### Expected Behavior

docker-compose.external_db.yml should be able to see exported environment variables

### Context

I want to deploy CVAT using PostgreSQL on Amazon RDS external database. I follow the steps of exporting the environment variables and adding the docker-compose.external_db.yml file to your docker compose up command. The issue is that docker-compose.external_db.yml is not able to access the environment variables and I get an error saying that the variables are set to empty strings.

### Environment

```Markdown
- CVAT is ran on an EC2 instance with 20.04.1-Ubuntu OS
- Docker 27.0.3
```

**Comment by azhavoro** [comment]
Please provide exact steps to reproduce

**Comment by IoanaCristescu15** [comment]
1. Setting up an EC2 instance where I clone the CVAT source code
2. Setting up an Amazon RDS instance using PostgreSQL
3. Defining environment variables with database connection settings in the EC2 instance CLI
`export CVAT_POSTGRES_HOST=<PostgreSQL hostname> 
export CVAT_POSTGRES_PORT=<PostgreSQL port> 
export CVAT_POSTGRES_DBNAME=<PostgreSQL database name>
export CVAT_POSTGRES_USER=<PostgreSQL role name>
export CVAT_POSTGRES_PASSWORD=<PostgreSQL role password> `
4. Running this command to bring containers up with connection to external database and SAM: `sudo docker compose -f docker-compose.yml -f docker-compose.external_db.yml -f components/serverless/docker-compose.serverless.yml up -d --build && cd ./serverless && sudo ./deploy_gpu.sh pytorch/facebookresearch/sam/nuclio/`

**Comment by azhavoro** [comment]
You need to use sudo with -E option

-E, --preserve-env
               Indicates to the security policy that the user wishes to preserve their existing environment variables.  The security policy may return an error if the user does not  have permission to preserve the environment.

**Comment by marmal88** [comment]
I have a similar issue. but from time to time I do face a permission error 13 Permission denied error accessing '/runs/secrets/postgres_password'
