### ISSUE TITLE
I want to know where the annotation information is.

### ISSUE THREAD

**Issue by bolero2** [cvat-ai/cvat#8141]
Where is annotation information? 
I have to get annotation info to make log system.

1. I saw `cvat_server` docker container, but there are uploaded images, not annotations.
2. and I got some logs from `cvat_db`, and I know that it contains postgreSQL framework.
3. I checked `/var/lib/postgresql/data` in `cvat_db` container, but I couldn't find annotation format file.

**Comment by zhiltsov-max** [comment]
Hi. If you're asking about DB layout, the annotations should be stored in `engine_labeledshape`, `engine_labeledtrack`, `engine_labeledimage`, `engine_trackedshape` tables.
