### ISSUE TITLE
Add: watermark logo

### ISSUE THREAD

**Issue by monkeycc** [cvat-ai/cvat#8143]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

Suggestion for adding features: watermark logo

Need to make the website public for other users to annotate
To prevent users from taking screenshots,
Hope to add watermark function

**Comment by Virajjai** [comment]
Hello, @monkeycc can i work on this.

**Comment by bsekachev** [comment]
The request is too custom request to be in community version.
