### ISSUE TITLE
I want a group I created to be able to see a list of tasks for a specific project.

### ISSUE THREAD

**Issue by yaeji98** [cvat-ai/cvat#8145]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

![image](https://github.com/cvat-ai/cvat/assets/65532694/c399f2cd-e4d8-4a58-b238-3c09ca443cca)

The documentation says that global roles can be adjusted only on self-hosted solution, how can I make the task list in a specific project visible to the group I created?
Currently self-hosted solution.

thank you!

**Comment by bsekachev** [comment]
Hello,

You may modify corresponding rego files. E.g. for tasks: cvat/apps/engine/rules/tasks.rego
