### ISSUE TITLE
Stuck on "open an issue" tool when switching from "Review" to "Standard" mode

### ISSUE THREAD

**Issue by thmegy** [cvat-ai/cvat#8147]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Open an annotation job
2. Switch to "review" mode
3. Create an issue using the "Open an issue" tool
4. Switch back to "standard" mode
5. Click on the image : the "open an issue" tool is still active...

I attach a video showing an example of this beahviour.
[Capture vidéo du 10-07-2024 17:18:39.webm](https://github.com/cvat-ai/cvat/assets/14315003/72979ac4-4da1-4ea1-a1cc-118613121084)

### Expected Behavior

The "open an issue" tool should be switched off as soon as we have finished creating an issue.

### Environment

```Markdown
Server version: 2.15.0
Core version: 15.0.5
Canvas version: 2.20.2
UI version: 1.63.11
```

**Comment by bsekachev** [comment]
Hello,
Thanks for the report, we will look into.
In your case, just start drawing a shape using side panel.
