### ISSUE TITLE
yolov5 algorithm automatic annotation

### ISSUE THREAD

**Issue by chang50961471** [cvat-ai/cvat#8150]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

Does the newer version not support yolov5 algorithm automatic annotation? What is the highest version supported?

**Comment by bsekachev** [comment]
Hello,

1. You may find all supported models in `serverless` directory
2. You may contribute more models, but please be sure that the license is suitable. For example Ultralytics uses [AGPL-3.0 license](https://github.com/ultralytics/yolov5#AGPL-3.0-1-ov-file), which is not.
