### ISSUE TITLE
CloudStorageWriteRequest create S3 URL and can't get override URL in private environment

### ISSUE THREAD

**Issue by AmitMalkaDAITA** [cvat-ai/cvat#8151]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

with ApiClient(configuration) as api_client:
    cloud_storage_write_request = CloudStorageWriteRequest(
        provider_type=ProviderTypeEnum("AWS_S3_BUCKET"),
        resource="test-landing-zone",
        display_name="display_name_example",
        credentials_type=CredentialsTypeEnum("KEY_SECRET_KEY_PAIR"),
        key=ACCESS_KEY_ID,
        secret_key=SECRET_ACCESS_KEY,
    )
    
    

### Expected Behavior

Create Cloud Storage with my Endpoint override URL and not get error:
HTTP response body: Connection was closed before we received a valid response from endpoint URL: "https://test-landing-zone.s3.amazonaws

### Possible Solution

Add endpoint_override_url parameter to override S3 default URL

**Comment by wedesoft** [comment]
Managed to do this using `specific_attributes="endpoint_url=http%3A%2F%2Fminio-dev%3A9000"` as keyword argument for the cloud storage write request.
