### ISSUE TITLE
Polyline shape not been exported in COCO format

### ISSUE THREAD

**Issue by paulohss** [cvat-ai/cvat#8154]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Hi!

I've got a dataset annotated using MASKS and POLYLINE shapes.

When I export it using COCO format, only the Masks are exported. 

The POLYLINE shape, that Im using only for a single category is listed as a category at the beginning of the COCO file but the annotations themselves are not generated.

This model (YOLO) works well with MASKS shapes already. What I was trying to do was to include a new label category using  POLYLINE shapes, but somehow it won't export it in the CVAT too.

Am I missing something? 

![sample_new](https://github.com/user-attachments/assets/156d6c3a-6fc0-484a-a7d1-ed63243c9d3e)
The red lines are the new category to represent "lanes".

Cheers

### Expected Behavior

Export both MASKS and POLYLINE shapes.

### Context

I've already have a model for the segmentation of intersections that works with MASKS shape annotations and I want to include a new label category using POLYLINE shapes.

**Comment by bsekachev** [comment]
COCO format does not support polylines:

https://docs.cvat.ai/docs/manual/advanced/formats/

![image](https://github.com/user-attachments/assets/7d53a95d-8702-451d-8563-a7b7aa569829)
