### ISSUE TITLE
Project and Task description is missing on their detail page (self-hosted)

### ISSUE THREAD

**Issue by ByeBug** [cvat-ai/cvat#8157]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Edit project / task description and submit.
2. Back or refresh project / task detail page.
3. Instead of displaying the submitted content, the description section only displays the `Edit` button.
4. Click `Edit` button, the submitted content is there normally.

![动画](https://github.com/user-attachments/assets/75da37f9-e16f-4e47-adfe-3f49625cf6b4)

### Expected Behavior

Description can be displayed.

### Environment

```Markdown
Self-hosted CVAT 2.15.0.

CVAT About:
Server version: 2.15.0
Core version: 15.0.7
Canvas version: 2.20.5
UI version: 1.63.12
```

**Comment by bsekachev** [comment]
Please, refer to documentation first. 
Annotation guides are rendered on job annotation view, not on task page.

**Comment by ByeBug** [comment]
> Please, refer to documentation first. Annotation guides are rendered on job annotation view, not on task page.

OK. Sorry...😂
