### ISSUE TITLE
Different SAM model not giving correct masks

### ISSUE THREAD

**Issue by realtimshady1** [cvat-ai/cvat#8158]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Download [sam_vit_b_01ec64.pth](https://drive.google.com/file/d/17cZAXBPaOABS170c9bcj9PdQsMziiBHw/view?usp=sharing)
2. Replace `decoder.onnx` in `/root/cvat/cvat-ui/plugins/sam/assets/decoder.onnx`
3. Update `serverless/pytorch/facebookresearch/sam/nuclio/model_handler.py`
```
self.sam_checkpoint = "/opt/nuclio/sam/sam_vit_b_01ec64.pth"
self.model_type = "vit_b" 
```
4. Update `serverless/pytorch/facebookresearch/sam/nuclio/function.yaml`
```
value: curl -O https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
```
5. Build 
```
docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.https.yml -f components/serverless/docker-compose.serverless.yml -f docker-compose.dev.yml up -d --build
```
6. Deploy function `deploy_cpu.sh serverless/pytorch/facebookresearch/sam/nuclio/ `
![image](https://github.com/user-attachments/assets/49934568-991b-49e5-8a68-cbe8c2237205)

7. Use the SAM tool on an image and the results look like the following
![image](https://github.com/user-attachments/assets/20ad14e4-89cc-4532-ba2c-4488b2689153)

### Expected Behavior

I believe that the new decoder is not being used properly. Either I did not build correctly or further steps are needed to accommodate the SAM-b model

### Environment

```Markdown
Version: ad1bcd5474582c24119a4a49909eb3f1e3979899 (HEAD -> develop, origin/develop, origin/HEAD)
Docker version: 20.10.22
Docker Swarm/ Kubernetes: No
OS: Debian GNU/Linux 11 (bullseye)
```

**Comment by bsekachev** [comment]
Because you need a different `onnx` decoder on client for different SAM decoder on the server.

**Comment by bsekachev** [comment]
Make sure that the previous decoder.onnx not cached by the browser

**Comment by xx674967** [comment]
HI @bsekachev, I followed the steps above to try to change the SAM model, and I also modified the ONNX code according to the issue #6019 you sent. However, I'm encountering this problem when starting CVAT for annotation. How can I resolve this issue? Thank you. 
![sam_error](https://github.com/user-attachments/assets/7d26d30c-2b8a-4e1d-b907-6b19897b76a9)

**Comment by realtimshady1** [comment]
did you follow the advice to remove the cached model? Depending on your browser, you need to do a hard refresh to ensure that it is using the new model
