### ISSUE TITLE
When running jobs with the created YOLOv8 model, the bounding box tool is not available

### ISSUE THREAD

**Issue by Mia-aram** [cvat-ai/cvat#8163]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1.Install Docker on the Ubuntu account and clone the CVAT Git repository.
2. Deploy the YOLOv8 model.
3. Install the Nuclio CLI.
4. When creating a project at localhost:8080, set the YOLOv8 model in the constructor settings under "from model".
5. Create tasks and execute automatic annotation.
6. In the jobs section, run the corresponding job.

### Expected Behavior

I want to label images that were not automatically annotated using the bounding box tool, but I cannot find the bounding box tool in the side menu. However, when creating a project with the constructor setting as 'add label' instead of 'from model' and then running the jobs, the bounding box tool is visible and works correctly

![2](https://github.com/user-attachments/assets/315bcb8d-361c-45f4-a72a-1b67c501fc54)
![1](https://github.com/user-attachments/assets/178adb3f-b29f-440c-af57-f77695a681fc)

**Comment by bsekachev** [comment]
YOLO v8 has labels with "mask". 
Thus, your task does not have labels with "rectangle" type and the bounding box tool is disabled. 
So, use "rectangle" type or "any" type to show all the controls

**Comment by Mia-aram** [comment]
> YOLO v8 has labels with "mask" type. Thus, your task does not have labels with "rectangle" type and the bounding box tool is disabled. So, use "rectangle" type or "any" type to show all the controls

Thank you for the prompt response.
