### ISSUE TITLE
assosiate skeleton to bbx

### ISSUE THREAD

**Issue by NicolasPetermann134** [cvat-ai/cvat#8170]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I miss the ability to assosiate different labels to one instance. Eg if there are mulitples persons each person is an instance and has one skeleton and bbx. 
In coco format this is the case but I don't see this is possible in cvat. Though bbx and skeletons can only exported in cvat. 

### Describe the solution you'd like

Add possibility to assoisate skeletons and bbx to one instance and poissibilty to export it. 

### Describe alternatives you've considered

I have no idea

**Comment by bsekachev** [comment]
1. Draw a skeleton
2. Draw a box
3. Group two objects
4. Export to COCO
