### ISSUE TITLE
Issue with Authentication in CVAT SDK

### ISSUE THREAD

**Issue by sagarkalburgi** [cvat-ai/cvat#8174]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

**Description**:
Hello CVAT SDK team,

I am experiencing an issue with authenticating and retrieving annotations using the CVAT SDK in Python. Despite successfully logging in and obtaining the API key, my subsequent requests to retrieve annotations return a `401 Unauthorized` error. Here is a summary of what I've tried:

1. **Login and Obtain API Key**:
   ```python
   from pprint import pprint
   from cvat_sdk.api_client import Configuration, ApiClient, exceptions
   from cvat_sdk.api_client.models import LoginSerializerExRequest

   # Set up an API client for login
   login_configuration = Configuration(
       host='http://myhost-intern.com/'
   )

   # Login and obtain API key
   with ApiClient(login_configuration) as api_client:
       login_serializer_ex_request = LoginSerializerExRequest(
           username="user",
           email="user@user.com",
           password="user"
       )

       try:
           (data, _) = api_client.auth_api.create_login(login_serializer_ex_request)
           api_key = data.key
           pprint(data)
       except exceptions.ApiException as e:
           print("Exception when calling AuthApi.create_login(): %s\n" % e)
           raise

   # Update configuration to use the API key for authentication
   authenticated_configuration = Configuration(
       host='http://cvat-intern.clkgmbh.de/',
       api_key={'Token': api_key},
       api_key_prefix={'Token': 'Token'}
   )

   # Retrieve annotations using the API key
   with ApiClient(authenticated_configuration) as api_client:
       tasks_api = TasksApi(api_client)
       cvat_id = 585
       try:
           data = tasks_api.retrieve_annotations(cvat_id)
           pprint(data)
       except exceptions.ApiException as e:
           print("Exception when calling TasksApi.retrieve_annotations(): %s\n" % e)

*Error Message:* 
```
Exception when calling TasksApi.retrieve_annotations(): Status Code: 401
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Mon, 15 Jul 2024 14:32:57 GMT', 'Content-Type': 'application/vnd.cvat+json', 'Content-Length': '58', 'Connection': 'keep-alive', 'Allow': 'GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS', 'Cross-Origin-Opener-Policy': 'same-origin', 'Referrer-Policy': 'same-origin, strict-origin-when-cross-origin', 'Vary': 'Accept, Origin, Cookie', 'Www-Authenticate': 'Token', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': '509aed33-d3cf-40fe-bb04-3cb2ee7e2d61'})
HTTP response body: {"detail":"Authentication credentials were not provided."}
```

Any guidance or assistance on how to resolve this issue would be greatly appreciated. Thank you!

### Expected Behavior

_No response_

### Possible Solution

_No response_

### Context

_No response_

### Environment

Environment:

    CVAT SDK Version: 2.14.3
    Python Version: 3.11.8
    Operating System: Windows 11

**Comment by sagarkalburgi** [comment]
Hi,

I have tried using the high-level API but, I still get the same error.

```python
from cvat_sdk import Config, Client

config = Config()
# set up some config fields ...

with Client('http://cvat-intern.clkgmbh.de/', config=config) as client:
    client.login(('kalburgi', 'clk1234!'))

    # Retrieve annotations using the authenticated client
    cvat_id = 585

    try:
        # Fetch annotations for the specified task
        annotations = client.tasks.retrieve(cvat_id)
        pprint(annotations)
    except Exception as e:
        print(f"Exception when calling retrieve_annotations: {e}")
```

```
Exception when calling retrieve_annotations: Status Code: 401
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Tue, 16 Jul 2024 13:27:50 GMT', 'Content-Type': 'application/vnd.cvat+json', 'Content-Length': '58', 'Connection': 'keep-alive', 'Allow': 'GET, PATCH, DELETE, HEAD, OPTIONS', 'Cross-Origin-Opener-Policy': 'same-origin', 'Referrer-Policy': 'same-origin, strict-origin-when-cross-origin', 'Vary': 'Accept, Origin, Cookie', 'Www-Authenticate': 'Token', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': '43e5b767-681b-44ec-b036-28da310d1f0c'})
HTTP response body: {"detail":"Authentication credentials were not provided."}
```

**Comment by zhiltsov-max** [comment]
Please try to add an extra header like this:
```python
client.api_client.set_default_header("X-Csrftoken", client.api_client.cookies.get("csrftoken"))
```

**Comment by sagarkalburgi** [comment]
After adding an extra header:
```python
client.api_client.set_default_header("X-Csrftoken", client.api_client.cookies.get("csrftoken"))
```

I get the following error:
`Exception when calling retrieve_annotations: expected string or bytes-like object, got 'dict'`

I have also installed a local CVAT version for further debugging. With high-level API:

```python
from cvat_sdk import Config, Client

config = Config()
# set up some config fields ...

with Client('http://localhost:8080/', config=config) as client:
    client.login(('abc', 'abc1234!'))

    # Retrieve annotations using the authenticated client
    cvat_id = 1

    # client.api_client.set_default_header("X-Csrftoken", client.api_client.cookies.get("csrftoken"))

    try:
        # Fetch annotations for the specified task
        annotations = client.tasks.retrieve(cvat_id)
        pprint(annotations)
    except Exception as e:
        print(f"Exception when calling retrieve_annotations: {e}")
```

I get the following output:
`<Task: id=1>`

Using the following method:
```python
# Set up an API client
# Read Configuration class docs for more info about parameters and authentication methods
configuration = Configuration(
    host = 'http://localhost:8080/',
    username = 'abc',
    password = 'abc1234!'
)

# Login
with ApiClient(configuration) as api_client:
    login_serializer_ex_request = LoginSerializerExRequest(
        username="abc",
        email="",
        password="abc1234!"
    )

    cvat_id = 1

    try:
        (data, response) = api_client.auth_api.create_login(login_serializer_ex_request)
        pprint(data)
    except exceptions.ApiException as e:
        print("Exception when calling AuthApi.create_login(): %s\n" % e)


    format = 'CVAT for images 1.1'
    try:
        (data, response) = api_client.tasks_api.retrieve_annotations(cvat_id, _parse_response=False)
        pprint(data)
    except exceptions.ApiException as e:
        print("Exception when calling TasksApi.retrieve_annotations(): %s\n" % e)
```
I get the following output:
```
{'key': '890deec95b28a82e0b7bd70720ce06723686a412'}
None
```

**Comment by descilla** [comment]
Hi,
it is important to provide an URL with the proper protocol identifier. While your local installation is plain http the cvat instance in your initial post seems to rely on http**s** only (with a http to https redirect) while you are providing a http-url in your configuration. http://example.com and https://example.com were considered as independent scopes in view of security.

ps:

your second example could be simplified (it is not necessary to retrieve the api key or login explicitly):

```py
# Set up an API client
# Read Configuration class docs for more info about parameters and authentication methods
from pprint import pprint
from cvat_sdk.api_client import Configuration, ApiClient, exceptions
configuration = Configuration(
    host='https://hostname/',
    username="user",
    password="password"
)

with ApiClient(configuration) as api_client:
    cvat_id = 585

    format = 'CVAT for images 1.1'
    try:
        (data, response) = api_client.tasks_api.retrieve_annotations(cvat_id, _parse_response=False)
        pprint(data)
    except exceptions.ApiException as e:
        print("Exception when calling TasksApi.retrieve_annotations(): %s\n" % e)
```

**Comment by zhiltsov-max** [comment]
@sagarkalburgi, 

> I get the following error:
> Exception when calling retrieve_annotations: expected string or bytes-like object, got 'dict'

It's hard to guess without the stack trace. It seems like the response contained some data, which could not be parsed,  probably you should have used the `_parse_response=False` parameter in the request parameters.

> I have also installed a local CVAT version for further debugging. With high-level API: [...]
> I get the following output:
> <Task: id=1>

Ok, it seems to be working in that test. The comments in the code snippet speak about annotations, but you requested a task, and it was successfully retrieved.

> Using the following method: [...]
> I get the following output:
> {'key': '890deec95b28a82e0b7bd70720ce06723686a412'}
> None

I see you got no error, for the second request so it also seems to be working. `None` was returned for `data` because of `_parse_response=False` in the request parameters. If you're using this parameter, you need to check `response.data` for returned contents.


Overall, it seems like some proxy server / firewall problem with the deployed instance.

**Comment by sagarkalburgi** [comment]
@zhiltsov-max and @descilla Authentication issue has been resolved.
