### ISSUE TITLE
Serverless function works from Task menu (selecting Automatic Annotation), but not from AI Tools in the Jobs section

### ISSUE THREAD

**Issue by hermda02** [cvat-ai/cvat#8182]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create functional serverless function (Detector - mask
2. Click on Jobs banner and select a job
4. Select AI Tools and select detector
5. Click annotate

The inference results have the following format:
```
results.append({
         "type": "mask",
         "confidence": str(prob),
         "label": "Net",
         "mask": cvat_mask,
     })
```
with the following being fed into CVAT via `main.py`:

```
return context.Response(body=json.dumps(results), headers={},
        content_type='application/json', status_code=200)

```

### Expected Behavior

Expect the image to be annotated as it is in the automatic annotation procedure from the Tasks menu.
Instead, a pop up which says:

```
Detection error occurred
Cannot read properties of undefined (reading 'reduce')
```
There is no error log found within the browser console or within the nuclio docker container. I would expect code failure to be logged somewhere but it was not accessible outside of the webpage popup. 

### Possible Solution

The error appears to occur from the `.reduce` call in L1181 of https://github.com/cvat-ai/cvat/blob/develop/cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx, which is presumably called to parse the outputs of the serverless model inference (L1268?).

This however does not throw an error in the https://github.com/cvat-ai/cvat/blob/develop/cvat/apps/lambda_manager/views.py `parse_anno` function which does a similar parsing of the serverless model inference output. 

The performance of these two parses does not appear to agree, potentially due to a check for whether or not the "attributes" exist or are required depending on detector type.  

### Context

I would like to be able to go to specific frames within an uploaded video in CVAT and annotate, instead of running automatic annotation on the whole video.

### Environment

```Markdown
CVAT details:
Server version: 2.16.0
Core version: 15.1.0
Canvas version: 2.20.6
UI version: 1.64.0

System details:
Docker version 27.0.3
Ubuntu 22.04 LTS
Nvidia Driver 535.183.01
```

**Comment by bsekachev** [comment]
Unfortunately we can't help with user-defined serverless function.
Please, submit a bug request only if it may be reproducable with existing code.

You may look at implementation of other mask detectors and compare them with your.
