### ISSUE TITLE
Organization name

### ISSUE THREAD

**Issue by AOSEI1001** [cvat-ai/cvat#8184]
Unable to change the name of the organization once it's made.

**Comment by bsekachev** [comment]
You may change the name on organization page, but not SLUG. SLUG is unique and const.

**Comment by AOSEI1001** [comment]
I'm sorry, I still don't understand. I'm on the organization settings page and I still can't change the name of the organization.

**Comment by bsekachev** [comment]
![image](https://github.com/user-attachments/assets/26961e9f-4241-4c29-9b1d-5c1f79b487d9)

**Comment by AOSEI1001** [comment]
I'm referring to the "overall" organization name. I still do not have the ability to change it. 
![2024-07-18](https://github.com/user-attachments/assets/63891f59-b9d9-468c-9836-e283fff0ced1)

**Comment by bsekachev** [comment]
That is SLUG, not name. SLUG can not be changed.
