### ISSUE TITLE
Error at Export job dataset

### ISSUE THREAD

**Issue by avadosf** [cvat-ai/cvat#8191]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Mark up data
2. Try to download the dataset in Segmentation mask 1.1 format
You will get this error.
![image](https://github.com/user-attachments/assets/946c0640-070a-486d-bad0-e3cc236c97c1)

### Environment

```Markdown
The work was carried out in the online version
```

**Comment by bsekachev** [comment]
Hello,
Solved in #8185

Release in progress, app.cvat.ai will be updated today.
