### ISSUE TITLE
Export job dataset on cvat.ai website

### ISSUE THREAD

**Issue by jjlee93** [cvat-ai/cvat#8194]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Hello. I tried to export keypoint, bbox dataset but error message came out "Could not export dataset for the [job 1045254](https://app.cvat.ai/jobs/1045254) You do not have permission to perform this action."
Is there any way to fix this issue?
Thanks.

**Comment by bsekachev** [comment]
Duplicate #8191
