### ISSUE TITLE
Cuboid only on point cloud?

### ISSUE THREAD

**Issue by mohamedsamirx** [cvat-ai/cvat#8203]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

If i want to create rectangle on the pointcloud where I should add or edit the code base.

**Comment by bsekachev** [comment]
The question is too open. 
It will affect code around the whole application.
