### ISSUE TITLE
 'Deny: Private Range'. destination address was denied by rule

### ISSUE THREAD

**Issue by javamv** [cvat-ai/cvat#8207]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I have two instances of CVAT - prod and stage. And two instances of MinIO - prod and stage (192.168.11.164). They all in the same local network, but physically on the different machines. My prod cvat can create cloud storages without any issues. When I try to do the same with my CVAT stage it throws 

{"allow":false,"content_length":191,"decision_reason":"The destination address (192.168.11.164) was denied by rule 'Deny: Private Range'. destination address was denied by rule, see error","dns_lookup_time_ms":0,"enforce_would_deny":true,"id":"cqf4gs046pgs7e57ba6g","inbound_remote_addr":"127.0.0.1:38354","level":"warning","msg":"CANONICAL-PROXY-DECISION","project":"","proxy_type":"http","requested_host":"192.168.88.164:9000","role":"","start_time":"2024-07-22T11:54:24.932386282Z","time":"2024-07-22T11:54:24Z","trace_id":""}

I am just trying to understand who is defining the rules

**Comment by zhiltsov-max** [comment]
Hi, I think you should try to add smokescreen excludes for these IPs. They are written in the form: `SMOKESCREEN_OPTS="--allow-address=172.22.0.1"` (this example is for docker).

**Comment by javamv** [comment]
> Hi, I think you should try to add smokescreen excludes for these IPs. They are written in the form: `SMOKESCREEN_OPTS="--allow-address=172.22.0.1"` (this example is for docker).

many thanks, it worked

**Comment by javamv** [comment]
Changed in docker-compose.yml

SMOKESCREEN_OPTS: ${SMOKESCREEN_OPTS:--allow-address=192.168.88.164}
