### ISSUE TITLE
python sdk api_client.jobs_api.create_annotations to import annotations of COCO format

### ISSUE THREAD

**Issue by gwengusc** [cvat-ai/cvat#8215]
This is my code the import annotation file in COCO format

```
with ApiClient(configuration) as api_client:
    id = 26 # int | A unique integer value identifying this job.
    format = "COCO 1.0" # str | Input format name You can get the list of supported formats at: /server/annotation/formats (optional)
    annotation_file_request = AnnotationFileRequest(
        annotation_file = open('/Users/guifan/Downloads/annotations_7_1/instances_default.json', 'rb'),
    ) # AnnotationFileRequest |  (optional)

    try:
        api_client.jobs_api.create_annotations(
            id,
            format=format,
            annotation_file_request=annotation_file_request,
        )
    except exceptions.ApiException as e:
        print("Exception when calling JobsApi.create_annotations(): %s\n" % e)
```

Then I got the error of TypeError: Object of type bytes is not JSON serializable

The file is exported from CVAT

I tried to import zip file and failed as well.

Thanks

**Comment by zhiltsov-max** [comment]
Hi, please check https://github.com/cvat-ai/cvat/issues/6103#issuecomment-2036576486

**Comment by gwengusc** [comment]
> Hi, please check [#6103 (comment)](https://github.com/cvat-ai/cvat/issues/6103#issuecomment-2036576486)

Is there a link like https://docs.cvat.ai/docs/api_sdk/sdk/reference/apis/jobs-api/#partial_update_annotations for the new api?

**Comment by zhiltsov-max** [comment]
What do you mean by "new API"? If you're speaking about high-level API, it has documentation [here](https://docs.cvat.ai/docs/api_sdk/sdk/highlevel-api/), but it has no full API documentation yet.
