### ISSUE TITLE
install nuclo cvat AI SAM tool in local hosted CVAT on windows

### ISSUE THREAD

**Issue by kh-diab** [cvat-ai/cvat#8221]
hello all
i installed cvat locally in windows but I am not able to install AI tool for using SAM model
how to follow this 
https://docs.cvat.ai/docs/administration/advanced/installation_automatic_annotation/
in windows

**Comment by bsekachev** [comment]
On Windows you may use WSL to install CVAT, including this module.
Please, read the manual carefully.

**Comment by kh-diab** [comment]
is there anyway to install out wsl?

**Comment by bsekachev** [comment]
No.
