### ISSUE TITLE
CVAT downloads the deleted images when exporting the dataset.

### ISSUE THREAD

**Issue by leppsey** [cvat-ai/cvat#8222]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a dataset.
2. Upload a couple of images.
3. Tag them.
4. Delete a frame [Alt+Del].
5. Save.
6. Click export in ImageNet 1.0 format.

### Expected Behavior

Download the dataset without the deleted images.

### Context

I labeled data for classification, deleted poor-quality and indistinguishable ones. As a result, the deleted ones remained and affected the quality of the trained model.

### Environment

```Markdown
Server version: 2.14.4

Core version: 15.0.6

Canvas version: 2.20.3

UI version: 1.63.11
```

**Comment by bsekachev** [comment]
Hello, thanks for the report. 
Is it reproducable on the latest release?

**Comment by leppsey** [comment]
> Hello, thanks for the report. Is it reproducable on the latest release?
The problem remains.
Server version: 2.17.0

Core version: 15.1.0

Canvas version: 2.20.6

UI version: 1.64.0

**Comment by bsekachev** [comment]
@zhiltsov-max 

I remember you recently tried to reproduce very similar problem and you could not. Do you have any ideas?

**Comment by leppsey** [comment]
Is there a way to get a list of deleted frames? I would delete them manually after exporting.

**Comment by zhiltsov-max** [comment]
@leppsey, the list can be retrieved from the task or job metadata endpoints, https://app.cvat.ai/api/swagger/#/tasks/tasks_retrieve_data_meta, https://app.cvat.ai/api/swagger/#/jobs/jobs_retrieve_data_meta.

**Comment by leppsey** [comment]
Somehow the problem resolved itself, I didn't do anything.
