### ISSUE TITLE
SAM annotate tool returned error

### ISSUE THREAD

**Issue by kh-diab** [cvat-ai/cvat#8225]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

hello
I use CVAT self hosted  and enabled AI tool .
when I go to SAM AI tool 
try to annotate object 
receive the below error 

HTTPConnectionPool(host='host.docker.internal', port=32770): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2f17f9270>: Failed to establish a new connection: [Errno 111] Connection refused'))

can you tell me how to solve it please
![SAM issue](https://github.com/user-attachments/assets/d8dff264-a61b-4326-97cd-e380da022ce2)

**Comment by bsekachev** [comment]
Hello,

Try to re-deploy the function. 
It may help.
