### ISSUE TITLE
Storage space scalability

### ISSUE THREAD

**Issue by 922tech** [cvat-ai/cvat#8232]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

As the application gets more users, there is going to be much more space needed to save files like videos and images.
Current implementation tends to keep all the data on the same server as the one hosts the application.

### Describe the solution you'd like

It is inevitable to make some changes in this architecture and pipeline for storing all the files. Using scalable distrubuted-system tools like MinIO. 
And also there should be a pipeline for training/testing procedure that matches to the new architecture.

### Describe alternatives you've considered

For sure OpenCV has handled this problem for cvat.ai but I want to know how?

**Comment by bsekachev** [comment]
> As the application gets more users, there is going to be much more space needed to save files like videos and images.

Please, use K8S and EFS, for example. Or another elastic storage. 

> Current implementation tends to keep all the data on the same server as the one hosts the application.

That is in general not true, you may mount any storage, but handling such things is not responsibility of CVAT, that is responsibility of infrastructure.
