### ISSUE TITLE
Kubernetes Deployment using Helm gives 404 error 

### ISSUE THREAD

**Issue by IWang20** [cvat-ai/cvat#8234]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. `minikube start --addons registry,registry-aliases --cpus 4 --memory 5012`
2. `kubectl config set-context --current --namespace=minikube`
3. navigate to ./helm-chart
4. `helm dependency update`
5. create override file, enable traefik and add minikube ip as externalIP, enable ingress 
6.` helm upgrade -n minikube cvat-test -i --create-namespace ./helm-chart -f ./helm-chart/override.values.yaml --set ingress.hosts[0].host=YOUR_FQDN`  Taken from similar issue #5359 
7. `minikube tunnel`
8. go to localhost
9. 404 page not found

### Expected Behavior

Upon running helm upgrade and minikube tunnel, expect to see login page at localhost

### Possible Solution

Are there things that I'm missing from my `override.values.yaml` file? 
The only things I've changed from values.yaml is the enabling of traefik and ingress, adding minikube ip to traefik

### Environment

```Markdown
Windows with Minikube (docker driver)
On develop branch
```

**Comment by azhavoro** [comment]
> 5\. --set ingress.hosts[0].host=YOUR_FQDN

this is incorrect, please refere to the [values.yaml](https://github.com/cvat-ai/cvat/blob/develop/helm-chart/values.yaml#L423)
