### ISSUE TITLE
Which container uses Elastic Search?

### ISSUE THREAD

**Issue by bolero2** [cvat-ai/cvat#8238]
Which container uses Elastic Search?

Currently: Using CVAT v2.15.0, CVAT Analytics related question

I want to install a container that uses Elastic Search on another EC2 in preparation for a lot of annotation work.

However, I don't know which container uses Elastic Search. (I heard it somewhere, so I don't know if it actually uses Elastic Search.)

In addition, are there any containers that would be good to distribute to avoid server overload? (ex. cvat_db)

**Comment by bsekachev** [comment]
Probably this is outdated container.
Long time ago CVAT used ELK stack (Elasticsearch, Logstash, and Kibana)
Now it uses Vector, Clickhouse and Grafana

**Comment by bolero2** [comment]
Hi, Boris. Thank you for your reply.

Then, I have another question. Can you reply my question?

Is there some containers to be able to occur server overload?
I want to move it from ec2 that have cvat_server container to another ec2
to avoid overload.

Thank you. Regards.
Dae-Cheol, Noh.

**Comment by bsekachev** [comment]
That is very open question depending on number of users, hardware requirements, types of datasets annotated, used features, etc.

Anyway, I would recommend to put `cvat_db` and `cvat_clickhouse` to different instances.
