### ISSUE TITLE
Missing Run Actions in Menu Toolbar

### ISSUE THREAD

**Issue by Petros626** [cvat-ai/cvat#8249]
Hello,

I wanted to use the shape converter (https://docs.cvat.ai/docs/enterprise/shapes-converter/), but in my version these is no option for it. Does it depend on a specific release?

![image](https://github.com/user-attachments/assets/52fa1492-2944-4134-b402-6290c78ce9cb)

Server version: 2.8.0
Core version: 11.1.0
Canvas version: 2.17.5
UI version: 1.56.1

Many thanks

**Comment by klakhov** [comment]
Hi, @Petros626. 

The feature is only available for subscribed users. Take a look on this note in our [documentation](https://docs.cvat.ai/docs/enterprise/shapes-converter/):
![image](https://github.com/user-attachments/assets/2514f184-ad08-4d3a-a055-c4a9e51bfb37)

I agree that information may be not-so convinient. We will try to improve documentation about `Actions` feature in #8181
