### ISSUE TITLE
CVAT can't export segmented images in yolo format annotated using SAM model

### ISSUE THREAD

**Issue by kh-diab** [cvat-ai/cvat#8252]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I have CVAT installed locally 
I have images annotated using SAM model.
with segmentation method

now I tried to export the data into yolo1.1 but the files annotated is empty. when I tried to export to coco, i has 1 json file with data, do you have a reason for this please knowing that I use CVAT hosted locally not online.

### Expected Behavior

yolo format files for each image 
but the files are generated and it is empty

**Comment by joeyhouser2** [comment]
I have the same issue, but I am using CVAT online.

**Comment by kh-diab** [comment]
But there is no SAM for Cvat online as far as i know, right?

Il giorno sab 10 ago 2024 alle 19:44 joeyhouser2 ***@***.***>
ha scritto:

**Comment by bsekachev** [comment]
Please, refer to the documentation to understand types of objects, supported by different formats: https://docs.cvat.ai/docs/manual/advanced/formats/
