### ISSUE TITLE
cvat_sdk `task.export_dataset` fails if dataset export has been called once recently.

### ISSUE THREAD

**Issue by davidrs** [cvat-ai/cvat#8256]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Assumes `from cvat_sdk import make_client` being used and high level SDK
1. Call export_dataset once: `task.export_dataset("CVAT for images 1.1", dest_path_zip, include_images=False)`
2. Wait until its done.
3.  Call export_dataset a second time: `task.export_dataset("CVAT for images 1.1", dest_path_zip, include_images=False)`

The second call will throw an exception because it receives a `201` status since the request is already created / request is ready for download, but code assumes only good response is `202` (it received the request and will start prepping download).
https://github.com/cvat-ai/cvat/blob/f3dcc3e8352f6d495f22398811f24d2944b6f7cb/cvat-sdk/cvat_sdk/core/downloading.py#L100 

### Expected Behavior

The second call succesfully downloads dataset to `dest_path_zip` should work.

### Possible Solution

If the downloading helper receives a `201` it should find the corresponding request and download the zip.
I'm not certain joining the request to the right id will be trivial or not. Could the 201 also return the request id?

### Context

I intend to work around by writing my own code using the low level API to query requests for completed one if I get a 201 exception.

### Environment

```Markdown
Interacting with the hosted cvat.ai app.
```

**Comment by davidrs** [comment]
Here is my workaround if it helps anyone else:

```
...
        try:
            task.export_dataset("CVAT for images 1.1", dest_zip, include_images=False)
        except: # TODO: check error is 202 vs 201 issue
            print("Trying low level API approach")
            get_request_result(task_name, dest_zip)
...

def get_request_result(task, dest_path):
    task_id = task.id
    configuration = Configuration(
        host=HOST,
        username=CVAT_NAME,
        password=CVAT_PASSWORD,
    )

    with ApiClient(configuration) as api_client:
        try:
            (data, response) = api_client.requests_api.list(
                status="finished",
                task_id=task_id,
            )
            assert len(data['results']) == 1, "can't assume correct result if more than 1"
            result = data['results'][0]
            result_url = result['result_url']
        except exceptions.ApiException as e:
            print("Exception when calling RequestsApi.list(): %s\n" % e)

        
    with make_client(host=HOST, credentials=(CVAT_NAME, CVAT_PASSWORD)) as client:
        downloader = Downloader(client)
        downloader.download_file(result_url, output_path=Path(dest_path))
```

**Comment by vigi30** [comment]
With using CVAT Version = 2.16.2, 
I am facing the same issue when exporting the jobs with include_image argument to True. But when I set it to False, I am able to download the annotations.

**code:**

   
```
for jobs in client.jobs.list():
     if jobs.id == job_number:
         jobs.export_dataset(filename=f'{job_number}.zip', format_name='COCO 1.0', include_images=True)
```




**Error**
Exception raises 
Traceback :Status Code: 201
Reason: Created
HTTP response headers: HTTPHeaderDict({'Allow': 'GET, HEAD, OPTIONS', 'Content-Length': '0', 'Cross-Origin-Opener-Policy': 'same-origin', 'Date': 'Tue, 06 Aug 2024 22:18:29 GMT', 'Referrer-Policy': 'same-origin, strict-origin-when-cross-origin', 'Server': 'nginx', 'Vary': 'Accept, Origin, Cookie', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY, deny', 'X-Request-Id': '9406bba6-e97e-4e6f-8ed7-22305898df33'})
