### ISSUE TITLE
Introduction to CVAT and Datumaro

### ISSUE THREAD

**Issue by palmcorp** [cvat-ai/cvat#8276]
I have a data set uploaded and annotated on CVAT and want to add images to the dataset.  It's not obvious how to do this.  Create a new project/task etc. ? But how are the images added to the existing data set?

**Comment by bsekachev** [comment]
Hello, please, create a new task within a project with these images (project = dataset in context of CVAT, sharing common labels specification and many tasks, video or images, as the dataset parts). 

When they are annotated, export the project. Thus, you will get final dataset.
