### ISSUE TITLE
Previous annotation on the current image

### ISSUE THREAD

**Issue by ApaxPhoenix** [cvat-ai/cvat#8290]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

 I've encountered an issue where annotations from previously marked images are unexpectedly merging with and appearing on current images being annotated. This problem arose suddenly after successfully annotating multiple images without any issues. Now, when I move to a new, unannotated image and begin marking it, it happens naturally.

### Expected Behavior

I expected that CVAT would handle each image independently, but I guess I was wrong?

### Context

I was using CVAT like I regularly do, but for some reason, it appeared to me out of nowhere.

![Screenshot 2024-08-09 141327](https://github.com/user-attachments/assets/66165026-3dff-491c-bfb7-3d66afde8d40)

![Screenshot 2024-08-09 141253](https://github.com/user-attachments/assets/13e61da4-cd56-4b67-8a51-056ba5b223da)

![Screenshot 2024-08-09 141315](https://github.com/user-attachments/assets/6d5bbf09-1ee1-438c-b92c-439c0ae30438)

![Recording 2024-08-09 140324](https://github.com/user-attachments/assets/86a979f8-580b-4b9d-b3fe-9feffe981d05)

### Environment

```Markdown
OS: Windows 11
Current Browser: Edge
```

**Comment by josiahls** [comment]
@ApaxPhoenix Those are tracks, they are supposed to propagate across images. If you don't want to have them show up on proceeding images, use shape labels instead

**Comment by josiahls** [comment]
Note these pages: https://docs.cvat.ai/docs/manual/basics/shape-mode-basics/ (which is want you should use for nonsequential images) and https://docs.cvat.ai/docs/manual/basics/track-mode-basics/ when you are labeling videos so images are expected to be sequential.
