### ISSUE TITLE
Incorrect Yolo label export

### ISSUE THREAD

**Issue by joeyhouser2** [cvat-ai/cvat#8291]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Export task dataset
2. Save images
3. Label type as Yolo
4. Download and extract
5. All label files are correctly named, but their contents only contain a few of the bounding box coordinates (sometimes none) as opposed to 10-15 on every one of my images.

### Expected Behavior

Yolo files are supposed to list the label number with 4 coordinates. I have 15 labels in each image so there should be 15 rows of data in each label file, but I am currently getting max ~3 and sometimes none in my exports on all of my task datasets.

**Comment by joeyhouser2** [comment]
Just tried exporting the dataset without saving images as well - same result.
I am currently unable to to use any of the data that I've labeled.

**Comment by dataScience-noob** [comment]
I am also facing the same problem. All exports to YOLO 1.1 format is affected. I am able to export to CVAT 1.1 without issues. I tried exporting some of my previous projects to see if it is an issue with the dataset. But even the datasets that were working fine earlier gives incomplete (mostly null) exports now.

**Comment by prashantkatoch12** [comment]
Facing the same issue. Tasks - export task dataset - export format - YOLO 1.1 - ok. Saved the downloaded dataset, but out of 44 annotation txt files only first three have Bounding Box coordinates, rest all txt files are blank. Please let me know if you find some solution to it. May be they give it for paid version only.

**Comment by dataScience-noob** [comment]
I will try to explain this based on my experience so far. While annotating, did you rotate the bounding boxes to match the orientation of the object in the image? In the YOLO format, bounding boxes are expected to be axis-aligned with the image (the sides of the bounding box should always align with the sides of the image, not object). Rotating the bounding boxes can cause confusion and CVAT may not save the coordinates for these boxes. 
The solution is to annotate the objects in such a way that the bounding boxes are parallel to the sides of the image even if this means capturing more background within the box. I hope this helps!

**Comment by nicooolo** [comment]
This issue is still persisting up to this day. exporting in Yolo 1.1 format loses the bounding box that is not parallel to the sides of the image. so the only way to annotate is to use rectangle. 

To replicate:

1. annotate any image(s) that is not a square or a rectangle, either by a polygon or even just purely rotating your annotation. 
2. export said images
3. extract from zip check obj_train_data folder
4. check the file .txt with the rotated image or polygon image to confirm the lost annotation.
