### ISSUE TITLE
Sharing Option 

### ISSUE THREAD

**Issue by seven-smile** [cvat-ai/cvat#8296]
I have recently annotated task in cvat and tried copying the link to the task from the browser( i am assuming that is how its done) but when i paste in in another browser that has a different account, i am unable to see the annotatedwork or task and i get the error message "Could not receive the requested task from the serverError: You do not have permission to perform this action"   what could the  issue be and how can share ,y work link with someone else?

**Comment by bsekachev** [comment]
Hello,

Collaboration only works with your team members in an organization. 
You may invite somebody to the organization, assign corresponding role and thus these users may have access to resources. 

Resources from personal workspace can not be shared. 

Regarding "share" feature, there is existing issue https://github.com/cvat-ai/cvat/issues/7930, so, I will close this one.

**Comment by seven-smile** [comment]
alright. Understood
