### ISSUE TITLE
Constant buffering every 10 frames, on both web and local instalation

### ISSUE THREAD

**Issue by AndyBarcia** [cvat-ai/cvat#8302]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Install CVAT (I tried it on 2.16.3) or open the web app.
2. Create a new project and a new task, with a high-resolution video
3. Try to play the video or step more than 10 frames at a time. The video always buffers for several seconds, both in Chromium and Firefox.

### Expected Behavior

The video should reproduce normally, specially in a local installation, even with a high resolution video (3840 by 2160 pixels in my case).

### Possible Solution

I have absolutely no idea. 

### Context

As it is, CVAT is barely usable by itself. I have to use another video player to actually play the video, and then move to that part of the video in the CVAT player. 

### Environment

```Markdown
CVAT 2.16.3
Docker version 24.0.7
Ubuntu 22.04.1
Chromium 127.0.6533.99
Firefox 129.0
```

**Comment by bsekachev** [comment]
> The video should reproduce normally, specially in a local installation, even with a high resolution video (3840 by 2160 pixels in my case).

I do not think that is possible.

When you first time request a data chunk, the server starts preparing it. Thus, it decodes your video and creates archive with images. Then this archive sent to the browser and unzipped there.

Why it so complicated? Short answer: to provide precise frames positioning when navigating between frames.
Unfortunately, this approach usually generates chunks with bytes size much more than corresponding part of the video. 

You may disable "Use cache" option. Than chunks will be generated during task creation. But it will eat a lot of your disk space.
