### ISSUE TITLE
Export tasks dataset with coco format,get wrong bbox and area

### ISSUE THREAD

**Issue by lujiangtao** [cvat-ai/cvat#8307]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1.  create a annotation job and upload pre-labeled annotations
![1](https://github.com/user-attachments/assets/69dd9a9b-2969-4cd8-b5e7-924b0494923b)

-  uploaded successed annotations, this is my original annotation
- ![image](https://github.com/user-attachments/assets/f749cbed-52cb-4f26-a6bb-611b7fb8f435)

2. export task dataset with coco1.0 format, i got instance_default.json, but my annotation got wrong bbox and area.

- ![image](https://github.com/user-attachments/assets/4cbdd35b-f98a-435d-8631-d709419a9951)

3. when i upload this instance_default.json without any edit, the rect is like this.

- 
![image](https://github.com/user-attachments/assets/6050b857-509d-4092-8912-08ad232621d5)

### Expected Behavior

the bbox of uploaded annotations.json should be consistent with bbox of exported dataset instance_default.json

### Possible Solution

when export dataset, maybe there is a problem calculating bbox

### Context

task in app.cvat.ai
https://app.cvat.ai/tasks/853785/jobs/1153581
my original annotation
[instances_default.json](https://github.com/user-attachments/files/16622736/instances_default.json)
wrong annotation from export task dataset
[instances_default.json](https://github.com/user-attachments/files/16622747/instances_default.json)

**Comment by bsekachev** [comment]
Hello,

Is the issue reproducible today? I mean importing correct annotations, export, and importing exported file back?

**Comment by lujiangtao** [comment]
> Hello,
> 
> Is the issue reproducible today? I mean importing correct annotations, export, and importing exported file back?

yeh，reproducible in my local cvat env which server version is 2.4.9. then i reproducible on app.cvat.ai which server version is 2.16.3 
this is my wrong task
https://app.cvat.ai/tasks/853785?page=1

**Comment by bsekachev** [comment]
Okay, thank you for the report, we will work on this.

**Comment by Eldies** [comment]
Hi! 
Your original annotation file contains two annotations with the same id=510 (and the same with the ids 511 to 531)
Since coco format only allows to have one annotation for each id, CVAT merges two annotations into one on export.

**Comment by lujiangtao** [comment]
> Hi! Your original annotation file contains two annotations with the same id=510 (and the same with the ids 511 to 531) Since coco format only allows to have one annotation for each id, CVAT merges two annotations into one on export.

got that. I didn't find the problem. it helped a lot. i will close this isuue, thanks

**Comment by KaiMJ** [comment]
I am running into the same issue.

In the cvat ui, everything looks right. is there a way to reset all annotation_ids instead of manually fixing everything? I have already fixed my psuedo-labels and there are too many images to fix manually.

found SOLUTION:

export to CVAT xml --> fix group_id and import back to CVAT xml --> export coco
