### ISSUE TITLE
Debug stopped while try to run server: debug

### ISSUE THREAD

**Issue by smit9924** [cvat-ai/cvat#8313]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. follow steps one by one mentioned in official documentation to setup development environment.
Link: https://docs.cvat.ai/docs/contributing/development-environment/
2. Issue occurs at this step.
![image](https://github.com/user-attachments/assets/12a3be8c-1e34-47ad-b7aa-fd64210a3493)

While try to run server: debug then getting error popup in VS Code saying "debug stopped" without any error message.
![Screenshot 2024-08-11 121755](https://github.com/user-attachments/assets/40cbd655-1f80-4fda-b822-f4cdd7a239f2)

### Expected Behavior

Expected behavior for this steps is to system should start all backed services for CVAT mentioned in `launch.json` file. And then we should be able to access all APIs in fronted without getting any error.

### Possible Solution

I spent a significant amount of time debugging an issue and eventually identified the root cause of the DEBUG STOPPED error popup. The issue arose while setting up the CVAT development environment in WSL (Windows Subsystem for Linux).

**1. Debugging the issue:**

- I followed the official CVAT documentation and tried to open VS Code by running the following command: `source .env/bin/activate && code`

- However, instead of opening VS Code inside the WSL environment, it opened in another location outside of WSL.

- When I attempted to run the `server:debug` , it failed because **it couldn't locate the appropriate Python compiler path**.

- The system was mistakenly searching for the compiler in the C drive, which led to the debug process failing and prevented the backend services from starting.

**2. Solution** 

- To resolve this problem, it is necessary to install the `WSL` vs code extension authored by Microsoft. To find the extension[ click here](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl).
![image](https://github.com/user-attachments/assets/06277b05-1b50-4624-828b-3e7cdf027429)

- Once the extension is installed, the `server:debug` command will run successfully without any errors and all the backed services for CVAT will by up successfully.

**3. My Recommendation** 

- **I recommend that the CVAT documentation include a note specifically for Windows users, advising them to install the WSL VS Code extension when setting up the development environment. This addition would help prevent similar issues for other users and ensure a smoother setup process.**

### Environment

```Markdown
WSL Ubuntu 22.04 (windows 11)
```

**Comment by smit9924** [comment]
I request mentor to add `documentation` label to this issue.

**Comment by azhavoro** [comment]
Fixed in https://github.com/cvat-ai/cvat/pull/8314
