### ISSUE TITLE
Export Error to CVAT 1.1 

### ISSUE THREAD

**Issue by shekarneo** [cvat-ai/cvat#8324]
I have annotated masks, bounding boxes and keypoints.
have 4 tasks out 4, 2 tasks are ~20 images and i have successfully exported to cvat 1.1 format.
other tasks have more than 60 images and it is giving me `IndexError: list index out of range` error when exporting to cvat 1.1 format.
but the same export is working for other formats.

**Comment by bsekachev** [comment]
Please, provide environment setups.

**Comment by azhavoro** [comment]
No reply, I'll close this issue for now.
