### ISSUE TITLE
An unexpected error occurred when I uploaded labels with more than 5,000 categories.

### ISSUE THREAD

**Issue by wbh604** [cvat-ai/cvat#8328]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

In the locally deployed CVAT, after creating a project, I imported labels into it according to a given JSON format. When the number of imported labels isn't large, it works fine. However, since my dataset contains over 5,000 categories, when I try to import all the categories, an error occurs as shown in the image. ![image](https://github.com/user-attachments/assets/3789a211-bfa0-4295-b565-da5d9f40d31b)

**Comment by wbh604** [comment]
here is my label raw:

**Comment by bsekachev** [comment]
Please, provide the server request details

**Comment by wbh604** [comment]
> 请提供服务器请求详细信息
I added the tags in this location and submitted them without sending them through an API request.
![image](https://github.com/user-attachments/assets/1d0692dc-f50a-4d83-ab39-8044a9c6a083)

**Comment by bsekachev** [comment]
Please, provide the server request details.
Or, please provide the full list of labels you submitted to the location.

**Comment by azhavoro** [comment]
There's been no response for a long time, let's close this issue for now.
