### ISSUE TITLE
Ground Truth jobs don't show up on "Jobs" page

### ISSUE THREAD

**Issue by thmegy** [cvat-ai/cvat#8330]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a task with one job (in an organization with owner role)
2. Create a GT job for the task
3. Go to "Jobs" page --> The GT jobs is not visible, only the nominal jobs...

### Expected Behavior

As an owner/maintainer, see all jobs in the "Jobs" page, including GT jobs.
As a worker, see all jobs assigned to me, including GT jobs.

### Environment

```Markdown
Server version: 2.17.0
Core version: 15.1.0
Canvas version: 2.20.6
UI version: 1.64.0
```

**Comment by bsekachev** [comment]
Fixed in 2.21.0
