### ISSUE TITLE
Is there a API of CVAT python sdk to call SAM?

### ISSUE THREAD

**Issue by gwengusc** [cvat-ai/cvat#8332]
I want to generate the annotation by SAM in a automate workflow, also I want to verify if SAM is working fine in the CVAT service. Not sure if there is a API for calling it?

**Comment by azhavoro** [comment]
Hello,

Please take a look at https://app.cvat.ai/api/swagger/#/functions
and https://docs.cvat.ai/docs/api_sdk/sdk/reference/apis/lambda-api/#create_requests
