### ISSUE TITLE
Where is the path where the labeling worker's job log is saved?

### ISSUE THREAD

**Issue by bolero2** [cvat-ai/cvat#8350]
I have one question.

When using the existing 2.3.0 version of CVAT, the following log was saved in `data/tasks/{task_id}/logs/task.log` in the cvat_server docker container.

```python
{"job_id":857,"task_id":881,"client_id":642278,"name":"Fit image","time":"2024-07-19T04:17:37.642000Z","payload":{},"is_active":true,"username":"user1"}
{"job_id":857,"task_id":881,"client_id":642278,"name":"Change frame","time":"2024-07-19T04:17:39.416000Z","payload":{"from":0,"to":1},"is_active":true,"username":"user1"}
```

After upgrading CVAT to 2.15.0, I cannot see the log. (The file is not visible.)
 
<img width="332" alt="image" src="https://github.com/user-attachments/assets/09c79b99-3888-4ee9-baf2-d85beef8fff1">

Do I need to turn on any related features or settings, or is the location where it's saved different?

**Comment by bsekachev** [comment]
All the logs are stored in clickhouse now (cvat_clickhouse docker container)
