### ISSUE TITLE
Exporting review comments with annotations

### ISSUE THREAD

**Issue by DainiusGaidamaviciuss** [cvat-ai/cvat#8353]
Hello,
I want to save not only annotations but also their issues (comments that are made during review by clicking right mouse button and choosing "Open Issue") however I cannot find any export format that would do that.
Am I missing something, or it isn't implemented? If not, there are any possibilities to get such a feature in near future?
Also, it would be nice to upload such comments during task creation

**Comment by bsekachev** [comment]
You can't export issues in annotation formats as no one format supports such kind of data. 
You may try to use backup/restore feature, but I do not remember if it really exports issues or not.

**Comment by bsekachev** [comment]
> Also, it would be nice to upload such comments during task creation

You may use write your own script and use API for that purpose.

**Comment by DainiusGaidamaviciuss** [comment]
Is it possible also to get comments using API instead of using backups/restore?

**Comment by DainiusGaidamaviciuss** [comment]
> > Also, it would be nice to upload such comments during task creation
> 
> You may use write your own script and use API for that purpose.
Could you provide API endpoint for this use case?

**Comment by bsekachev** [comment]
All API may be found here: https://app.cvat.ai/api/swagger/ or on the same endpoint in your locally installed CVAT
