### ISSUE TITLE
Unable to Log In to CVAT Main Webpage After Restarting Windows 11

### ISSUE THREAD

**Issue by balandongiv** [cvat-ai/cvat#8356]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Expected Behavior

I am unable to log in to the CVAT main webpage, even though I was able to log in and complete tasks previously. This issue started occurring after I restarted my Windows 11 system

### Context

Upon click the url path

When accessing the url
![image](https://github.com/user-attachments/assets/ffd2d3c6-9239-497e-8586-a4310b503945)

There is a notification 

> Could not receive server schema
> Cannot convert undefined or null to object

 
Then, upon entering both the username and password, and click next, there is another notification

> Could not login on the server
> Open the Browser Console to get details

### Environment

```Markdown
Docker Version: 4.32.0 (157355)
Windows 11
```

**Comment by bsekachev** [comment]
Be sure server container is working and healthy.

**Comment by orenong** [comment]
same, maybe microsoft broke something?

**Comment by balandongiv** [comment]
> Make sure the server container is working and healthy.

Thanks for the response @bsekachev , may I know what measure I should do to check whether the server is working and healthy?

Apart from that, worse case if the docker is corrupted, may I know how can I retrieve/recover label that I had completed?

Really appreciate for your insight.

**Comment by balandongiv** [comment]
For some reason, thing back to normal, after I reinstall and follow all the instruction https://docs.cvat.ai/docs/administration/basics/installation/#windows-10.
