### ISSUE TITLE
Export label empty files - yolov8 export confusion

### ISSUE THREAD

**Issue by davy-blavette** [cvat-ai/cvat#8367]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

We don't have the tags in the exports. I have tried all versions of the tags: https://docs.cvat.ai/docs/manual/advanced/formats/#data-export-formats

the generated .txt label files have no value. yet my jobs are completed.

![image](https://github.com/user-attachments/assets/00a6f59b-1955-4e8b-b0e5-c1a2ed60a912)
![image](https://github.com/user-attachments/assets/075f0768-7ed7-46f6-8633-384bb3a5847f)

### Expected Behavior

export with dashboard or sdk but the same problem.

**Comment by bsekachev** [comment]
Which formats do not support tags?

**Comment by davy-blavette** [comment]
Its ok sry, it was my mistake

**Comment by davy-blavette** [comment]
hum,  I tested the two latest export formats YOLOv8 Detection 1.0 and YOLOv8 Oriented Bounding Boxes 1.0 but the label files were empty before I used COCO 1.0 (which still works). I have a dataset with maskshape (Oriented Bounding Boxes) for detection.

**Comment by bsekachev** [comment]
If you want to export everything (or almost everything), please, use CVAT or Datumaro formats. 

> I have a dataset with maskshape (Oriented Bounding Boxes) for detection ...... works with YOLOv8 Segmentation 1.0

Oriented bounding box may be easliy converted to a mask. That is why we support such conversion. 

We won't add support for an object to a format if specification of that format does not support such objects. For example YOLOv8 does not have unified format structure for all shapes. That is why we devided it to several formats.
