### ISSUE TITLE
ValueError: No media data found(when importing dataset)

### ISSUE THREAD

**Issue by chenmz-lab** [cvat-ai/cvat#8371]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

As I want to see how coco keypoints' annotations look like in pictures in cvat,but the whole coco dataset is too large hence I choose a single picture and its related annotations and compress them to a zip file,when I choose to import dataset in a new project,it says"ValueError: No media data found",how could this happen and what should I do?Sincerely waiting for some help
[cvat_test1.zip](https://github.com/user-attachments/files/16791182/cvat_test1.zip)

### Expected Behavior

I expect to successfully import the self-made dataset,and see how coco annotate human's keypoints.

**Comment by bsekachev** [comment]
If your dataset is self-made, it must be in one of supported formats. Othewise it is not possible to recognize it. 
To  understand the format you may read the specification, or export a dataset from CVAT in a target format and compare it and your own self-made. Their structure must be the same.

**Comment by chenmz-lab** [comment]
> If your dataset is self-made, it must be in one of supported formats. Othewise it is not possible to recognize it. To understand the format you may read the specification, or export a dataset from CVAT in a target format and compare it and your own self-made. Their structure must be the same.

Thank you,it turns out that I lacked some segmentations,I just chose one but there are three in the original whole dataset.And I didn't setup skeletons in cvat in advance.
