### ISSUE TITLE
How to display images in "original" quality in the annotation view?

### ISSUE THREAD

**Issue by wtiandong** [cvat-ai/cvat#8375]
Hi,
I'm trying to display images in their original quality in the annotation view. I attempted to modify the code in `server-proxy.ts` as follows, but it didn't work:
```ts
async function getData(jid: number, chunk: number, quality: ChunkQuality, retry = 0): Promise<ArrayBuffer> {
    const { backendAPI } = config;

    try {
        const response = await (workerAxios as any).get(`${backendAPI}/jobs/${jid}/data`, {
            params: {
                ...enableOrganization(),
                quality: 'original', // here fixed to original quality
                type: 'chunk',
                number: chunk,
            },
            responseType: 'arraybuffer',
        });

        ...
}
```
I referenced this from [patch](https://github.com/cvat-ai/cvat/pull/5460/).

Could anyone help me with this? I only need images in their original quality and do not require switching between original and compressed quality, as I am deploying CVAT within a local network.

Best regards,

**Comment by azhavoro** [comment]
Hello,

Could you please describe your actions besides the file change you mentioned?

**Comment by wtiandong** [comment]
> Hello,
> 
> Could you please describe your actions besides the file change you mentioned?

Hi @azhavoro ,
Thank you for the reply. 
After modifying the code, I ran the following commands to restart the CVAT server:
```bash
docker compose down
docker compose up -d
```
Then, I re-logged into CVAT, opened a previously uploaded Task (which was uploaded with 100% quality in the advanced configuration), opened the annotation view, but the image quality did not seem to improve. I also checked the URL of the image data via Chrome's inspect tool and found that:

<img width="736" alt="image" src="https://github.com/user-attachments/assets/789710d8-b65a-4a2d-b042-1de88279f69a">

**Comment by azhavoro** [comment]
You need to build the images after modifying the source code
```console
docker compose -f docker-compose.yml -f docker-compose.dev.yml build

```

**Comment by wtiandong** [comment]
> You need to build the images after modifying the source code
> 
> ```
> docker compose -f docker-compose.yml -f docker-compose.dev.yml build
> ```

Thank you, @azhavoro ! It did work!
