### ISSUE TITLE
Change the label of an existing skeleton

### ISSUE THREAD

**Issue by ZJZ0405** [cvat-ai/cvat#8383]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

When I use my custom autotagging model, sometimes the model gives the wrong label. At this point I tried to fix the error, but I found that the skeleton tag could not be modified.
![image](https://github.com/user-attachments/assets/fb92f2a2-4621-4af6-a50b-99988f1039be)

### Describe the solution you'd like

Very simply, do I want to get the modification tag, or tell me how I can lift this restriction

### Describe alternatives you've considered

Currently I can only change the auto-annotated label map to solve this problem, because I want to train the keypoints model, so I need to use auto-annotated to ensure that my data set is accurate enough. Is that why I don't build a new skeleton

**Comment by bsekachev** [comment]
Each skeleton in general is unique. You can't just assign skeleton1 to skeleton2 because their structure is usually different. 

If this is not a case, please explain why.

**Comment by ZJZ0405** [comment]
> Each skeleton in general is unique. You can't just assign skeleton1 to skeleton2 because their structure is usually different.一般来说，每个骨骼都是独一无二的。您不能只将 skeletal1 分配给 skeletal2，因为它们的结构通常不同。
> 
> If this is not a case, please explain why.如果不是这种情况，请解释原因。

I know what you mean. Every skeleton is unique. However, if I want to classify different objects of the same skeleton, for example, design two labels: man and woman, they both belong to the same skeleton: person. Then how can I use cvat to label them.

**Comment by ZJZ0405** [comment]
If I add an extra attribute to the skeleton to describe the class I want, the class in that extra attribute will not be recognized and derived

**Comment by bsekachev** [comment]
> both belong to the same skeleton: person

- Create a skeleton person
- Add attribute `gender`

>  extra attribute will not be recognized and export

This is defenitely depends on the model you are using.

**Comment by bsekachev** [comment]
Generally, I understand your use-case. But this is quite rare. I do not think that the core team is going to work on it. You always may contribute your own pull request. Let us know if you need any help on that.

**Comment by ZJZ0405** [comment]
Thanks for your reminding, I found that the export format I used, YOLOv8 Pose, does not recognize additional attributes. Considering that this function may not be common, I will modify the YOLOv8 Pose export function to fulfill my needs
