### ISSUE TITLE
Cannot read properties of undefined (reading 'flat')

### ISSUE THREAD

**Issue by ZJZ0405** [cvat-ai/cvat#8384]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I created a custom interactor modeled after SAM's main.py, but when I used it, the page reported the error

error:
![2024-09-01 004556](https://github.com/user-attachments/assets/12a9e5a5-3650-40ae-a6e6-329a38aca3c0)

I checked my nuclio container and found no error. No interactive does not support automatic annotation of skeletons

### Expected Behavior

I would like to know how this problem occurs and how to solve it

### Possible Solution

I think some automatic tagging tools may need to provide some advance information to help them complete the tagging, like the one I designed.

### Context

main.py
`import io
import base64
import json

import cv2
import numpy as np
from detect import *

# Initialize your model
def init_context(context):
  context.logger.info('Init context...  0%')
  context.logger.info('Init context...100%')

# Inference endpoint
def handler(context, event):
  context.logger.info('Run legacy autoaim armor detect')
  data = event.body
  image_buffer = io.BytesIO(base64.b64decode(data['image']))
  image = cv2.imdecode(np.frombuffer(image_buffer.getvalue(), np.uint8), cv2.IMREAD_COLOR)
  pos_points = data["pos_points"]
  neg_points = data["neg_points"]

  pos_points, neg_points = list(pos_points), list(neg_points)

  pos_points = np.array(pos_points).astype(np.int32)

  if not len(pos_points) == 8:
    return []
  detect = Process(image, pos_points)

  res = detect.detect()

  points = [
        float(res[0][0]), float(res[0][1]),
        float(res[1][0]), float(res[1][1]),
        float(res[2][0]), float(res[2][1]),
        float(res[3][0]), float(res[3][1])
      ]

  return context.Response(body=json.dumps(
    {
      'confidence': "1.0",
      'label': "Armor",
      'type': 'skeleton',
      'points': points,
      "elements": [
        {
          "label": str(id+1),
          "type": "points",
          "outside": 0,
          "points": [
              str(float(res[id][0])),
              str(float(res[id][1]))
          ],
          "confidence": "1.0",
        } for id in [0, 1, 2, 3]
      ],
      "attributes": [
        {"name": "Color", "value": "Blue"},
        {"name": "Type", "value": "Hero"},
      ]
  }),
    headers={},
    content_type='application/json', status_code=200)
`

function.yaml
`metadata:
  name: legacy-autoaim-help-ann
  namespace: cvat
  annotations:
    name: legacy-autoaim-help-ann
    type: interactor
    version: 2
    min_pos_points: 8
    min_neg_points: 0
    # change this accordingly to your model output/classes
    spec: |
      [
        {
          "name": "Armor",
          "type": "skeleton",
          "svg": "<circle r=&quot;0.75&quot; cx=&quot;41.39057159423828&quot; cy=&quot;32.107025146484375&quot; data-type=&quot;element node&quot; data-element-id=&quot;1&quot; data-node-id=&quot;1&quot; data-label-id=&quot;13&quot;></circle>\n<circle r=&quot;0.75&quot; cx=&quot;70.82201385498047&quot; cy=&quot;32.107025146484375&quot; data-type=&quot;element node&quot; data-element-id=&quot;2&quot; data-node-id=&quot;2&quot; data-label-id=&quot;14&quot;></circle>\n<circle r=&quot;0.75&quot; cx=&quot;41.72502136230469&quot; cy=&quot;48.3277587890625&quot; data-type=&quot;element node&quot; data-element-id=&quot;3&quot; data-node-id=&quot;3&quot; data-label-id=&quot;15&quot;></circle>\n<circle r=&quot;0.75&quot; cx=&quot;71.15645599365234&quot; cy=&quot;46.8227424621582&quot; data-type=&quot;element node&quot; data-element-id=&quot;4&quot; data-node-id=&quot;4&quot; data-label-id=&quot;16&quot;></circle>",
          "sublabels": [
              { "id": 0, "name": "1", "type": "points" },
              { "id": 1, "name": "2", "type": "points" },
              { "id": 2, "name": "3", "type": "points" },
              { "id": 3, "name": "4", "type": "points" }
          ],
          "attributes": [
              {
                "name": "Color",
                "input_type": "select",
                "mutable": false,
                "values": [
                  "Blue",
                  "Red",
                  "None",
                  "Purple"
                ],
                "default_value": "Blue"
              },
              {
                "name": "Type",
                "input_type": "select",
                "mutable": false,
                "values": [
                  "Hero",
                  "Engineer",
                  "Three",
                  "Four",
                  "Five",
                  "Outpost",
                  "Sentry",
                  "SmallBase",
                  "BigBase"
                ],
                "default_value": "Hero"
              }
          ]
        }
      ]

spec:
  description: legacy-autoaim-help-ann
  runtime: 'python:3.9'
  handler: main:handler
  eventTimeout: 30s

  build:
    image: cvat.legacy.autoaim.help-ann
    baseImage: ubuntu:22.04

    directives:
      preCopy:
        - kind: ENV
          value: DEBIAN_FRONTEND=noninteractive
        - kind: RUN
          value: apt-get update && apt-get -y install curl git python3 python3-pip
        - kind: RUN
          value: apt-get -y install libgl1-mesa-glx libglib2.0-dev
        - kind: WORKDIR
          value: /opt/nuclio
          #
          # make sure that for the next step (at least) the ultralytics package version
          # is compatible to that of the the ultralytics package used to train the custom model
        - kind: RUN
          value: pip3 install opencv-python==4.10.0.84 numpy==1.26.4
        - kind: RUN
          value: ln -s /usr/bin/pip3 /usr/local/bin/pip
        - kind: RUN
          value: ln -s /usr/bin/python3 /usr/local/bin/python

  triggers:
    myHttpTrigger:
      maxWorkers: 2
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
`

**Comment by bsekachev** [comment]
SAM models requires additional handling on client (running features decoder with provided user clicks).
Please, see: `cvat-ui/plugins/sam`

**Comment by ZJZ0405** [comment]
Perhaps my code explanation was too long and you misunderstood my intention. I tried to send a custom skeleton annotation message to the server, which is the same as when I used the detector mode. Here is the key code

**Comment by ZJZ0405** [comment]
> Perhaps my code explanation was too long and you misunderstood my intention. I tried to send a custom skeleton annotation message to the server, which is the same as when I used the detector mode. Here is the key code

![image](https://github.com/user-attachments/assets/eda75334-3386-4f71-8c0e-a4014e3bb764)
