### ISSUE TITLE
A way to add extra keypoints to the current annotation format

### ISSUE THREAD

**Issue by AkitaRaphael** [cvat-ai/cvat#8385]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

There are 17 body points only in the COCO keypoint format. Is there a way that I can add more points to the same one detected person by using CVAT?

**Comment by bsekachev** [comment]
![image](https://github.com/user-attachments/assets/0bdb856e-1911-470e-8a56-0de0db0e8265)
![image](https://github.com/user-attachments/assets/d5825f13-49d7-445f-a26e-c50134debaea)
