### ISSUE TITLE
Can't deploy custom tracking model for auto labeling

### ISSUE THREAD

**Issue by sangeun-jo** [cvat-ai/cvat#8387]
I trained a YOLOv8-deepSORT model with custom data, and it worked well when deployed as a detector type. However,  I'm unsure how to write a function.yaml file for tracker type, so I tried to refer to the Siammask function.yaml as an example. Unfortunately, when I deployed the Siammask model, it failed to track and returned a 500 server error. The error log is as follows:
```
(E) sor.http.w1.python.logger Exception caught in handler {"exc": "'NoneType' object is not subscriptable", "traceback": "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 151, in serve_requests\n    await self._handle_event(event)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 439, in _handle_event\n    entrypoint_output = self._entrypoint(self._context, event)\n  File \"/opt/nuclio/main.py\", line 19, in handler\n    buf = io.BytesIO(base64.b64decode(data[\"image\"]))\nTypeError: 'NoneType' object is not subscriptable\n", "worker_id": "1"}
```
My goal is not to solve this problem directly. Instead, I'm looking for a good example of a tracking model's yaml configuration and a Python script for my custom model.

**Comment by azhavoro** [comment]
I hope this will be helpful
https://docs.cvat.ai/docs/manual/advanced/serverless-tutorial/#adding-your-own-dl-models
