### ISSUE TITLE
Can the front-end CVAT-UI image not use nginx? If not, what should I do to ensure that the project works properly

### ISSUE THREAD

**Issue by chenrongjian** [cvat-ai/cvat#8391]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

Can the front-end CVA-UI image not use nginx? If not, what should I do to ensure that the project works properly

**Comment by azhavoro** [comment]
> Can the front-end CVA-UI image not use nginx?

The short answer is yes. Any web server capable of serving static content with proper configuration can be used as the base  image.
