### ISSUE TITLE
Feature Request: Add Images to Existing Task

### ISSUE THREAD

**Issue by gauravlochab** [cvat-ai/cvat#8392]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

Currently, it seems there's no straightforward way to add new images to an existing task in CVAT. This limitation forces users to create new tasks or use workarounds when they need to expand their dataset, which can be time-consuming and disruptive to the annotation workflow

### Describe the solution you'd like

Ability to add new images to an existing task directly from the task details page
An "Upload Images" or "Add Images" option in the task's "Actions" menu
Maintain all existing task settings and annotations when adding new images

### Describe alternatives you've considered

Creating a new task: This works but results in fragmented datasets and requires replicating task settings.

**Comment by azhavoro** [comment]
Hello

Thanks for the feature request, but we don't plan to support this at this time.
Project is an existing concept that already solves this problem:

- You can set project-level labels for all tasks in the project
- You can add images to the project by creating a new task
