### ISSUE TITLE
Could not create the task  Open the Browser Console to get details

### ISSUE THREAD

**Issue by jacopich** [cvat-ai/cvat#8396]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I'm simply trying to use the tool, but as soon as I add the image to the task I want to work on, the error "Could not create the task  Open the Browser Console to get details" appears when i press "Submit&".

### Context

```Markdown
I am currently use the just the online version, in the console i get theese errors:

- Failed to load resource: the server responded with a status of 404 (Not Found)
- Failed to load resource: the server responded with a status of 403 (Forbidden)
- Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

```

**Comment by magic-Alex** [comment]
Hello, I encountered the same issue. Could you please let me know how you resolved it?
