### ISSUE TITLE
Could not receive image data

### ISSUE THREAD

**Issue by giconsultapp** [cvat-ai/cvat#8398]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

After restarting the containers yesterday, we encountered an issue where most of the jobs with labeled images are not accessible. The jobs were created simultaneously, and the images are located in the same folder, connected via a shared path. When trying to open some jobs, we receive the following error:

"Could not receive image data

<!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>."

At the same time, the rest of the jobs are accessible and unaffected.

We are using CVAT Version 2.15.0.
![image](https://github.com/user-attachments/assets/5b6b408c-d584-4276-a6ef-9e278ceeba35)

**Comment by bsekachev** [comment]
If you created tasks from a cloud storage or the connected share, be sure the data are still available.

**Comment by azhavoro** [comment]
Please provide logs from cvat_server container at least

**Comment by shery909** [comment]
Facing similar issues. Have you been able to solve this?

**Comment by giconsultapp** [comment]
> Facing similar issues. Have you been able to solve this?

It was an issue with the connected share, and it was not mounted correctly.
