### ISSUE TITLE
Ghost box when quickly using occlusion

### ISSUE THREAD

**Issue by Casper-lu** [cvat-ai/cvat#8399]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

When placing a normal rectangle shape box, quickly after creating the box hover over it and press Q to occlude the object. This will in many cases create a "ghost-box" that is shifted (usually) upwards. Hovering over where the box should be its still accessible, but visually shifted. Reloading the frame/jumping back and forth resolves the visual glitch.

### Context

Seems similar to #8271, box is thrown in similar way visually.

### Environment

```Markdown
Server version: 2.17.0
Core version: 15.1.2
Canvas version: 2.20.9
UI version: 1.65.0
```

**Comment by bsekachev** [comment]
Can't reproduce as described. Please, provide more information on steps to reproduce.
