### ISSUE TITLE
Attribute-annotation, shortcut key 9 not working anymore

### ISSUE THREAD

**Issue by Casper-lu** [cvat-ai/cvat#8400]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Using the Attribute annotation mode with a lot of attributes (e.g. using keys 0-9), updating the attribute works perfectly fine for key 0-8. But using key number 9 will not update the attribute. 

### Environment

```Markdown
Server version: 2.17.0
Core version: 15.1.2
Canvas version: 2.20.9
UI version: 1.65.0
```

**Comment by bsekachev** [comment]
Thanks for the report, I will check

**Comment by bsekachev** [comment]
Could not reproduce. Please, provide more information. Be sure that the shortcut setup in settings. 
![image](https://github.com/user-attachments/assets/feece121-930f-441a-a06f-eb94cebbd65f)

**Comment by Casper-lu** [comment]
Hmm weird, how do I access that menu? Was unable to find it!

Experienced the issue both on app.cvat.ai, as well as our locally hosted version. Had colleagues experience the same thing as well!

**Comment by bsekachev** [comment]
This is the latest develop branch. Not released yet, and not deployed on app.cvat.ai
We will release it maybe next week.
