### ISSUE TITLE
如何用GPU推理SAM模型

### ISSUE THREAD

**Issue by zhanghaihangandliuli** [cvat-ai/cvat#8402]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

在serverless目录下运行
nuctl deploy --project-name cvat --path "`pwd`/pytorch/facebookresearch/sam/nuclio/"  --file "`pwd`/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml" --platform local报错

### Expected Behavior

![img_v3_02ee_7356144e-8df6-40f1-b5c7-84cf8d23f10g](https://github.com/user-attachments/assets/900ebf47-4641-4d67-8f9f-0c29b7a5a46a)

### Possible Solution

出现```
nuctl.platform.docker (W) Failed to run container {"err": "stdout:\nd174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n\nstderr:\n", "errVerbose": "\nError - exit status 125\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\n\nCall stack:\nstdout:\nd174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n\nstderr:\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\nstdout:\nd174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n\nstderr:\n", "stdout": "d174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n", "stderr": ""}
24.08.31 13:31:40.265                     nuctl (W) Failed to create a function; setting the function status {"err": "Failed to run a Docker container", "errVerbose": "\nError - exit status 125\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\n\nCall stack:\nstdout:\nd174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11\ndocker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.\n\nstderr:\n\n    /nuclio/pkg/cmdrunner/shellrunner.go:114\nFailed to run a Docker container\n    /nuclio/pkg/platform/local/platform.go:905\nFailed to run a Docker container"}

Error - exit status 125
    /nuclio/pkg/cmdrunner/shellrunner.go:114

Call stack:
stdout:
d174c5116609d9dec9da8deb0c7a20dbf9a5b3b3fe7b130987993704e75f1d11
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.

stderr:

    /nuclio/pkg/cmdrunner/shellrunner.go:114
Failed to run a Docker container
    /nuclio/pkg/platform/local/platform.go:905
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:227
```

### Context

请问一下我该如何解决这个问题

### Environment

```Markdown
我的 NVIDIA 驱动版本为以下：

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A4000    Off  | 00000000:3B:00.0 Off |                  Off |
| 41%   43C    P8    16W / 140W |   8672MiB / 16376MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A4000    Off  | 00000000:AF:00.0 Off |                  Off |
| 41%   41C    P8    16W / 140W |      8MiB / 16376MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
NVIDIA Container Toolkit为如下：

(base) ubuntu@cvat:~/cvat-han$ dpkg -l | grep nvidia-docker
ii  nvidia-docker2                   2.14.0-1                                all          NVIDIA Container Toolkit meta-package

docker的daemon.json为：

{
  "runtimes": {
    "nvidia": {
      "path": "nvidia-container-runtime",
      "runtimeArgs": []
    }
  }
}

请问我该如何解决这个问题，万分感谢解答
```

**Comment by azhavoro** [comment]
> nvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted

This is not CVAT related issue please submit issue on nvidia-docker repo
