### ISSUE TITLE
Changing rego file doesn't take effect

### ISSUE THREAD

**Issue by ronjian** [cvat-ai/cvat#8403]
I tried to change rules, but it didn't take effect. My steps as below:
1. change ```default allow := false``` to ```default allow := true``` in cvat/apps/ima/rules/projects.rego
2. restart docker compose ```docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build```
3. I can verify this change taking effect by accessing ```host_ip:port/api/auth/rules```

But the "worker" role user still can't view any projects on the page.

**Comment by azhavoro** [comment]
In the case of getting the project list, the logic is a bit more complicated, it looks like you need to change these lines https://github.com/cvat-ai/cvat/blob/develop/cvat/apps/engine/rules/projects.rego#L85-L106.
