### ISSUE TITLE
Missing Label in CVAT After Labeling Two Objects

### ISSUE THREAD

**Issue by QuifaAbas** [cvat-ai/cvat#8407]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Here’s the task link where this issue occurs: https://app.cvat.ai/tasks/616492/jobs/710592

### Expected Behavior

When labeling two objects, I expected the first object to be labeled with '0' and the second with '1'. However, I only receive label '0' for both objects, and label '1' is missing. I'm not sure what the issue is.

### Possible Solution

I’ve already tried checking the label configuration, refreshing the browser, and restarting the task, but the issue remains. I’ve successfully labeled objects with '0' and '1' in previous tasks and exports without any issues. However, now it only gives me label '0'. This seems to be a problem with CVAT itself, as I haven’t changed my process, and it worked before. Could you please look into this issue? This is for a very important project.

### Context

This issue has significantly affected my ability to continue working on a critical project. I need to label objects with both '0' and '1', but now I can only apply label '0'. I am annotating vegetation and power lines, where vegetation is labeled as '0' and power lines as '1'. Previously, it applied the labels correctly, but now only label '0' is being applied. This is causing delays in my project, as I need both labels to properly categorize the objects. Resolving this is crucial for me to move forward with my work.

I’m attaching my task link for reference: https://app.cvat.ai/tasks/616492/jobs/710592

### Environment

```Markdown
I’m attaching my task link for reference: https://app.cvat.ai/tasks/616492/jobs/710592
```

**Comment by azhavoro** [comment]
In the task id you provided, all the images have annotations for both power lines and vegetation, so I can't understand what exactly the problem is. Please provide more detailed information.

**Comment by QuifaAbas** [comment]
Yes, I am annotating both vegetation and power lines. Vegetation is labeled as '0', and power lines are labeled as '1'. However, when I export the annotations in the YOLO 1.1 format, it only includes label '0', and label '1' is missing. I have attached my export file for your reference, and you can also check it to verify the issue.

[task_vegetation_line_detector_annotation_task_004_annotations_2024_04_28_03_17_00_yolo 1.1.zip](https://github.com/user-attachments/files/16914497/task_vegetation_line_detector_annotation_task_004_annotations_2024_04_28_03_17_00_yolo.1.1.zip)

**Comment by azhavoro** [comment]
Rotating bounding boxes are not supported in Yolo v1, use Yolo v8

**Comment by QuifaAbas** [comment]
I also tried using Yolo v8, but it only has the '0' label and not the '1' label.

I am attaching my task link for reference: 
[task_vegetation_line_detector_annotation_task_004_annotations_2024_04_28_03_17_00_yolov8 detection 1.0.zip](https://github.com/user-attachments/files/16949508/task_vegetation_line_detector_annotation_task_004_annotations_2024_04_28_03_17_00_yolov8.detection.1.0.zip)

**Comment by azhavoro** [comment]
As I mentioned earlier, your annotations contain rotated bounding boxes, so you need to use a format that supports them:
![image](https://github.com/user-attachments/assets/4d018389-593c-4a83-a981-6aeacf5ab7e6)
