### ISSUE TITLE
Determine the amount of free memory via CVAT

### ISSUE THREAD

**Issue by mdvdv** [cvat-ai/cvat#8421]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

Hello. Is there a way to determine the amount of free memory on the local server for self-hosted CVAT? Via Python SDK or alternative queries to CVAT. Thanks!

**Comment by bsekachev** [comment]
Hello. No, there is no way. The functionality is out of CVAT scope.
