### ISSUE TITLE
Toggle switch for mask point does not work anymore 

### ISSUE THREAD

**Issue by hasano20** [cvat-ai/cvat#8431]
For instance segmentation, I used to draw the first mask. For the second mask which would always overlap the first mask, I usually used CTRL to make the points of mask 1 appear to have a suitable overlap in annotation.

Now, the function of making the points of mask 1 appear is gone?! I can not turn the points on with CTRL, which makes the instance segmentation impossible for now. The only way to make the points appear is visible in figure 1 is to hover over it. But this does not work in draw mode. As soon as I enter the draw mode the points disappear, as seen in figure 2.

![Figure1](https://github.com/user-attachments/assets/2adb2dc6-809a-47ee-a54c-9e4f45519107)
![Figure2](https://github.com/user-attachments/assets/d3d00d95-cd7c-4f4d-b5ab-425b55991130)

Please have a look at it. I'm sure its just a small oneliner that must have been the reason to make the Toggle of the points not work with CTRL.

**Comment by bsekachev** [comment]
New default hotkey is Ctrl + A. 
You may customize it in a new version:
![image](https://github.com/user-attachments/assets/c9bd435a-b68e-4a04-92eb-7f270c24cfeb)

**Comment by hasano20** [comment]
Ah thanks a lot!
