### ISSUE TITLE
Unable to upload annotations in Datumaro format. What RLE format is required for uploading annotations?

### ISSUE THREAD

**Issue by hermda02** [cvat-ai/cvat#8432]
I am attempting to upload annotations created by my own segmentation neural network due to a previously closed issue (#8182 ). As such I've annotated with my own serverless function within CVAT and have downloaded the annotations in the Datumaro format as a template for my own annotations.

The issue comes from a lack of transparency of what RLE format is required for Datumaro formatted annotations. As such I receive the following error from CVAT: 
`cvat.apps.dataset_manager.bindings.CvatImportError: Image 0: can't import annotation #0 (mask): Invalid RLE mask representation`

The downloaded file, which when re-uploaded to CVAT works fine, though it is not clear what format the RLE comes out in. The attached file shows that the output RLE format comes in a string of characters instead of a list as is required by other parts of CVAT. Any hint towards what format is required or which part of the code-base I should look in would be helpful.

[default.json](https://github.com/user-attachments/files/16965739/default.json)

**Comment by zhiltsov-max** [comment]
Hi, explained here: https://github.com/cvat-ai/cvat/issues/6487#issuecomment-1640097518
