### ISSUE TITLE
Persistent Export Issues: COCO to YOLO and Direct YOLO Formats

### ISSUE THREAD

**Issue by svignesh007** [cvat-ai/cvat#8444]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1.Prepare the Data:
Ensure you have a dataset in COCO format that includes polygonal classifications.

2.Open CVAT:
Launch the CVAT application where you have your dataset loaded.

3.Attempt COCO to YOLO Conversion:
Navigate to the export settings or tools.
Select the option to convert annotations from COCO to YOLO format.
Execute the conversion process.

4.Verify Polygonal Classification:
After conversion, check the resulting YOLO annotations.
Verify if the polygonal classifications are preserved or correctly formatted.

5.Attempt Direct YOLO Export:
In CVAT, select the direct YOLO format export option.
Execute the export process and save the annotations.

6.Check Annotation Accuracy:
Open the exported YOLO annotations.
Verify if the annotations are accurate and properly formatted.

### Expected Behavior

1.COCO to YOLO Conversion:
The resulting YOLO annotations do not include correct polygonal classifications.
2.Direct YOLO Export:
The exported annotations are not properly formatted or are incorrect.

### Possible Solution

Double-checked the configuration settings for COCO to YOLO conversion and direct YOLO export to ensure they are correctly set.

### Context

Impact on Workflow: The inability to properly convert annotations from COCO to YOLO format and issues with direct YOLO export are hindering our ability to use these annotations for training our models. This delays our development process and affects project timelines.

Objective: Our goal is to obtain properly formatted YOLO annotations from COCO data, including accurate polygonal classifications and proper bounding box annotations. These annotations are crucial for the training and evaluation of our object detection models.

Current Situation: We have tried multiple troubleshooting steps, including restarting systems, but the issue remains unresolved.

### Environment

```Markdown
CVAT Version : 10.0.19045.4780
```

**Comment by bsekachev** [comment]
>1.COCO to YOLO Conversion:
The resulting YOLO annotations do not include correct polygonal classifications.
2.Direct YOLO Export:
The exported annotations are not properly formatted or are incorrect.

Please, be more specific. We can't work with the information provided. 

> CVAT Version : 10.0.19045.4780

The latest CVAT version is 2.18. I have no idea where you received CVAT v10 ..

**Comment by zhiltsov-max** [comment]
It would be very helpful to see the actual problems in the exported annotations. There are several YOLO formats available at the moment. Make sure you're using the one that supports polygons - [YOLOv8 Segmentation](https://docs.ultralytics.com/datasets/segment/).
