### ISSUE TITLE
Find a remote project

### ISSUE THREAD

**Issue by leeeeeeeeeemon** [cvat-ai/cvat#8452]
I was preparing photos for training the yolo neural network. 
I had a project where I spent 3 months working on object selection.

This project suddenly disappeared, or someone deleted it, can you tell me how to restore this project?

**Comment by klakhov** [comment]
Hi @leeeeeeeeeemon, are you using local cvat or our platform `app.cvat.ai`?
Please provide more info about the user/project you are looking for.

**Comment by leeeeeeeeeemon** [comment]
> Hi @leeeeeeeeeemon, are you using local cvat or our platform `app.cvat.ai`? Please provide more info about the user/project you are looking for.

Hi  @klakhov 
I was using https://www.cvat.ai/ and someone who had access to my account deleted a project with a photo, I don't remember the exact name but it was deleted on September 18, my login is afrAdmin.

**Comment by azhavoro** [comment]
Hello

We analyzed the logs and found that only 1 project owned by `afrAdmin` user was deleted: project_id 148723 was deleted by the afrAdmin user himself on 2024-09-16 13:22:24, this action cannot be undone.
