### ISSUE TITLE
cvat-vector deployment crashing on a fresh Kubernetes deployment

### ISSUE THREAD

**Issue by RedrumSherlock** [cvat-ai/cvat#8455]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. git clone the latest develop branch of cvat
2. follow the instruction on https://docs.cvat.ai/docs/administration/advanced/k8s_deployment_with_helm/#with-overrides to install the helm chart on Google Kubernetes Engine clusters 
3. Found that all the other deployments are running properly, but the cvat-vector deployment pods are crashing, with the following error messages

`2024-09-18T19:16:12.808567Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10                                                                                                                                                                │
│ 2024-09-18T19:16:12.808875Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,lapin=info,kube=info"                                                                              │
│ 2024-09-18T19:16:12.809073Z  INFO vector::app: Loading configs. paths=["/etc/vector"]                                                                                                                                                                                       │
│ 2024-09-18T19:16:12.809609Z ERROR vector::cli: Configuration error. error=No sources defined in the config.                                                                                                                                                                 │
│ 2024-09-18T19:16:12.809623Z ERROR vector::cli: Configuration error. error=No sinks defined in the config.                                                                                                                                                                   │
│ Stream closed EOF for cvat/cvat-vector-0 (vector)                                                                                 `

### Expected Behavior

All the deployments would start correctly

### Context

Since cvat-vector is down, when I am trying to create a superuser ,I got the following error and was not able to do it. It looks the superuser creation is dependent on the cvat-vector instance. Thus I am not able to use the system at all.

2024-09-18 18:33:11: exception: An error occurred while sending events: HTTPConnectionPool(host='cvat-vector', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c03a09bd330>: Failed to establish a new connection: [Errno 111] Connection refused'))

### Environment

```Markdown
Kuberentes on GKE
Cluster version: 1.28.13
Node OS image: Container-Optimized OS with containerd (cos_containerd)
```

**Comment by azhavoro** [comment]
Please make sure that `cvat-vector-config` is correctly created and vector config file from is mounted into vector container.
What is output of `kubectl exec <your-release-name>-vector-0 -- cat /etc/vector/vector.toml` ?
