### ISSUE TITLE
Difficult to grab rotation handle of smaller shape when label overlaid on a larger label

### ISSUE THREAD

**Issue by JuliusLin** [cvat-ai/cvat#8456]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

If there are multiple lable shapes overlaid, it is very cumbersome to use mouse cursor to grab the rotation handle of the smaller shape, once I try to grab it, the focus goes to the larger label. 
To workaround I've to put larger shape into deeper layer by press + key while focus on it, then set the visual layer higher, then I'll be able to rotate ithe label, the back-and-force of adjusting this steps make productivity very slow.

### Expected Behavior

I'd like to able to grab the rotation handle of the smaller label directly without losing focus to the larger label overlaid at same area.

**Comment by bsekachev** [comment]
> focus goes to the larger label

Hold `Ctrl` to keep focus on selected object
