### ISSUE TITLE
cvat secondary development

### ISSUE THREAD

**Issue by zhanghaihangandliuli** [cvat-ai/cvat#8461]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

May I ask if cvat can be used for local secondary development under Windows 10? If so, what tools do I need to download, such as vscode, pyhton3.8, postgreSQL, etc. Do I need to download docker?

### Describe the solution you'd like

May I ask if cvat can be used for local secondary development under Windows 10? If so, what tools do I need to download, such as vscode, pyhton3.8, postgreSQL, etc. Do I need to download docker?

**Comment by klakhov** [comment]
Hi, I've answered your question in #8427, please do not make duplicates
