### ISSUE TITLE
Annotations have dissapeared from a large pre-annotated dataset

### ISSUE THREAD

**Issue by ghuser72** [cvat-ai/cvat#8462]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Go to projects
2. Open an already worked-on annotation task
3. Annotations are gone

### Expected Behavior

I expect to see the annotations in the task, but most have disappeared. 

### Context

I need to urgently retrieve the annotations, would there be any way to restore the data? There is no export from before the annotations were lost.

**Comment by klakhov** [comment]
Hi @ghuser72 , are you using local cvat or our platform app.cvat.ai?
Please provide more info about the user/project you are looking for.
