### ISSUE TITLE
In the server, after modifying the CVAT backend code, how can I make it take effect?

### ISSUE THREAD

**Issue by zhanghaihangandliuli** [cvat-ai/cvat#8463]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

In the server, after modifying the CVAT backend code, how can I make it take effect?

### Expected Behavior

In the server, after modifying the CVAT backend code, how can I make it take effect?

### Possible Solution

In the server, after modifying the CVAT backend code, how can I make it take effect?

### Context

In the server, after modifying the CVAT backend code, how can I make it take effect?

**Comment by klakhov** [comment]
Hi, it depends on your cvat env. If you are running docker, you need to rebuild containers. If you are running development environment you need to restart server processes in vscode

**Comment by azhavoro** [comment]
I believe the question has been answered.
