### ISSUE TITLE
CVAT not starting due to timeout error wait-for-it.sh: waiting for cvat_db:5432 without a timeout

### ISSUE THREAD

**Issue by 4BD0U** [cvat-ai/cvat#8464]
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1- Set the CVAT_HOST environment variable:
export CVAT_HOST=MY-IP-ADDRESS

2- Run the following command to bring up the containers:
docker compose up -d

### Context

Hello,

I'm encountering an issue where CVAT is not starting on my PC. It seems to be stuck with the following error message:
wait-for-it.sh: waiting for cvat_db:5432 without a timeout

I have already tried restarting the application and checking my Docker setup, but the problem persists. It looks like the database connection is timing out, and CVAT is unable to initialize properly.

Has anyone else experienced this issue or knows how to resolve it? Any guidance or advice would be greatly appreciated.

### Environment

```Markdown
OS: Ubuntu 20.04
Docker version: 27.3.1, build ce12230
CVAT version: v2.19.0
```

**Comment by azhavoro** [comment]
Any logs from cvat_db?

**Comment by 4BD0U** [comment]
Thank you for your response! After further investigation, I realized the issue was likely caused by a problem with my local setup. I decided to reinstall Ubuntu on my machine, and after doing so, the issue no longer occurs. Everything seems to be working fine now. Apologies for the confusion, and thank you again for your time and support!
