### ISSUE TITLE
Project doesnt create when restoring from backup

### ISSUE THREAD

**Issue by boninale** [cvat-ai/cvat#8469]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

- Backed up previous project from another account as a .zip archive
- Tried to create a project from backup on other account

### Expected Behavior

Project created after a loading time

### Context

Return following message (cf image) but even after waiting a while and refreshing the page the project isnt created. The dataset isnt very big (75 images + 38 annotations)
<img width="147" alt="Capture" src="https://github.com/user-attachments/assets/d46275bb-fddc-4452-8888-036463ac3b33">

### Environment

```Markdown
CVAT online app
```

**Comment by azhavoro** [comment]
Please provide steps to reproduce

**Comment by boninale** [comment]
Backed up the projects on account 1 using default settings and downloaded backup.zip
<img width="329" alt="image" src="https://github.com/user-attachments/assets/b489c6c5-2bc6-4405-ac0e-193f6eed7c0e">
<img width="203" alt="image" src="https://github.com/user-attachments/assets/2ae2e549-5288-402d-8de5-15966f57d0a9">

Then from account 2 : Projects > Restore from backup and dropped the downloaded backup.zip archive
<img width="246" alt="image" src="https://github.com/user-attachments/assets/57c5cde8-3de2-4e55-b9fb-61038a8cc213">

Received the message previously shown but nothing appears in the "Requests" or "Project" tab even after waiting and/or refreshing the page 

New behavior : Received the following error message when logging out of account 2 :
<img width="142" alt="image" src="https://github.com/user-attachments/assets/6b0714a7-0ac5-4332-b826-d46135ed07ad">

**Comment by boninale** [comment]
For more context : the project contains one segmentation task with 77 images, about half of them are annotated

**Comment by azhavoro** [comment]
I'll close the issue as a duplicate, it's not related to restoring a backup, there are a few issues about it 
https://github.com/cvat-ai/cvat/issues/7288
https://github.com/cvat-ai/cvat/issues/8153
