### ISSUE TITLE
Issue in COCO format

### ISSUE THREAD

**Issue by Sandesh-Rprocess** [cvat-ai/cvat#8470]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Logged in Cvat.ai platform using credentials
2. Created & completed task using instruction.
3. Exported Task in 3 different types of output format- (CVAT1.1, COCO & COCO keypoints)

Issue: Previously, we worked on the CVAT platform and downloaded the COCO format multiple times according to the client’s requirements. As shown in the attached screenshot, both are in COCO format. However, in the past, we were unable to find 'counts' in the segmentation, which was a key requirement for the client. Recently, we downloaded the same format and shared it with the client.
![image](https://github.com/user-attachments/assets/a6beeb4a-7646-4186-b292-26ab9c7fe1d7)
![image](https://github.com/user-attachments/assets/ba5938d5-15cc-40aa-be1f-ee905fe34b71)

### Expected Behavior

We have attached two different COCO formats of the same project. Previously, in segmentation, we were unable to find 'counts,' which was the exact requirement of our client. Recently we downloaded the same segmentation format, and it now starts with the word 'counts' in curly brackets: segmentation: {"counts": [1338192, 2]. We have also attached the two COCO format outputs.
[Archive-1-COCO.zip](https://github.com/user-attachments/files/17124858/Archive-1-COCO.zip)
[Batch 4_coco.zip](https://github.com/user-attachments/files/17124875/Batch.4_coco.zip)

### Possible Solution

I kindly request you to review both formats and suggest how we can obtain the required output format or how we can rectify this issue.

**Comment by zhiltsov-max** [comment]
Hi, 

In the COCO instances (object detection) format, the segmentation field [can be of 2 types](https://cocodataset.org/#format-data):
- RLE: {"size": [w, h], "counts": [<a list of rle numbers>]}
- One or more polygons: [ [x1, y1, x2, y2, ...], ... ] 

CVAT also uses the second form with the [ [ ] ] value to export bounding boxes.

If you want to have RLEs in the exported annotations, you need to draw masks or convert polygons to masks in CVAT before export. If you need to convert already exported dataset, consider [using Datumaro for this](https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/coco.html#export-to-coco):
```
datum convert -if coco -i <path/to/dataset> -f coco -o <output/dir> -- --segmentation-mode "mask"
```
