### ISSUE TITLE
Solo Plan vs Team Plan

### ISSUE THREAD

**Issue by jw8huang** [cvat-ai/cvat#8478]
I signed up for the Solo plan, at $33 per month, since March/2024. I used both the online version and the local container version on and off and just recently came back to the local version (with docker).  I can do annotations and save the results, with images, without any issues.  While trying to incorporate SAM segmentation feature, I broke the local version, and can't get it to work again?  Meanwhile, I started using the online version, but when I tried to export the annotated data, with "Save images", it won't let me, and a popup is sending me to an Upgrade to Team area? Can I just stay with my $33 Solo plan for now? Very confused with CVAT's multi-plan descriptions! Help!

**Comment by azhavoro** [comment]
Please use support@cvat.ai for such questions
