### ISSUE TITLE
"Export Dataset" exporting a subset of full dataset only

### ISSUE THREAD

**Issue by margauxf** [cvat-ai/cvat#8483]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

We have tried several approaches:

- exporting the full project
- exporting the task
- exporting the job

Every time, only a fraction of the images and annotations are exported. 

1. Go to the project/task/job of interest
2. Click on the drop down three dots
3. Select `Export dataset` / `Export task dataset` / `Export annotations`. 
4. Select COCO format. Note we have tried both with and without images.
5. Under the `Requests` tab, download the dataset when ready.

When unzipping the download, only a fraction (< 1/3) of the annotations and corresponding images are present.

### Expected Behavior

We expect 100% of the annotations (and associated images if also exported) to be included.

### Environment

```Markdown
Team plan.
```

**Comment by zhiltsov-max** [comment]
Hi, if you experience this problem at app.cvat.ai and you have a subscription, please contact us [here (cvat.ai / contact us)](https://youtrack.cvat.ai/form/447d9c98-ab4b-466e-bf9d-004f01b22f73) instead. Please provide more information so we could help you with the issue.
