### ISSUE TITLE
Convert job type from annotation to ground_truth

### ISSUE THREAD

**Issue by bhoo-git** [cvat-ai/cvat#8486]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

When I upload a task with the segment_size attribute, I can create multiple jobs for a task. However, I am unable to delete the jobs because their type is set to annotations. 

### Describe the solution you'd like

I either would like to be able to delete jobs that are annotations, or have the ability to change the job type from annotation to ground_truth in order to delete some jobs from a task.

### Describe alternatives you've considered

the UI, cvat SDK, and REST API all did not work.

**Comment by bsekachev** [comment]
You can't delete annotations jobs by design.
