### ISSUE TITLE
Can't build SiamMask and TransT functions

### ISSUE THREAD

**Issue by midnightdim** [cvat-ai/cvat#8490]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I'm encountering an issue where building automated annotation functions (SiamMask and TransT) in CVAT gets stuck in the "building" state. Below are the steps I followed and the output logs.

**Steps to Reproduce:**
1. Installed CVAT locally using WSL 2 and Docker, following the installation instructions.
2. CVAT runs fine, and I can annotate videos.
3. Tried building automated annotation functions (SiamMask, TransT) using:
`./serverless/deploy_cpu.sh serverless/pytorch/foolwood/siammask/`

Both SiamMask and TransT get stuck in the "building" state. Here's the console output for SiamMask:

> 24.09.30 21:28:55.948 (I)                     nuctl Project created {"Name": "cvat", "Namespace": "nuclio"}
> Deploying pytorch/foolwood/siammask function...
> 24.09.30 21:28:56.094 (W)            nuctl.platform MaxWorkers is deprecated and will be removed in v1.15.x, use NumWorkers instead
> 24.09.30 21:28:56.192 (I)                     nuctl Deploying function {"name": "pth-foolwood-siammask"}
> 24.09.30 21:28:56.193 (I)                     nuctl Building {"builderKind": "docker", "versionInfo": "Label: 1.13.13, Git commit: 028989fe9d3fec47692e4a1384ac42267a8b7e0b, OS: linux, Arch: amd64, Go version: go1.21.13", "name": "pth-foolwood-siammask"}
> 24.09.30 21:28:56.329 (I)                     nuctl Staging files and preparing base images
> 24.09.30 21:28:56.393 (W)                     nuctl Using user provided base image, runtime interpreter version is provided by the base image {"baseImage": "ubuntu:2a0.04"}
> 24.09.30 21:28:56.454 (I)                     nuctl Building processor image {"registryURL": "", "taggedImageName": "cvat.pth.foolwood.siammask:latest"}
> 24.09.30 21:28:56.454 (I)     nuctl.platform.docker Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.13.13-amd64"}
> 24.09.30 21:28:59.486 (I)     nuctl.platform.docker Pulling image {"imageName": "quay.io/nuclio/uhttpc:0.0.1-amd64"}
> 24.09.30 21:29:02.353 (I)            nuctl.platform Building docker image {"image": "cvat.pth.foolwood.siammask:latest"}

It halts at this point. When accessing http://localhost:8070/projects/cvat/functions, I see the functions stuck in the "building" state, and the build log shows nothing.

Found somewhat similar issues:
https://github.com/cvat-ai/cvat/issues/3059
https://github.com/cvat-ai/cvat/issues/4475

Followed the suggestions from the first one (adding port and IP address into SiamMask function.yaml), but it didn't solve the problem.

### Expected Behavior

SiamMask and TransT functions should be deployed successfully and appear in the AI Tools section of the CVAT annotation UI.

### Environment

```Markdown
Docker Desktop 4.34.2 (167172) on Windows 10
CVAT:
Server version: 2.20.0
Core version: 15.2.0
Canvas version: 2.20.9
UI version: 1.66.0
```

**Comment by azhavoro** [comment]
Please try to run the build with the verbose option and attach a full log. If the build process is running, it does not mean that the function container cannot be built. I would suggest waiting for completion, it can't continue forever anyway
