### ISSUE TITLE
I created a Cvat account but I did not receive the verification email 

### ISSUE THREAD

**Issue by aerngren** [cvat-ai/cvat#8504]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

I can see that people hade had this issue but no solution i can do
// Adam

**Comment by bsekachev** [comment]
Email?

**Comment by aerngren** [comment]
adam_erngren@hotmail.com

**Comment by bsekachev** [comment]
You may login now

**Comment by Mickeyyyang** [comment]
> You may login now

hi, I try to invite someone to join my organization, and the upper-right corner of the WEB says that the email has been sent SUCCESSFULLY, but the other party has not received it. Why is this?

![2024-12-07_15-28](https://github.com/user-attachments/assets/d1ddfbb5-af20-4d82-b5aa-9285789538d3)

Best wishes for YOU.
