### ISSUE TITLE
Could not restore project backup

### ISSUE THREAD

**Issue by pavelorlovyeah** [cvat-ai/cvat#8508]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I am getting an error:
"Could not restore project backup.
KeyError: "There is no item named 'project.json' in the archive"

1. I create Backup Project and downloading it.
2. I'll unzip it and zip it immediately without any changes.
3. Click Import from backup and getting specified error.

Mac OS ventura 13.7

I am testing backup feature for possible changes in project (adding new tasks for example).
But even simple action without any changes in backup, just unzip/zip actions make it unusable for restore.

Thanks a lot for help.

**Comment by bsekachev** [comment]
Probably you have extra top level directory in new archive.

**Comment by pavelorlovyeah** [comment]
Thanks, everything is ok
