### ISSUE TITLE
Superuser login fails after updating docker desktop

### ISSUE THREAD

**Issue by prnr** [cvat-ai/cvat#8512]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

I created a new superuser account with [docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'], but the error 'Unable to log in with provided credentials' occurred. If I create a regular account, I can log in with that account.
If there's any change since the last login, it's about [1. downgraded the numpy version 2. updated the version of docker desktop to the latest version], but after you reboot the pc after that update, you've seen pulling the container when you use the command [docker compose -f docker-compose.yml -f components/serverless/docker-compose.yml up -d]. Is there a way to log in as a superuser? I want to back up data such as project/task/annotation.

This is the error message on browser console.

server-proxy.ts:467 
 
 POST http://localhost:8080/api/auth/login?org= 400 (Bad Request)
(Anonymous)	@	xhr.js:195
xhr	@	xhr.js:15
Jo	@	dispatchRequest.js:51
Promise.then		
_request	@	Axios.js:149
request	@	Axios.js:40
(Anonymous)	@	Axios.js:212
(Anonymous)	@	bind.js:5
login	@	server-proxy.ts:467
(Anonymous)	@	api-implementation.ts:106
apiWrapper	@	plugins.ts:43
await in apiWrapper		
login	@	api.ts:77
(Anonymous)	@	auth-actions.ts:102
(Anonymous)	@	index.js:16
t.<computed>	@	bindActionCreators.js:8
onSubmit	@	login-page.tsx:44
onFinish	@	login-form.tsx:112
onFinish	@	Form.js:73
(Anonymous)	@	useForm.js:855
Promise.then		
(Anonymous)	@	useForm.js:851
onSubmit	@	Form.js:130
Re	@	react-dom.production.min.js:54
Be	@	react-dom.production.min.js:54
(Anonymous)	@	react-dom.production.min.js:55
zo	@	react-dom.production.min.js:105
$o	@	react-dom.production.min.js:106
(Anonymous)	@	react-dom.production.min.js:117
uc	@	react-dom.production.min.js:274
Pe	@	react-dom.production.min.js:52
Vo	@	react-dom.production.min.js:109
qn	@	react-dom.production.min.js:74
Gn	@	react-dom.production.min.js:73

cvat-app.tsx:421 
 Unable to log in with provided credentials.
o	@	cvat-app.tsx:421
showErrors	@	cvat-app.tsx:431
componentDidUpdate	@	cvat-app.tsx:306
As	@	react-dom.production.min.js:261
_s	@	react-dom.production.min.js:260
ys	@	react-dom.production.min.js:259
(Anonymous)	@	react-dom.production.min.js:283
wc	@	react-dom.production.min.js:281
cc	@	react-dom.production.min.js:273
Wl	@	react-dom.production.min.js:127
(Anonymous)	@	react-dom.production.min.js:267
XMLHttpRequest.send		
(Anonymous)	@	xhr.js:195
xhr	@	xhr.js:15
Jo	@	dispatchRequest.js:51
Promise.then		
_request	@	Axios.js:149
request	@	Axios.js:40
(Anonymous)	@	Axios.js:212
(Anonymous)	@	bind.js:5
login	@	server-proxy.ts:467
(Anonymous)	@	api-implementation.ts:106
apiWrapper	@	plugins.ts:43
await in apiWrapper		
login	@	api.ts:77
(Anonymous)	@	auth-actions.ts:102
(Anonymous)	@	index.js:16
t.<computed>	@	bindActionCreators.js:8
onSubmit	@	login-page.tsx:44
onFinish	@	login-form.tsx:112
onFinish	@	Form.js:73
(Anonymous)	@	useForm.js:855
Promise.then		
(Anonymous)	@	useForm.js:851
onSubmit	@	Form.js:130
Re	@	react-dom.production.min.js:54
Be	@	react-dom.production.min.js:54
(Anonymous)	@	react-dom.production.min.js:55
zo	@	react-dom.production.min.js:105
$o	@	react-dom.production.min.js:106
(Anonymous)	@	react-dom.production.min.js:117
uc	@	react-dom.production.min.js:274
Pe	@	react-dom.production.min.js:52
Vo	@	react-dom.production.min.js:109
qn	@	react-dom.production.min.js:74
Gn	@	react-dom.production.min.js:73

### Environment

```Markdown
WSL2 Ubuntu 22.04
Docker desktop 4.33.1>4.34.2(docker engine 27.1.1>27.2.0)
GPU RTX4090
```

**Comment by bsekachev** [comment]
> POST http://localhost:8080/api/auth/login?org= 400 (Bad Request)

Please, check logs for `cvat_server` docker container.

**Comment by bsekachev** [comment]
Also, please provide available details in environment section. We do not know what version and where you are using.

**Comment by prnr** [comment]
> Also, please provide available details in environment section. We do not know what version and where you are using.

Server version: 2.21.0
Core version: 15.2.0
Canvas version: 2.20.9
UI version: 1.66.0

I installed a completely new cvat, and I'm still experiencing the same symptoms after restarting wsl (rebooting windows). None of it has changed the version this time.

**Comment by prnr** [comment]
I tried the following way in collaboration with Chadge P.T.
1. Docker Container Restart
2. Reset Administrator Password
3. Verifying Database Migration
4. Delete browser cache
5. Check environment variables again
6. Check Django User Account
7. Django Session Data Initialization
8. Redis Container Session Data Initialization

While doing the check, I confirmed that the account not in PostgreSQL db can log in (non-superuser account before reinstallation, subscription through web page), and the OPA log shows an error.

{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp: lookup cvat-server on 127.0.0.11:53: no such host","name":"cvat","plugin":"bundle","time":"2024-10-19T21:31:58Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.18.0.18:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2024-10-19T21:31:58Z"}



When I type http://localhost:8080/api/auth/rules in the web browser, the rules.tar file was downloadable, 
The results of Python manage.py health_check are as follows.

[2024-10-20 10:06:02,076] ERROR health-check: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
Traceback (most recent call last):
  File "/home/django/cvat/apps/health/backends.py", line 22, in check_status
    response.raise_for_status()
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/home/django/cvat/apps/health/backends.py", line 24, in check_status
    raise HealthCheckException(str(e))
health_check.exceptions.HealthCheckException: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
[2024-10-20 10:06:02,083] ERROR health-check: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
Traceback (most recent call last):
  File "/home/django/cvat/apps/health/backends.py", line 22, in check_status
    response.raise_for_status()
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/home/django/cvat/apps/health/backends.py", line 24, in check_status
    raise HealthCheckException(str(e))
health_check.exceptions.HealthCheckException: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
Cache backend: default   ... working
Cache backend: media     ... working
DatabaseBackend          ... working
DiskUsage                ... working
MemoryUsage              ... working
OPAHealthCheck           ... unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles

**Comment by prnr** [comment]
It didn't work out, so I solved it by proceeding to restore (https://docs.cvat.ai/docs/administration/advanced/backup_guide/) after backup. There seems to be no problem with cvat_db / cvat_server itself. The exact cause is unknown, but it is presumed that the docker image was deleted or built was incomplete.
