### ISSUE TITLE
av 9.2.0 compatibility

### ISSUE THREAD

**Issue by Krishna-UGit** [cvat-ai/cvat#8517]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

The av 9.2.0 is not compatible with the latest python versions. I tried downgrading the version to 3.11 but still doesn't help.

**Comment by azhavoro** [comment]
https://docs.cvat.ai/docs/contributing/development-environment/

CVAT currently supports python 3.10. If you are interested in supporting 3.11 and later versions, we are always open to contributions
