### ISSUE TITLE
Deleting .sst Files in Docker Volume

### ISSUE THREAD

**Issue by seasenzzr000** [cvat-ai/cvat#8518]
Can the **.sst** files in the path be deleted? 
They are taking up too much disk space on the server. After deletion, will I need to rebuild the `Docker Compose`? 
What are the console commands for that?

`/var/lib/docker/volumes/cvat_cvat_cache_db/_data/db`

```shell
286G    cvat_cvat_cache_db
50G     cvat_cvat_data
6.3G    cvat_cvat_db
58G     cvat_cvat_events_db
43M     cvat_cvat_inmem_db
28K     cvat_cvat_keys
12K     cvat_cvat_letsencrypt
1.4G    cvat_cvat_logs
2.2T    cvat_cvat_share
``` 
```shell
000220.sst  001701.sst  003103.sst  004111.sst  005323.sst  006072.sst  
008356.sst  009402.sst  010040.sst  011243.sst  012069.sst  012857.sst  
013580.sst  013924.sst  014274.sst  014643.sst  000263.sst  001713.sst  
003104.sst  004129.sst  005324.sst  006074.sst  008372.sst  009405.sst 
LOG.old.1726067292594497
LOG.old.1726115966257893
LOG.old.1726115966261954
LOG.old.1726226367676262
MANIFEST-008661
OPTIONS-002555
OPTIONS-008663
```

``` shell
/*/archive/
```

I only pasted a portion of the files in the directory; there are simply too many, and they are taking up a lot of storage space, which is already affecting the normal operation of CVAT annotation work.

**Comment by seasenzzr000** [comment]
> > 是否可以删除路径中的 .sst 文件？
> 
> 简短的回答：不，您不应该手动删除卷中的任何数据。

@bsekachev thanks.How can I delete them? Will deleting these files affect the normal operation of CVAT?

**Comment by bsekachev** [comment]
> Will deleting these files affect the normal operation of CVAT?

Yes.

**Comment by seasenzzr000** [comment]
> > 是否可以删除路径中的 .sst 文件？
> 
> 简短的回答：不，您不应该手动删除卷中的任何数据。

If I want to delete these .sst files, how should I proceed? They are taking up too much hard drive storage.

**Comment by azhavoro** [comment]
> > > 是否可以删除路径中的 .sst 文件？
> > 
> > 
> > 简短的回答：不，您不应该手动删除卷中的任何数据。
> 
> If I want to delete these .sst files, how should I proceed? They are taking up too much hard drive storage.

https://docs.docker.com/reference/cli/docker/volume/rm/

**Comment by seasenzzr000** [comment]
I have another question. How can I determine which of these SST files can be deleted without affecting CVAT? I have observed the growth over the past 3 hours, and these SST files have increased by a total of 15GB in storage. The impact on CVAT's performance is really significant.

Thank you so much for your help. This issue has been bothering me for a long time, and I hope it can be resolved.

 Once again, thank you! ;)

**Comment by seasenzzr000** [comment]
> 我还有另一个问题。如何确定哪些 SST 文件可以在不影响 CVAT 的情况下删除？我观察到过去 3 小时的增长，这些 SST 文件的存储空间总共增加了 15GB。对 CVAT 性能的影响确实很大。
> 
> 非常感谢您的帮助。这个问题困扰了我很久，希望能得到解决。
> 
> 再次感谢你们！;)

@azhavoro @bsekachev   plz help me. thaks!
