### ISSUE TITLE
Unable to access the cvat.ai website

### ISSUE THREAD

**Issue by Akashdip-N** [cvat-ai/cvat#8522]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Open the website and wait for it to load then will see this message.

<img width="1449" alt="Screenshot 2024-10-08 at 11 26 55 PM" src="https://github.com/user-attachments/assets/c0276a11-52f8-43f5-b5fc-d66a8d17429c">

### Expected Behavior

The website should have opened

**Comment by azhavoro** [comment]
Hello, this is a temporary issue that some users may encounter for a short time, we are working on a fix.
