### ISSUE TITLE
Delete an account from cvat.ai?

### ISSUE THREAD

**Issue by jasonmbrown** [cvat-ai/cvat#8526]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I cannot find any method to remove my account from the service. 

### Describe the solution you'd like

Please add a button in the settings to delete the currently logged in account.

**Comment by bsekachev** [comment]
Hello, please write to support@cvat.ai
