### ISSUE TITLE
User name change request

### ISSUE THREAD

**Issue by sgrude** [cvat-ai/cvat#8536]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I want to change my username so i need your assistance to do that, because there is no such option where i can do it my myself.
In cvat my current _username_ is __awais34__
And my email is : ss477127@gmail.com

### Describe the solution you'd like

I would like to have option to change my user name , or whereever i have used the name __awais34/awais__ to b changed.

### Describe alternatives you've considered

If you will not support me then i have to delete my account.

### Additional context

Looking forward to you response

**Comment by bsekachev** [comment]
Hello, changing the username is not possible.
