### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by w0rdb3ar3r** [cvat-ai/cvat#8541]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Expected Behavior

Installed it on a virtual machine, it works. I'm trying to connect via the network with another computer - it says "404 page not found"

CV_HOST=10.184.1.154

my docker-compose.yml:
 Copyright (C) 2018-2022 Intel Corporation
      2 #
      3 # SPDX-License-Identifier: MIT
      4 
      5 version: '3.3'
      6 
      7 services:
      8   cvat_db:
      9     container_name: cvat_db
     10     image: postgres:10-alpine
     11     restart: always
     12     environment:
     13       POSTGRES_USER: root
     14       POSTGRES_DB: cvat
     15       POSTGRES_HOST_AUTH_METHOD: trust
     16     volumes:
     17       - cvat_db:/var/lib/postgresql/data
     18     networks:
     19       - cvat
     20 
     21   cvat_redis:
     22     container_name: cvat_redis
     23     image: redis:4.0-alpine
     24     restart: always
     25     networks:
     26       - cvat
     27 
     28   cvat_server:
     29     container_name: cvat_server
     30     image: cvat/server:${CVAT_VERSION:-v2.2.0}
     31     restart: always
     32     depends_on:
     33       - cvat_redis
     34       - cvat_db
     35       - cvat_opa
     36     environment:
     37       DJANGO_MODWSGI_EXTRA_ARGS: ''
     38       ALLOWED_HOSTS: '*'
     39       CVAT_REDIS_HOST: 'cvat_redis'
     40       CVAT_POSTGRES_HOST: 'cvat_db'
     41       ADAPTIVE_AUTO_ANNOTATION: 'false'
     42       no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
     43       NUMPROCS: 1
     44     command: -c supervisord/server.conf
     45     labels:
     46       - traefik.enable=true
     47       - traefik.http.services.cvat.loadbalancer.server.port=8080
     48       - traefik.http.routers.cvat.rule=Host(`${CVAT_HOST:-localhost}`) &&
     49         PathPrefix(`/api/`, `/git/`, `/opencv/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)
     50       - traefik.http.routers.cvat.entrypoints=web
     51     volumes:
     52       - cvat_data:/home/django/data
     53       - cvat_keys:/home/django/keys
     54       - cvat_logs:/home/django/logs
     55     networks:
     56       - cvat
     57 
     58   cvat_utils:
     59     container_name: cvat_utils
     60     image: cvat/server:${CVAT_VERSION:-v2.2.0}
     61     restart: always
     62     depends_on:
     63       - cvat_redis
     64       - cvat_db
     65       - cvat_opa
     66     environment:
     67       CVAT_REDIS_HOST: 'cvat_redis'
     68       CVAT_POSTGRES_HOST: 'cvat_db'
     69       no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
     70     command: -c supervisord/utils.conf
     71     volumes:
     72       - cvat_data:/home/django/data
     73       - cvat_keys:/home/django/keys
     74       - cvat_logs:/home/django/logs
     75     networks:
     76       - cvat
     77 
     78   cvat_worker_default:
     79     container_name: cvat_worker_default
     80     image: cvat/server:${CVAT_VERSION:-v2.2.0}
     81     restart: always
     82     depends_on:
     83       - cvat_redis
     84       - cvat_db
     85       - cvat_opa
     86     environment:
     87       CVAT_REDIS_HOST: 'cvat_redis'
     88       CVAT_POSTGRES_HOST: 'cvat_db'
     89       no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
     90       NUMPROCS: 2
     91     command: -c supervisord/worker.default.conf
     92     volumes:
     93       - cvat_data:/home/django/data
     94       - cvat_keys:/home/django/keys
     95       - cvat_logs:/home/django/logs
     96     networks:
     97       - cvat
     98 
     99   cvat_worker_low:
    100     container_name: cvat_worker_low
    101     image: cvat/server:${CVAT_VERSION:-v2.2.0}
    102     restart: always
    103     depends_on:
    104       - cvat_redis
    105       - cvat_db
    106       - cvat_opa
    107     environment:
    108       CVAT_REDIS_HOST: 'cvat_redis'
    109       CVAT_POSTGRES_HOST: 'cvat_db'
    110       no_proxy: elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}
    111       NUMPROCS: 1
    112     command: -c supervisord/worker.low.conf
    113     volumes:
    114       - cvat_data:/home/django/data
    115       - cvat_keys:/home/django/keys
    116       - cvat_logs:/home/django/logs
    117     networks:
    118       - cvat
    119 
    120   cvat_ui:
    121     container_name: cvat_ui
    122     image: cvat/ui:${CVAT_VERSION:-v2.2.0}
    123     restart: always
    124     depends_on:
    125       - cvat_server
    126     labels:
    127       - traefik.enable=true
    128       - traefik.http.services.cvat-ui.loadbalancer.server.port=80
    129       - traefik.http.routers.cvat-ui.rule=Host(`${CVAT_HOST:-localhost}`)
    130       - traefik.http.routers.cvat-ui.entrypoints=web
    131     networks:
    132       - cvat
    133 
    134   traefik:
    135     image: traefik:v2.4
    136     container_name: traefik
    137     restart: always
    138     command:
    139       - '--providers.docker.exposedByDefault=false'
    140       - '--providers.docker.network=cvat'
    141       - '--entryPoints.web.address=:8080'
    142       - '--providers.file.directory=/etc/traefik/rules'
    143     # Uncomment to get Traefik dashboard
    144     #   - "--entryPoints.dashboard.address=:8090"
    145     #   - "--api.dashboard=true"
    146     # labels:
    147     #   - traefik.enable=true
    148     #   - traefik.http.routers.dashboard.entrypoints=dashboard
    149     #   - traefik.http.routers.dashboard.service=api@internal
    150     #   - traefik.http.routers.dashboard.rule=Host(`${CVAT_HOST:-localhost}`)
    151     ports:
    152       - 8080:8080
    153       - 8090:8090
    154     volumes:
    155       - /var/run/docker.sock:/var/run/docker.sock:ro
    156     networks:
    157       - cvat
    158 
    159   cvat_opa:
    160     container_name: cvat_opa
    161     image: openpolicyagent/opa:0.34.2-rootless
    162     restart: always
    163     networks:
    164       cvat:
    165         aliases:
    166           - opa
    167     volumes:
    168       - ./cvat/apps/iam/rules:/rules
    169     ports:
    170       - '8181:8181'
    171     command: run --server --addr :8181 --set=decision_logs.console=true /rules
    172 
    173 volumes:
    174   cvat_db:
    175   cvat_data:
    176   cvat_keys:
    177   cvat_logs:
    178 
    179 networks:
    180   cvat:

sudo docker logs traefik > traefik_logs.txt
time="2024-10-14T11:28:53Z" level=info msg="Configuration loaded from flags."
time="2024-10-14T11:28:53Z" level=error msg="Cannot start the provider *file.Provider: unable to read directory /etc/traefik/rules: open /etc/traefik/rules: no such file or directory"

Please help me

**Comment by w0rdb3ar3r** [comment]
and at start:
cvat@cvat:~/cvat$ sudo docker-compose up -d
WARNING: The no_proxy variable is not set. Defaulting to a blank string.
Creating network "cvat_cvat" with the default driver
Creating cvat_redis ... done
Creating cvat_opa   ... done
Creating cvat_db    ... done
Creating traefik             ... done
Creating cvat_worker_low     ... done
Creating cvat_utils          ... done
Creating cvat_worker_default ... done
Creating cvat_server         ... done
Creating cvat_ui             ... done

**Comment by azhavoro** [comment]
Is 10.184.1.154 the IP address of the host or the virtual machine? What network mode is used for the VM's network interface?
You will only get 404 if CVAT_HOST is different from the value in the HOST header in a request

**Comment by azhavoro** [comment]
Also if you are using docker compose with sudo, use it with the `-E` option: `suso -E docker compose ....`
