### ISSUE TITLE
Tag annotation not similar with Ground Truth

### ISSUE THREAD

**Issue by davy-blavette** [cvat-ai/cvat#8547]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I don't know why there's a difference between tags entered on a task and tags entered on ground truth. On GT you can add the GT tag, why not  (in case you don't know?!), but you no longer have the option of deleting it. Is there a particular reason for this or is it an oversight?

![image](https://github.com/user-attachments/assets/d38a8ebf-dfd9-46a1-ac19-b90762fec97c)
![image](https://github.com/user-attachments/assets/9d60c76f-c00b-484e-b622-b090c62c668d)

### Describe the solution you'd like

Add the possibility to delete with a cross

**Comment by klakhov** [comment]
Hi @davy-blavette,

If I understand correctly, in the first screenshot, you’re viewing the tag inside the ground truth (GT) job, and in the second screenshot, it's in a regular job. Ground truth annotations are separate from regular jobs, meaning they cannot be deleted or edited in regular jobs. This applies not only to tags but to all kinds of annotations.

GT annotations can only be viewed in review mode, and the purpose of this is to identify conflicts between regular annotations and ground truth. You can either create an issue for the annotator or switch back to standard mode to edit the regular annotations and resolve the conflict.

**Comment by davy-blavette** [comment]
Thanks @klakhov for your answer! 
I'm talking about the fact that adding a tag to the ground truth job doesn't make it easy to delete it at the moment because there's no cross like on a normal job, the first screen corresponds to the GT view... at the moment it's not very practical because you have to press SHIFT + N to delete the tag.

I also have another problem, but it's specific to my use, I add issues (in api mode) to the GT because it's generated automatically with the inference values, in input mode the review disappears so I don't have the information to change my tag, I spend my time switching between GT review and GT annotation tag which isn't very practical.

![image](https://github.com/user-attachments/assets/db369204-1c84-450b-af7e-73cb5e391517)
![image](https://github.com/user-attachments/assets/bb33fe64-05a5-4b73-b2b2-f7b69bfc6b08)

**Comment by klakhov** [comment]
Now I see, it seems in gt job we also dont have a cross, looks like a bug, I will look into this.

Also it seems we need to add some setting for tag annotation mode to show issues.

**Comment by klakhov** [comment]
Hi @davy-blavette,

I’ll be closing this issue since the main problem you reported (which was more of a bug) has now been resolved. If you still would like to request displaying issues in tag annotation mode, please feel free to open a new issue for that.
