### ISSUE TITLE
Pod liveness probes fail in some container environments because local ip not included in Allowed Hosts

### ISSUE THREAD

**Issue by sei-jmattson** [cvat-ai/cvat#8567]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Deploy cvat/server v2.21.1 in k8s with default values file
2. Check logs of server pod to see liveness probe attempts "http://10.x.x.x/api/server/about" and fails due to ip not included in Allowed Hosts

### Expected Behavior

liveness probe should work with defaults.

### Possible Solution

Automatically include pod ip in Allowed Hosts.
PR submitted.

**Comment by azhavoro** [comment]
ALLOWED_HOSTS is already set to `*` for the pod server https://github.com/cvat-ai/cvat/blob/develop/helm-chart/values.yaml#L41.
Could you please attach the logs?

**Comment by sei-jmattson** [comment]
Sure enough! Not sure how I missed that.
