### ISSUE TITLE
Unable to Connect to CVAT Server

### ISSUE THREAD

**Issue by svignesh007** [cvat-ai/cvat#8589]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Open the CVAT web interface.
Attempt to connect to the server.
Observe the pop-up message indicating connection issues.

### Expected Behavior

I expected to successfully connect to the CVAT server and access its functionalities without encountering error messages.

### Possible Solution

It may be related to the backend services (Database, Redis, Open Policy Agent) not running properly. Checking their statuses and ensuring they are all operational might resolve the issue.

### Context

This issue is preventing me from using CVAT for my project. I need to access the annotation tools to proceed with my work.

### Environment

```Markdown
- Git version - git version 2.34.1
- Docker version - Docker version 27.3.1, build ce12230
- OS - Ubuntu 22.04.4 LTS
- Windows system - X11
```

**Comment by azhavoro** [comment]
any logs?

**Comment by svignesh007** [comment]
Its solved @azhavoro

**Comment by svignesh007** [comment]
I cleared the storage in the system and its now good thank you for your kind response
