### ISSUE TITLE
Wrong skeleton structure issue when trying to load a svg skeleton file

### ISSUE THREAD

**Issue by manu13008** [cvat-ai/cvat#8592]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce
Hi folks, 

I created a skeleton in a project using CVAT self hosted version and then exported it into a svg file.

Then I created a new project and tried to upload my previous svg file as a new skeleton but I got "Wrong skeleton structure" error.

Do you have any idea how to fix this issue ?

Thanks a lot

![Error](https://github.com/user-attachments/assets/c54f6ac3-8c7f-4337-97aa-26156c31fc65)

### Expected Behavior

The upload function should load my svg file as a new skeleton

### Environment

CVAT installed on Windows laptop
Ubuntu and Docker Desktop

**Comment by bsekachev** [comment]
Please, share a file you are trying to upload and fill environment section

**Comment by manu13008** [comment]
Here is my svg file

![7ae83f5c-6a90-4990-b2d5-0bcbd832ccdd](https://github.com/user-attachments/assets/4b426251-c556-4d80-adb7-27c46af30b59)

Thanks !
