### ISSUE TITLE
No shortcut for 'done'

### ISSUE THREAD

**Issue by lordhjx** [cvat-ai/cvat#8595]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

As I want to find a shortcut for 'done' in poly line, there shows press 'undefined' for done, and I cannot find a measure to set shortcut for 'done' in the settings.

**Comment by bsekachev** [comment]
Already fixed in the latest release
