### ISSUE TITLE
Сan't export 60Gb+ dataset

### ISSUE THREAD

**Issue by leppsey** [cvat-ai/cvat#8600]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Start exporting the dataset.  
2. Encounter an error: Moved to FailedJobRegistry, due to AbandonedJobError, at 2024-10-28 11:26:05.902082

### Environment

```Markdown
Server version: 2.22.0

Core version: 15.2.0

Canvas version: 2.20.9

UI version: 1.66.1
```

**Comment by bsekachev** [comment]
Default timeout is 4 hours. Is it enough to export your dataset?

**Comment by bsekachev** [comment]
Also, please, make sure workhorse process was not killed because of out of memory issue.

**Comment by leppsey** [comment]
> Default timeout is 4 hours. Is it enough to export your dataset?

How can I change timeout?

**Comment by bsekachev** [comment]
https://github.com/cvat-ai/cvat/blob/88e8db0b373d2794eb667ceb13859440593c5cc0/cvat/settings/base.py#L298

Update the field, **rebuild** docker images and restart containers. 
To rebuild images add `-f docker-compose.yml.dev` and `--build` options
Basically: `docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

When containers started you may make sure that changes are applied by going inside and checking the `base.py` file:
`docker exec -it cvat_server bash`
`cat cvat/settings/base.py`

**Comment by leppsey** [comment]
I have a new problem. The dataset was exported, and I clicked download. After about 30% of the download, the speed drops to 0.

**Comment by leppsey** [comment]
> https://github.com/cvat-ai/cvat/blob/88e8db0b373d2794eb667ceb13859440593c5cc0/cvat/settings/base.py#L298
> 
> Update the field, **rebuild** docker images and restart containers. To rebuild images add `-f docker-compose.yml.dev` and `--build` options Basically: `docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`
> 
> When containers started you may make sure that changes are applied by going inside and checking the `base.py` file: `docker exec -it cvat_server bash` `cat cvat/settings/base.py`

I have a new problem. The dataset was exported, and I clicked download. After about 30% of the download, the speed drops to 0.

**Comment by leppsey** [comment]
![image](https://github.com/user-attachments/assets/71fae31c-58d3-48c7-aaae-e46e20b1e391)
