### ISSUE TITLE
Multiple Object Selection & Copy/Paste

### ISSUE THREAD

**Issue by matheusguzman** [cvat-ai/cvat#8603]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Describe the solution you'd like

Hi everyone!

My suggestion of feature is the functionality of selecting multiple object shapes, and being able to copy/paste the selected shapes between frames.
Let´s assume i have a picture with 10 annotations, but i have a similar picture i need to annotate, Being able to copypaste multiple objects selected would rapidly fasten the process of manual annotations!
We do use the automatic annotation, but for new labels this process would be really helpful!

Thanks in advance!

### Describe alternatives you've considered

Already tried the Propagate feature, but this one too only let´s you propagate one object at a time to the next frames.

**Comment by bsekachev** [comment]
#2340
