### ISSUE TITLE
Change Stage from complete to annotation

### ISSUE THREAD

**Issue by seyedalicheraghi** [cvat-ai/cvat#8605]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I have a CVAT project containing 100 tasks that has already labeled. Now, I need to draw bounding boxes around a new object in these tasks. While I can manually change the status of each task from "completed" to "annotation," is there a more efficient way to do this for all tasks at once?

### Describe the solution you'd like

A python code that enable me to change all at once

**Comment by bsekachev** [comment]
You may write a simple Python script using CVAT SDK. There is no way to do it in the graphical interface
