### ISSUE TITLE
Add multiple selectable attribute values

### ISSUE THREAD

**Issue by huayecaibcc** [cvat-ai/cvat#8613]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

Currently, the label attributes of cvat do not support multiple options. For example, checkbox can only select true or false, and radio can select only one value from multiple values. However, when labeling, you often need to select multiple values. For example, I have a label `chart`, and one of its attributes is `chart_type`, which contains multiple values (line, bar, pie, etc.). Some charts may contain multiple attributes at the same time. In this case, multiple selections are required. The current possible solution is to make each value a checkbox attribute, but this will increase the complexity of the attribute list.

### Describe the solution you'd like

Add an attribute that can select multiple values

**Comment by bsekachev** [comment]
#7500
