### ISSUE TITLE
Canva is busy error

### ISSUE THREAD

**Issue by DelGideonstar** [cvat-ai/cvat#8619]
Please how I can resolve this, attached is a screenshot of the error

![image (69)](https://github.com/user-attachments/assets/33feaa89-b4d0-437f-94c5-dbb8c957bb04)

**Comment by DelGideonstar** [comment]
@nmanovic

**Comment by nmanovic** [comment]
@DelGideonstar , could you please provide a scenario to reproduce the issue? Have you met it on your self-hosted version?

**Comment by DelGideonstar** [comment]
I'm using the free plan.

It happens randomly, mostly when the tool is autosaving. At the moment, the tool is fine. When such a pop-up appears, when you refresh the page, everything goes back to normal.

**Comment by bsekachev** [comment]
Please, provide the  task ID, we cannot identify your account.

**Comment by bsekachev** [comment]
We updated app.cvat.ai. I believe the issue shall be fixed now. Please, check.

**Comment by DelGideonstar** [comment]
Thanks for fixing that, we have another issue whereby annotations are not
saving.
