### ISSUE TITLE
Can't download 50Gb+ dataset

### ISSUE THREAD

**Issue by leppsey** [cvat-ai/cvat#8620]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

 The dataset was exported, and I clicked download. After about 30% of the download, the speed drops to 0.
![image](https://github.com/user-attachments/assets/9e80fcdc-9672-4b11-b303-95eb10de2f18)

### Environment

```Markdown
Server version: 2.22.0

Core version: 15.2.0

Canvas version: 2.20.9

UI version: 1.66.1
```

**Comment by leppsey** [comment]
I have another question: my machines are connected via Ethernet cable, but the speed doesn’t go above 108 Mbps. There are no speed limitations in the network, could it be that CVAT has a limit?

**Comment by bsekachev** [comment]
No, CVAT itself does not set any bandwidth limits. Find the reason in your infrastructure.
