### ISSUE TITLE
Automatic annotation with pose model

### ISSUE THREAD

**Issue by manu13008** [cvat-ai/cvat#8622]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I read previous issues with answers saying it was not possible actually to load a pose estimation model to perform automatic annotation with skeleton (#6497 ).

Is this feature still unavailable actually ? If no, is there any guidelines showing how to implement it ?

Thanks

### Describe the solution you'd like

I trained a Yolo11n-pose model on a specific dataset and I would like to load this model in my cvat self hosted version to perform automatic annotation on a larger dataset.

**Comment by bsekachev** [comment]
The feature is available. You may find reference model recognizing skeletons in open source: https://github.com/cvat-ai/cvat/tree/develop/serverless/pytorch/mmpose/hrnet32/nuclio
