### ISSUE TITLE
@lakshmikantdeshpande , it should be possible. We are going to use KeyCloak for auth purpose in the nearest future.

### ISSUE THREAD

**Issue by Brokendisme** [cvat-ai/cvat#8630]
@lakshmikantdeshpande , it should be possible. We are going to use KeyCloak for auth purpose in the nearest future.

_Originally posted by @nmanovic in https://github.com/cvat-ai/cvat/issues/1217#issuecomment-607787437_

**Comment by azhavoro** [comment]
@Brokendisme ?

**Comment by Brokendisme** [comment]
Sorry, I didn't notice your reply，I would like to know the documentation about the keycloak integration with cvat。
