### ISSUE TITLE
Can not slide combined segmentation masks multiple times.

### ISSUE THREAD

**Issue by tong-xz** [cvat-ai/cvat#8647]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a huge instance segmentation mask
2. Right-click it and slice it.
3. After finishing the first trial, do it a second time.
4. Nothing will pop out at that time.

### Possible Solution

Go back to the main website and enter the task again. But still can only slice mask for once.

**Comment by bsekachev** [comment]
It only appears until you click "Hide" for the first time. 

![Uploading image.png…]()
