### ISSUE TITLE
Attribute Annotation is zooming too much when changing the frame

### ISSUE THREAD

**Issue by piercus** [cvat-ai/cvat#8656]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

## With firefox
1. Create a task in CVAT with 2 images, like

```json
[
  {
    "name": "Test",
    "id": 3693910,
    "color": "#fb117d",
    "type": "mask",
    "attributes": []
  }
]
```
2. Create one big mask for each image -> Save the job
3. Re-open the task
4. Go in 'Attribute annotation' mode

<img width="1274" alt="Capture d’écran 2024-11-07 à 10 59 02" src="https://github.com/user-attachments/assets/be6bb661-5e4c-4fa7-b9bb-ea84cb04d632">

5. Type "F" for next frame

<img width="1268" alt="Capture d’écran 2024-11-07 à 10 58 41" src="https://github.com/user-attachments/assets/c6d438b2-210b-44a3-befd-76b39dbf5d89">

### Expected Behavior

The next frame is visible on the screen

### Possible Solution

I feel the problem comes from [SHAPE_FOCUSED event](https://github.com/cvat-ai/cvat/blob/a56e94b00dfbd583a7e01cec19332a2b92f27067/cvat-canvas/src/typescript/canvasView.ts#L1921-L1929)

This problem makes the Attribute Annotation very hard to use, i'm wondering is a quick fix would be to just fit to the image, or have the ability to fit to the image in the Attribute Annotation mode.

### Context

I'm trying to annotate attributes on Mask

### Environment

```Markdown
This issue is reproductible both in cloud-hosted CVAT and self-hosted CVAT
```

## Note about behavior on Google Chrome

The same kind of problem appear on Google Chrome, but the behavior is a little bit different, and it is impacted by the size of the image and by AAM parameter (while on Firefox it's not)

Should i open another issue ?

## About the AAM parameter

Changing the AAM parameter on Firefox does not fix the issue

<img width="531" alt="Capture d’écran 2024-11-06 à 17 42 13" src="https://github.com/user-attachments/assets/4e7cbcaa-4555-4939-be2f-09c34a2550bb">

**Comment by bsekachev** [comment]
Hello, thanks for the report
