### ISSUE TITLE
why the deleted frame will still be restored automatically?

### ISSUE THREAD

**Issue by jaffe-fly** [cvat-ai/cvat#8665]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

anno a video frames with ractangle shape. set 15min auto save, when i deleted some frames, with  `ALT+Del` shortcuts, after some time, go back to check anno, found some frame still  not annoed, I distinctly remember deleting it
Does anyone know why this is?

**Comment by bsekachev** [comment]
Did you save the job after deleting frames?

**Comment by jaffe-fly** [comment]
just use auto save by 15min. Do I need to save it every time I delete it? I want to know why it is automatically restored? Is my deletion a fake deletion?

**Comment by bsekachev** [comment]
Your deletions submiited on the server each 15 minutes if auto save enabled each 15 minutes. But the tab must be open, otherwise auto save may not trigger or trigger rare (it is a browser restriction, not CVAT).
