### ISSUE TITLE
CVAT installation Issue

### ISSUE THREAD

**Issue by sailokeshaithagoni** [cvat-ai/cvat#8666]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Clone and go to dir, docker compose up -d.

docker logs cvat_server
Error: positional arguments are not supported: ['init', 'run', 'server']
For help, use /usr/bin/supervisord -h
Error: positional arguments are not supported: ['init', 'run', 'server']
For help, use /usr/bin/supervisord -h

**Comment by azhavoro** [comment]
Seems you have old cvat images locally with `dev` tag, try to use latest release or run `docker compose pull` before run
