### ISSUE TITLE
Auto Annotation fails with Tracker Initialization error

### ISSUE THREAD

**Issue by trathpai** [cvat-ai/cvat#8670]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

docker compose -f docker-compose.yml -f components/serverless/docker-compose-serverless.yml up -d 

deploy nuctl function such as siammask

Press f or play button

### Expected Behavior

Auto annotate should work without errors.

### Context

Tracker initialization error
HTTPConnectionPool(host='host.docker.internal', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbaec1976a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

All services are working including nuctl deployed functions.

### Environment

```Markdown
Git hash commit commit 7f764a2fcc78fe29f362b46ddac54139ceb7b482 (HEAD -> develop, origin/develop, origin/HEAD)

Docker version 27.3.1

OS - Linux
```

**Comment by azhavoro** [comment]
> Name or service not known

`host.docker.internal` can't be resolved but should be, this is not CVAT related, please refer to the Docker documentation
