### ISSUE TITLE
Interaction error when working with SAM-2

### ISSUE THREAD

**Issue by amrithkrish** [cvat-ai/cvat#8674]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Set-up CVAT with serverless functions.
2. Host SAM-2 model.

### Context

When using SAM-2 model, the interface indicates its waiting for SAM processing but immediately gives an error :

Interaction error occured
Error: Request failed with status code 503. "HTTPConnectionPool(host='host.docker.internal', port=34361): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb7905337c0>: Failed to establish a new connection: [Errno 111] Connection refused'))".

![image](https://github.com/user-attachments/assets/6acaa165-518b-49b9-8136-ac1f1069ae6c)

The logs from SAM2 container looks like : 
![image](https://github.com/user-attachments/assets/23c40ab3-6618-48b6-aa40-461d416e0398)

The logs from cvat_server is giving the error : 
2024-11-11 07:02:14,648 DEBG 'runserver' stderr output:
[Mon Nov 11 07:02:14.648184 2024] [wsgi:error] [pid 141:tid 140427000612608] [remote 172.18.0.3:37396] [2024-11-11 07:02:14,648] ERROR django.request: Service Unavailable: /api/lambda/functions/pth-facebookresearch-sam2-vit-h

2024-11-11 07:02:14,648 DEBG 'runserver' stderr output:
[Mon Nov 11 07:02:14.648325 2024] [wsgi:error] [pid 141:tid 140427000612608] [remote 172.18.0.3:37396] ERROR:django.request:Service Unavailable: /api/lambda/functions/pth-facebookresearch-sam2-vit-h

![image](https://github.com/user-attachments/assets/d869916d-0957-4337-a26a-ef40b60e574e)

### Environment

```Markdown
- Operating System and version (e.g. Linux, Windows, MacOS) --> Ubuntu 20.04.6 
- Are you using Docker Swarm or Kubernetes? --> Docker
```

**Comment by bsekachev** [comment]
We do not have SAM2 model in this repository
