### ISSUE TITLE
Nuclio Function Deployment Fails with Image Pull Error in Kubernetes

### ISSUE THREAD

**Issue by javiplav** [cvat-ai/cvat#8679]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

While deploying a Nuclio function included in the CVAT repository in a Kubernetes environment, I encountered an issue where the function deployment fails due to an image pull error. The function status is marked as “unhealthy,” and the deployment does not proceed as expected.

1. Run CVAT and Nuclio in a Kubernetes environment.
2. Execute the following command to deploy the Nuclio function:  `./nuctl deploy --project-name cvat -n nuclio --path ./serverless/onnx/WongKinYiu/yolov7/nuclio --platform kube`
3. Observe the error message in the logs.

### Expected Behavior

The function should deploy successfully in Kubernetes without image pull issues.

### Possible Solution

If this image is intended to be public, ensure it is accessible without authentication or provide updated instructions for handling private images. Otherwise, please clarify the required configuration for authentication to pull private images.

### Context

Running the function in Kubernetes for inference purposes is essential for our setup with CVAT. Guidance on resolving this image pull issue would be greatly appreciated.

### Environment

```Markdown
Server version: 2.22.0

Core version: 15.2.1

Canvas version: 2.20.10

UI version: 1.66.4

Kubernetes Version: v1.28.9

Deployment Platform: Kubernetes
```

**Comment by azhavoro** [comment]
https://docs.cvat.ai/docs/administration/advanced/k8s_deployment_with_helm/#optional-enable-auto-annotation-feature
