### ISSUE TITLE
Export problem (COCO File)

### ISSUE THREAD

**Issue by isu-jahan** [cvat-ai/cvat#8682]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

![Export Issue 1](https://github.com/user-attachments/assets/a3dd4a53-3963-4080-8cca-8062b66af7ed)
![Export Issue 2](https://github.com/user-attachments/assets/1924b50d-2e64-4bf2-b9cf-c1953c9d6078)

### Expected Behavior

want to export data without loosing my annotation

**Comment by bsekachev** [comment]
As the task is already in a queue, you can't export twice. Please, wait the first process to be done
