### ISSUE TITLE
Cannot create a project from a backup 

### ISSUE THREAD

**Issue by azadehashouri** [cvat-ai/cvat#8684]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

Hello everyone,

I used CVAT on another virtual machine and its version is:

```
Server version: 2.19.0

Core version: 15.2.0

Canvas version: 2.20.9

UI version: 1.66.0
```

After a while I had to move to another virtual machine and I exported a backup of my whole project and create a project from this backup on my second virtual machine but I got the following error:

![image](https://github.com/user-attachments/assets/f27fa39a-aa4e-4e4d-b4ca-236597b67c50)

CVAT version on my second machine is:

Server version: 2.22.0

Core version: 15.2.1

Canvas version: 2.20.10

UI version: 1.66.4

Please help me in this problem, so many thanks in advance.

**Comment by zhiltsov-max** [comment]
Hi, please make sure all the DB migrations were applied. It looks like you might need to run `python manage.py migrate` on the second CVAT instance.

**Comment by azadehashouri** [comment]
> python manage.py migrate

@zhiltsov-max Thanks for reply.

I have to have two CVATs with exactly same version to import backup of project from one to another one? or just runnig `python manage.py migrate` is enough?

Thanks for your help.

**Comment by azadehashouri** [comment]
@zhiltsov-max 
In addition to this information, I clone the last version of cvat github on my second machine, but the version of my first cvat was v2.18.0.

Thank you.

**Comment by zhiltsov-max** [comment]
No, you don't need to have the same versions of CVAT for backups to work. Please try to run this on the second machine:
```bash
cd cvat_repo/
docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
python manage.py migrate
```

**Comment by azadehashouri** [comment]
@zhiltsov-max Thank you so much for your response.

I will test if. 
But before create a project from backup I need to solve another issue about restricting worker download option.

I explained it clearly in [this issue](https://github.com/cvat-ai/cvat/issues/8714).

Please help me in this if it's possible for you.

**Comment by azadehashouri** [comment]
I reinstall cvat from the first step and It works.

Thank you.
