### ISSUE TITLE
Issues related to tasks with honeypots

### ISSUE THREAD

**Issue by Marishka17** [cvat-ai/cvat#8686]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

- ~~Check if `GET /jobs` can be optimized for tasks with gt_pool validation mode (e.g. in the case of 500 jobs it takes 17s)~~ 
![image](https://github.com/user-attachments/assets/cccfae28-2467-44ef-987f-4f4ca463001d)
![image](https://github.com/user-attachments/assets/f9d2cd2b-df6e-467d-a270-ccbbf91f8d3a)
- When updating `disabled_frames` in task validation layout, outdated data is returned in the response
- Optimize `PATCH /tasks/id/validation_layout`
For instance, when disabling one validation frame and shuffling honeypots:
  Request duration: 114254 ms
  ![image](https://github.com/user-attachments/assets/3e3c6d05-7eb1-435f-a171-d3cd2c4bfbd1)

### Environment

```Markdown
- git commit: 1e7ff33
```

**Comment by zhiltsov-max** [comment]
Job list performance was improved in https://github.com/cvat-ai/cvat/pull/8275, it's because of inefficient field access in IAM.
