### ISSUE TITLE
how to set a shorchut key for AI interactor?

### ISSUE THREAD

**Issue by ywangwxd** [cvat-ai/cvat#8707]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Describe the solution you'd like

The AI interactor is very useful for image segmentation, but I did not find any shortcut key for this function. I have to re-select it after annotating each instance. How can I set up a hotkey for this?

**Comment by bsekachev** [comment]
Default shortcut to use the latest drawing tool is **N**.
