### ISSUE TITLE
404 Page not found on CVAT server link

### ISSUE THREAD

**Issue by ywangwxd** [cvat-ai/cvat#8715]
I am encountering the same issue as described in the title. I have searched this in the history issues.
I am sure I have export CVAT_HOST correctly before the `up` command, like this:

CVAT_HOST=my_host_ip docker compose up -d

I have also checked logs of cvat_db, cvat_server and cvat_opa. Only cvat_opa show some errors.
I have attached the log output for each service here.
[log1.txt](https://github.com/user-attachments/files/17797199/log1.txt)
[log2.txt](https://github.com/user-attachments/files/17797201/log2.txt)
[log3.txt](https://github.com/user-attachments/files/17797202/log3.txt)
     
If I run health_check, it report everything is working, no error or warning message reported.

> Cache backend: default   ... working
Cache backend: media     ... working
DatabaseBackend          ... working
DiskUsage                ... working
MemoryUsage              ... working
OPAHealthCheck           ... working

So what is the problem?

    There are no `up` and `down` commands for docker, you probably mean `docker compose`.
    Seems you just forgot to export the CVAT_HOST environment variable before the `up` command.
    If this does not help, please provide the exact steps on how we can reproduce the problem.
 _Originally posted by @azhavoro in https://github.com/cvat-ai/cvat/issues/7072#issuecomment-1785891950_

**Comment by azhavoro** [comment]
@ywangwxd what is output of `docker inspect --format '{{ index .Config.Labels "traefik.http.routers.cvat.rule"}}' cvat_server`?

**Comment by ywangwxd** [comment]
> @ywangwxd what is output of `docker inspect --format '{{ index .Config.Labels "traefik.http.routers.cvat.rule"}}' cvat_server`?

I got the solution. Using hostname instead of the ip address when export CVAT_HOST. This is very tricky.

**Comment by azhavoro** [comment]
There is only one reason for this - the HOST header that comes to traefik does not match the Host value in the configuration.

**Comment by GGDRriedel** [comment]
I have the same problem, what do you mean by hostname? I was exporting the IP as I am on an internal network
