### ISSUE TITLE
nuclt deploy function hangs at the cleanup stage

### ISSUE THREAD

**Issue by ywangwxd** [cvat-ai/cvat#8717]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce
I am trying to deploy the SAM auto-annotation function. Everything goes well until the last cleanup stage.
I checked the documentation for the nuctl deploy command, and there is actually a --no-cleanup option. I changed the code in deploy-gpu.sh to enable this option:

`nuctl deploy --project-name cvat --path "$func_root" --no-cleanup --no-pull --logger-level debug --file "$func_config" --platform local`

However, nothing changed; it still hangs at the cleanup stage.

Btw, I have already made the other funtions work well, e.g., yolov3, so I guess my whole env is fine.

> Deploying pytorch/facebookresearch/sam function...
24.11.19 10:29:44.123 (W)            nuctl.platform MaxWorkers is deprecated and will be removed in v1.15.x, use NumWorkers instead
24.11.19 10:29:44.671 (I)                     nuctl Deploying function {"name": "pth-facebookresearch-sam-vit-h"}
24.11.19 10:29:44.671 (I)                     nuctl Building {"builderKind": "docker", "versionInfo": "Label: 1.13.0, Git commit: c4422eb772781fb50fbf017698aae96199d81388, OS: linux, Arch: amd64, Go version: go1.21.7", "name": "pth-facebookresearch-sam-vit-h"}
24.11.19 10:29:45.360 (I)                     nuctl Staging files and preparing base images
24.11.19 10:29:45.360 (W)                     nuctl Python 3.8 runtime is deprecated and will soon not be supported. Migrate your code and use Python 3.9 runtime (`python:3.9`) or higher
24.11.19 10:29:45.360 (W)                     nuctl Using user provided base image, runtime interpreter version is provided by the base image {"baseImage": "ubuntu:22.04"}
24.11.19 10:29:45.361 (I)                     nuctl Building processor image {"registryURL": "", "taggedImageName": "cvat.pth.facebookresearch.sam.vit_h:latest-gpu"}
24.11.19 10:29:57.752 (I)            nuctl.platform Building docker image {"image": "cvat.pth.facebookresearch.sam.vit_h:latest-gpu"}
24.11.19 10:30:01.583 (I)            nuctl.platform Pushing docker image into registry {"image": "cvat.pth.facebookresearch.sam.vit_h:latest-gpu", "registry": ""}
24.11.19 10:30:01.583 (I)            nuctl.platform Docker image was successfully built and pushed into docker registry {"image": "cvat.pth.facebookresearch.sam.vit_h:latest-gpu"}
24.11.19 10:30:01.583 (I)                     nuctl Build complete {"image": "cvat.pth.facebookresearch.sam.vit_h:latest-gpu"}
24.11.19 10:30:01.583 (I)                     nuctl Cleaning up before deployment {"functionName": "pth-facebookresearch-sam-vit-h"}

### Expected Behavior

I expect the cleaning up stage to go well. If it does not, I expect the `--no-cleanup` option to take effect.

**Comment by azhavoro** [comment]
CVAT team does not develop and support the nuclio and nuctl tools, please ask your question to the nuclio team

**Comment by ywangwxd** [comment]
> CVAT team does not develop and support the nuclio and nuctl tools, please ask your question to the nuclio team

But the problem is likely in the docker image of `pth-facebookresearch-sam-vit-h`. This is provided by the CVAT project.
I have two other functions work well, so it is hard to get help from nuctl. Here is the last piece of logging output when
enabling verbose option.  Is it possible that the container dies right after it is started for some reason? Otherwise
docker inspect will not hangs because the container disappeared soon.

> 24.11.19 16:32:06.469 (D)                     nuctl no-cleanup flag provided, skipping temporary dir cleanup
24.11.19 16:32:06.469 (I)                     nuctl Cleaning up before deployment {"functionName": "pth-facebookresearch-sam-vit-h"}
24.11.19 16:32:06.469 (D)     nuctl.platform.docker Getting containers {"options": {"Name":"nuclio-nuclio-pth-facebookresearch-sam-vit-h","Labels":null,"Stopped":true,"ID":""}}
24.11.19 16:32:06.469 (D) tl.platform.docker.runner Executing {"command": "docker ps --quiet --all   --filter \"name=^/nuclio-nuclio-pth-facebookresearch-sam-vit-h$\"  "}
24.11.19 16:32:06.489 (D) tl.platform.docker.runner Command executed successfully {"output": "96cde29537ef\n", "stderr": "", "exitCode": 0}
24.11.19 16:32:06.489 (D) tl.platform.docker.runner Executing {"command": "docker inspect 96cde29537ef "}
