### ISSUE TITLE
How can I create a task from remote sources?

### ISSUE THREAD

**Issue by azadehashouri** [cvat-ai/cvat#8722]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

I want to create a new task from remote sources that its URL placed in internal network. But I got this error:

![Clipboard - November 20, 2024 8_37 AM](https://github.com/user-attachments/assets/bfd788d5-4bf7-4dc3-b3a0-448e6070b6d6)

Does it need to the internet? because I don't have internet on my virtual machine but I have ping to the machine that this URL belongs to.

Thanks in advance.

**Comment by azadehashouri** [comment]
In addition to this information, I can download this image om my virtual machine by using wget command.

**Comment by zhiltsov-max** [comment]
Hi, please read the manual https://docs.cvat.ai/docs/manual/basics/create_an_annotation_task/#select-files.
If the host is a localhost, you might need to make the url reachable from the CVAT container as described [here](https://github.com/cvat-ai/cvat/issues/8207#issuecomment-2247146045) or [here](https://github.com/cvat-ai/cvat/issues/6892#issuecomment-1746484066).

**Comment by azhavoro** [comment]
You need to define `SMOKESCREEN_OPTS` env variable to access local IPs here https://github.com/cvat-ai/cvat/blob/develop/docker-compose.yml#L17 like this https://github.com/cvat-ai/cvat/blob/develop/tests/allow_minio.sh#L3

**Comment by hdb-3** [comment]
> Hi, please read the manual https://docs.cvat.ai/docs/manual/basics/create_an_annotation_task/#select-files. If the host is a localhost, you might need to make the url reachable from the CVAT container as described [here](https://github.com/cvat-ai/cvat/issues/8207#issuecomment-2247146045) or [here](https://github.com/cvat-ai/cvat/issues/6892#issuecomment-1746484066).
I'm having this issue as well, but this link is broken.How to solve it, thank you
<img width="1359" height="1020" alt="Image" src="https://github.com/user-attachments/assets/9c177335-06c5-4b81-99d5-8456ec3d1ff2" />

**Comment by zhiltsov-max** [comment]
@hdb-3 , hi, did you have a change to try the steps described in https://github.com/cvat-ai/cvat/issues/8722#issuecomment-2490597378, https://github.com/cvat-ai/cvat/issues/8207#issuecomment-2247146045 and https://github.com/cvat-ai/cvat/issues/6892#issuecomment-1746484066?

**Comment by hdb-3** [comment]
> ，嗨，您是否有更改来尝试 [#8722（评论）、](https://github.com/cvat-ai/cvat/issues/8722#issuecomment-2490597378)[#8207（评论）](https://github.com/cvat-ai/cvat/issues/8207#issuecomment-2247146045)和 [#6892（评论）](https://github.com/cvat-ai/cvat/issues/6892#issuecomment-1746484066)中描述的步骤？

<img width="1005" height="262" alt="Image" src="https://github.com/user-attachments/assets/b16d5a8b-0988-47c2-9187-5ca9392f304a" />I changed the configuration according to the suggestion you gave, the cloud storage can be created, I originally created a bucket with an image, but it prompted me this content,Please advise!

**Comment by hdb-3** [comment]
There is an image inside the bucket

**Comment by zhiltsov-max** [comment]
Please try to investigate what data is reachable from CVAT via the task creation dialog:

<img width="1862" height="1668" alt="Image" src="https://github.com/user-attachments/assets/9d2483f4-908f-4795-8ae2-8bca4c6a74b7" />

or via the cloudstorage content-v2 endpoint in swagger: `https://app.cvat.ai/api/swagger/#/cloudstorages/cloudstorages_retrieve_content_v2` (change the url for your server).

If everything needed is visible, the issue might be that the cvat_worker_import doesn't can't reach the cloud storage.

**Comment by hdb-3** [comment]
> 请尝试通过任务创建对话框调查可从 CVAT 访问哪些数据：
> 
> <img alt="图像" width="1862" height="1668" src="https://private-user-images.githubusercontent.com/13832349/464636426-9d2483f4-908f-4795-8ae2-8bca4c6a74b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIyMjk5ODksIm5iZiI6MTc1MjIyOTY4OSwicGF0aCI6Ii8xMzgzMjM0OS80NjQ2MzY0MjYtOWQyNDgzZjQtOTA4Zi00Nzk1LThhZTItOGJjYTRjNmE3NGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzExVDEwMjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ODFmZTU5NTE1NWVkYjhlMTQwNmUwNGU1OTFmMTcyYTQ3MGU0OTgxNThiOWE5MTM2NDY2NDA2ODlmNDMwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZWligV1BvnG6clqCaAY8_sVICg6P-HEsaYoB9MQvDrE">
> 或通过 Swagger 中的 CloudStorage Content-v2 端点：（更改服务器的 URL）。`https://app.cvat.ai/api/swagger/#/cloudstorages/cloudstorages_retrieve_content_v2`
> 
> 如果所需的一切都可见，则问题可能是cvat_worker_import无法访问云存储。

<img width="379" height="184" alt="Image" src="https://github.com/user-attachments/assets/12282e0c-7aa5-4169-8863-bf21ae19fae5" />

<img width="682" height="235" alt="Image" src="https://github.com/user-attachments/assets/aaf45cab-25fe-407a-aa55-72e184886088" />

<img width="588" height="372" alt="Image" src="https://github.com/user-attachments/assets/e9dbee6c-7dfa-4cba-b889-7604c7f96fe4" />

<img width="588" height="335" alt="Image" src="https://github.com/user-attachments/assets/5120871d-a1e7-4753-ae76-c2a99eb41633" />

<img width="751" height="743" alt="Image" src="https://github.com/user-attachments/assets/57862aa7-88b1-45d4-8e5a-0fe8d5f536e1" />
Sorry, I'm back to Failed to connect to proxy URL: "http://localhost:4750 error, is this the reason why smokescreen is not connecting? I've posted all the relevant configurations here, please help me check what the hell is the problem, it's been bothering me all day.  By the way, I have a question: SMOKESCREEN_OPTS: ${SMOKESCREEN_OPTS:---allow-address=172.19.0.7/16}Is the IP here to fill in the IP of my minio container, but it is not fixed, or can you fill in the container name? Thanks a lot！

**Comment by zhiltsov-max** [comment]
@hdb-3, hi, I guess you should check if smokescreen is started successfully, as the port 4750 is the smokescreen port. Try running `docker logs cvat_server` and check if there are any startup errors.

**Comment by hdb-3** [comment]
> [@hdb-3](https://github.com/hdb-3), hi, I guess you should check if smokescreen is started successfully, as the port 4750 is the smokescreen port. Try running and check if there are any startup errors.`docker logs cvat_server`

Thanks for the suggestion, I confirm that cvat_worker_import can't access cloud storage, {"allow":false,"content_length":178,"decision_reason":"The destination address (172.19.0.5) was denied by rule 'Deny: Private Range'. destination address was denied by rule, see error","requested_host":"minio:9000"}

botocore.exceptions.ClientError: An error occurred (407) when calling the GetObject operation: Proxy Authentication Required

This is an error in my log, I don't know how to change it, do I need to modify the ACL file in the smokescreen? I'm a novice who doesn't know very much, please advise, thank you!

**Comment by zhiltsov-max** [comment]
@hdb-3, this is exactly the error that should be resolved by allowing a host in `SMOKESCREEN_OPTS`. I can see from the screenshots above you're changing the entrypoint scripts, so it's possible to check in the logs which IP is determined for minio. From the conversation, I can also see that the minio IP in the error message and in your question above are different:

`The destination address (172.19.0.5) ` and `SMOKESCREEN_OPTS: ${SMOKESCREEN_OPTS:---allow-address=172.19.0.7/16}` 

It looks like you need to make sure the minio IP in SMOKESCREEN_OPTS is correct.

[The CLI documentation](https://github.com/stripe/smokescreen) says that the `--allow-address` can only accept a single IP address.

**Comment by hdb-3** [comment]
<img width="994" height="176" alt="Image" src="https://github.com/user-attachments/assets/8127bae2-c377-4623-bf4a-2b8236d0796d" />These two IPs are inconsistent, and the IP of minio will change every time I restart it, is it because I wrote the dead IP here, causing the auto-fetch script to fail? SMOKESCREEN_OPTS: "--allow-address=172.19.0.7", how do I change it here?Thanks for your advise.

**Comment by hdb-3** [comment]
```bash
#!/bin/bash
# Same as allow_webhooks_receiver.sh, but for minio.
minio_ip_addr="$(getent hosts minio | head -1 | awk '{ print $1 }')"
export SMOKESCREEN_OPTS="$SMOKESCREEN_OPTS --allow-address=$minio_ip_addr"

exec /home/django/backend_entrypoint.sh "$@"
```

Here's the script for me to get the ip, is there a bug?

**Comment by zhiltsov-max** [comment]
@hdb-3, the script looks ok. I think it can be a deployment issue instead. I'm not sure how minio is deployed in your case, but I can see 2 options here:
- it's deployed in the same docker-compose as CVAT, then it can have a dynamic ip, which needs to be fetched with the script (this is how it's being done in CVAT tests for [minio](https://github.com/cvat-ai/cvat/blob/develop/tests/docker-compose.minio.yml) and [webhooks](https://github.com/cvat-ai/cvat/blob/develop/tests/docker-compose.test_servers.yml))
- a custom network is created separately and minio is deployed separately in the this network, with required ports open (9000 in your case). This way, you can reach minio from CVAT through the network gateway ip and the minio port (this setup is described in https://github.com/cvat-ai/cvat/issues/6760#issuecomment-1696961411)

Please also check: 
- the minio container has open ports for connection (9000 in your case, [example](https://github.com/cvat-ai/cvat/blob/0d855af7c548c13ec23d32440718dae96a1c4bda/tests/docker-compose.minio.yml#L18-L23))
- the updated entrypoint script is used in the `cvat_worker_import` container ([example](https://github.com/cvat-ai/cvat/blob/0d855af7c548c13ec23d32440718dae96a1c4bda/tests/docker-compose.minio.yml#L1-L11))

**Comment by hdb-3** [comment]
<img width="432" height="428" alt="Image" src="https://github.com/user-attachments/assets/857ff6f7-6bd5-4d86-b302-af2103ac9a69" />I seem to understand that my minio is deployed in the same docker-compose as the CVAT, but I also created a custom network, and the two can't be mixed up, right?

**Comment by hdb-3** [comment]
Thank you very much! I added some configuration under the cvat_worker_import and it made it happen!
