### ISSUE TITLE
Cant communicate cvat Api from my dockerized application

### ISSUE THREAD

**Issue by Nishanth-KR** [cvat-ai/cvat#8723]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1) Docker compose up - CVAT application
2) Docker compose up - my application
3) Call CVAT REST API from my application

### Expected Behavior

{
status:200,
message:"successfuly",
}

### Possible Solution

We should able to reach the CVAT REST API from different networks. 

### Context

I am planning to integrate the CVAT application with my MERN  application. So in that, I have facing the issue while i was inside the dockerized containers.

**Comment by bsekachev** [comment]
That is about network configuration, we can't help here. At least make sure that your application in the same Docker network as CVAT
