### ISSUE TITLE
I encountered a CORS error while trying to create a new project in CVAT. 

### ISSUE THREAD

**Issue by Nishanth-KR** [cvat-ai/cvat#8733]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1). Open the CVAT web interface.
2). Attempt to create a new project using the API or web UI.
3). Observe the error in the browser's developer console.

### Expected Behavior

Access to XMLHttpRequest at 'http://localhost:5001/api/annotate/createStorage' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

### Possible Solution

The project should be created without any CORS issues.

### Context

CVAT version: latest
Deployment method: Docker
Browser:  Chrome

### Environment

```Markdown
This issue seems related to CORS policy misconfiguration between the frontend and backend. Please advise if additional configuration is required in the setup.
```

**Comment by bsekachev** [comment]
Response headers from localhost:5001 have to allow requests from localhost:3000 using corresponding rules: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
