### ISSUE TITLE
Image Quality documentation-reality discrepancy

### ISSUE THREAD

**Issue by jaroslavknotek** [cvat-ai/cvat#8738]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1) See [user manual - advanced configuration](https://docs.cvat.ai/docs/manual/basics/create_an_annotation_task/#advanced-configuration), the part about Image Quality and read that when Image Quality is set to 100% then the image is not compressed
2) Follow the procedure with the image below 
![C100_700_L_250_00](https://github.com/user-attachments/assets/da312123-94d4-48cb-831f-f36bc554cab6)
3) Open the editor and get surprised to see a compressed image:

![image](https://github.com/user-attachments/assets/ba57bf11-94b8-400f-92c0-c5255c2c8818)

4) Try to monitor trafic and see that the default data fetching request is `.../data?quality=compressed`. This is where the documentation is wrong. According to documentation there should be no compression applied. Using `.../data?quality=` returns data in their original state.

### Expected Behavior

Opening the task, you would expect to see that image not compressed. 

### Possible Solution

Respect the user settings. When image quality is set to 100% then either

A) Don't send `quality=compress` query params from frontend, send `quality=standard`
B) Send `quality=compress` but return uncompressed data because you identified user compression settings

Another solution is to fix the documentation so it would not state false information, but that would be a bummer. 

### Context

I am trying to use CVAT for its original purpose with the data provided abovee

### Environment

```Markdown
- Using local deployment
- From `develop` branch commit `2cca2dd3cc61290aeac138443979cd28571e5846` from Oct 22nd
- Relevant links:
  - 4yo closed issue: https://github.com/cvat-ai/cvat/issues/1900
  - open discussion https://github.com/cvat-ai/cvat/discussions/3824
```

**Comment by bsekachev** [comment]
The problem with your image (it got darker) is that original image is 16bit, hovewer CVAT does not support 16bit images.

**Comment by bsekachev** [comment]
Related https://github.com/cvat-ai/cvat/issues/2987

**Comment by jaroslavknotek** [comment]
Thank you, you are correct. Using 8bit solved the issue.

However, let me point out that allowing to upload unsuppurted image without transformation and let users who are not usually technically skilled, deal with the consequences is very inconvenient.

Is there any workaround so I (as a CVAT admin) can keep tens of users from my organization to upload unsupported images?
