### ISSUE TITLE
Can access CVAT over LAN but not Internet

### ISSUE THREAD

**Issue by alirezajafarishahedan** [cvat-ai/cvat#8764]
Hi, i did all in https://github.com/cvat-ai/cvat/issues/1095 but http://localhost:7070/auth/login don't login and show message "Could not check authentication on the server Open the Browser Console to get details" but on http://localhost:8080/auth/login no problem.it on WAN also http://myip:7060/, i have same state. can you help me?

**Comment by azhavoro** [comment]
Please describe properly your issue and provide steps to reproduce
