### ISSUE TITLE
how to change UI language

### ISSUE THREAD

**Issue by stephen-TT** [cvat-ai/cvat#8774]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

**Comment by stephen-TT** [comment]
I want to change the web UI language to Chinese, how to  achieve it . thanks

**Comment by bsekachev** [comment]
We do not support Chinese language. There is existing issue about localization support https://github.com/cvat-ai/cvat/issues/374
