### ISSUE TITLE
Getting 429 while annotating images (images are not being able to load)

### ISSUE THREAD

**Issue by ErezAlster** [cvat-ai/cvat#8781]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. open a job
2. move to image that you never loaded
3. previous image is grayed out and not new images is not loaded 

### Expected Behavior

relevant images should be displayed

### Context

The first ~30 images from each job are being loaded successfully.
When trying to move to the next images i'm getting timeout and 429 errors for this url: http://{domain}/api/jobs/3/data?org=&quality=compressed&type=chunk&index=1

Any ideas what can be the problem?

In the server logs I'm able to see the following error:
[2024-12-05 11:05:12,804] INFO cvat.apps.engine.cache: Starting to prepare chunk: key segment_3_chunk_1_0

I'm not able to see the next log which is: "Ending to prepare chunk: key {key}"

Any ideas?

### Environment

```Markdown
cvat env based on k8s
```

**Comment by bsekachev** [comment]
Since the latest release, a dedicated worker `cvat_worker_chunks` is responsible for preparing data chunks.
Make sure you have enough active pods hosting this worker and they are healthy.

**Comment by AchimGaedkeLynker** [comment]
Stumbling into issues with image loading, too. As I use shared image resources I have added a section to `docker-compose.override` - and now it works...

```text
  cvat_worker_chunks:
    volumes:
      - cvat_share:/home/django/share:ro
```

to extend https://docs.cvat.ai/docs/administration/basics/installation/#share-path - is this a "documentation bug"?

**Comment by satyatejaswini1234** [comment]
It appears that the issue stems from either insufficient worker pods or improper resource sharing, which can lead to the server timing out or hitting rate limits. Scaling up the number of cvat_worker_chunks pods and ensuring proper image resource sharing should address the issue.

**Comment by ErezAlster** [comment]
The solution was to create PVC with many write permission and not only one.
I'm using k8s

Thanks a lot!
