### ISSUE TITLE
I have modified the source code, how do I rebuild the image?

### ISSUE THREAD

**Issue by stephen-TT** [cvat-ai/cvat#8813]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I have modified the source code, how do I rebuild the image?
thanks

**Comment by stephen-TT** [comment]
i follow the step
```
# 1. cd project root
    cd cvat-2.23.1
    
    # 2. make something change in views.py file

    # 3. rebuild
    docker compose -f docker-compose.yml -f docker-compose.dev.yml build --no-cache

```
i want to know it's right?

**Comment by bsekachev** [comment]
``docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build``

**Comment by stephen-TT** [comment]
Do you have any way to localize the UI interface into Chinese, besides using that ancient issue --- https://github.com/cvat-ai/cvat/issues/374 ?

**Comment by bsekachev** [comment]
No.
