### ISSUE TITLE
No idea how to add another label to the same task?

### ISSUE THREAD

**Issue by AntDX316** [cvat-ai/cvat#8829]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/8d595701-20fb-48dd-a261-8e677fc1e7aa)

### Expected Behavior

I should be able to add, rename, and delete labels with ease.

### Possible Solution

Add ability to add, rename, delete labels with ease from the task area.

### Context

![image](https://github.com/user-attachments/assets/f1c11ff0-31bd-45ae-88d1-8b7361123d7c)

### Environment

```Markdown
https://app.cvat.ai/tasks/
```

**Comment by bsekachev** [comment]
On the task page `app.cvat.ai/tasks/<id>`
Or on the project page if the task is in project `app.cvat.ai/projects/<id>`

https://docs.cvat.ai/docs/manual/basics/task-details/
