### ISSUE TITLE
Retrieve Object Count in a Project from Database

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [cvat-ai/cvat#8831]
Hi,
I would like to know if it's possible to directly retrieve the total count of objects within a project from the database.
For example, if I have a project with 3 tasks, each containing 10 frames, and each frame having 2 objects, the total number of objects in the project would be 3 * 10 * 2 = 60.
Does the database store this kind of data, and if so, could you provide the relevant table name and column details to access the object count?
Thank you for your help!

**Comment by MohamedKHALILRouissi** [comment]
expected result 
{ 
   "train": 50, # total images in train subset ( count task segment_size ) 
   "trainObj": 100, # total object ( not sure if this exist but this should be    total object annotated in 50 frame 
   "test": 10,
   "testObj": 20 
}

**Comment by zhiltsov-max** [comment]
Hi, annotations are stored in the DB per job. If you want to retrieve object counts outside of CVAT, it can be done by iterating over tasks or jobs, approximately this way:

```python
import sys
from argparse import ArgumentParser
from typing import List, Optional

from cvat_sdk import make_client
from cvat_sdk.core.proxies.tasks import Task
from cvat_sdk.core.helpers import get_paginated_collection

from tqdm import tqdm


def main(args: Optional[List[str]] = None) -> int:
    parser = ArgumentParser()
    parser.add_argument("project_id")
    parsed_args = parser.parse_args(args)

    with make_client(...) as client:
        all_annotations_count = {}

        tasks = [
            Task(client=client, model=task_model)
            for task_model in get_paginated_collection(
                client.tasks.api.list_endpoint, 
                project_id=parsed_args.project_id
            )
        ]

        for task in tqdm(tasks):
            annotations = task.get_annotations()

            annotations_count = {}
            annotations_count["tag"] = annotations_count.get("tag", 0) + len(annotations.tags)
            annotations_count["shapes"] = annotations_count.get("shapes", 0) + len(
                annotations.shapes
            )
            annotations_count["tracks"] = annotations_count.get("tracks", 0) + len(
                annotations.tracks
            )

            for shape in annotations.shapes:
                annotations_count[shape.type.value] = annotations_count.get(shape.type.value, 0) + 1

            print(f"Task {task.id} annotation counts:", annotations_count)

            for k, v in annotations_count.items():
                all_annotations_count[k] = all_annotations_count.get(k, 0) + v

        print("tasks visited:", [t.id for t in tasks])
        print("annotations count:", all_annotations_count)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))

```

**Comment by MohamedKHALILRouissi** [comment]
a minor issue in this code not sure if it could be resolved and thanks you so much for your time 
annotations count: {'tag': 0, 'shapes': 20, 'tracks': 1, 'rectangle': 20} , this is the result track contain 1 but in reality it may have more the image which result in more bounding box so 1 can represent a larger number

**Comment by MohamedKHALILRouissi** [comment]
found it again thanks for the help
