### ISSUE TITLE
Add sorting methods (lexicographical, natural, predefined, random) to CVAT API

### ISSUE THREAD

**Issue by DinohRatiarisandy** [cvat-ai/cvat#8832]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

When creating a task in CVAT via the API, there is no straightforward way to specify a sorting method (e.g., lexicographical, natural, predefined, or random) for the files or frames. This makes it difficult to control the order in which frames are processed or presented within the task.

For example, when uploading a dataset, the default order of frames might not align with the desired sequence (e.g., natural order for filenames like frame1, frame2, frame10). This lack of sorting flexibility can complicate workflows, especially for projects requiring a specific frame sequence.

### Describe the solution you'd like

I would like the CVAT API to support various sorting methods:

1. Lexicographical: Items sorted alphabetically (e.g., file1, file10, file2).

2. Natural: Items sorted as humans expect (e.g., file1, file2, file10).

3. Predefined: Items sorted in a user-defined order.

4. Random: Items shuffled randomly for scenarios where order does not matter.

This feature would enhance flexibility and allow users to better control the order of their data in automated workflows.

### Describe alternatives you've considered

In the CVAT interface, there is already an option to sort items using different methods (e.g., lexicographical, natural, etc.). However, this functionality does not appear to be available in the API.

As a workaround, users currently need to retrieve the data via the API and implement sorting on the client side. This approach increases complexity and processing time, particularly when working with large datasets. Adding built-in support for sorting directly within the API would provide consistency with the interface and simplify workflows.

### Additional context

Adding this feature would greatly benefit teams that rely on CVAT for annotation tasks, particularly in projects involving large datasets or custom workflows.

Example API usage (proposed):

```
GET /api/data?sort=natural  
GET /api/data?sort=random  
```

**Comment by azhavoro** [comment]
It's already supported
https://docs.cvat.ai/docs/api_sdk/sdk/reference/apis/tasks-api/#create_data
https://app.cvat.ai/api/swagger/#/tasks/tasks_create_data
