### ISSUE TITLE
Unable to Override CVAT_CHUNK_CACHE_TTL and CVAT_PREVIEW_CACHE_TTL via .env File

### ISSUE THREAD

**Issue by NoahNour** [cvat-ai/cvat#8845]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I attempted to modify the cache time-to-live settings for CVAT_CHUNK_CACHE_TTL and CVAT_PREVIEW_CACHE_TTL by specifying new values in the .env file. Despite these changes, the application continues to use the default values, indicating that the environment variables are not being properly overridden.
Приложение игнорирует настройки файла .env и продолжает работать со значениями TTL по умолчанию.

**Comment by zhiltsov-max** [comment]
Hi, CVAT doesn't use `.env` files for configuration of services. If you want to adjust some env variables, pass them directly to the corresponding containers in docker-compose files or set these values directly in `cvat/settings/*.py`.
