### ISSUE TITLE
Create holes in masks

### ISSUE THREAD

**Issue by javaidakhan** [cvat-ai/cvat#8847]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

I am annotating for ai cargo camera and have to annotate used space and unused space inside the trailer, I want to cut out used space from unused space masks but cannot do it, I read and saw the video that this problem is solved but I could not see how. Can you add a subtraction tool. Right now we need to do lot of work to achieve this and in the end use code to subtract the pixels. Also can you add a feature to convert cuboids to masks automatically.

### Describe the solution you'd like

Can you add a subtraction tool to cut one mask from another, like in our case used space from unused space inside the trailer.?

### Describe alternatives you've considered

I am searching other tools and it seems they have it but are more costly but would have to go for them to solve our problem unless you add it soon.

**Comment by javaidakhan** [comment]
> Hi @javaidakhan Have you tried using `remove underlying pixels`(we have docs [about it here](https://docs.cvat.ai/docs/manual/advanced/annotation-with-brush-tool/#remove-underlying-pixels)) masks feature? If so, why it doesnt work for you?

If you mean using eraser to remove underlying pixels we tried it but it takes too much time, no practical, can you add a feature to cut holes automatically and give a visible option.

**Comment by klakhov** [comment]
No, this is not related to using the eraser tool.  

The `Remove underlying pixels` feature allows you to draw a mask over an existing mask while automatically deleting the pixels of the underlying mask. You can enable this feature using the **arrow icon**:  
![image](https://github.com/user-attachments/assets/9f991037-b5da-4483-b9ed-4aa58fdf634e)  

In your case, you can first draw the `unused space` mask. Then, enable the feature and draw the `used space` mask. Wherever the `used space` mask overlaps with the `unused space` mask, the overlapping pixels from the `unused space` will be automatically removed.

**Comment by javaidakhan** [comment]
> No, this is not related to using the eraser tool.
> 
> The `Remove underlying pixels` feature allows you to draw a mask over an existing mask while automatically deleting the pixels of the underlying mask. You can enable this feature using the **arrow icon**: ![image](https://private-user-images.githubusercontent.com/50956430/397759808-9f991037-b5da-4483-b9ed-4aa58fdf634e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTIzMDksIm5iZiI6MTczNDk1MjAwOSwicGF0aCI6Ii81MDk1NjQzMC8zOTc3NTk4MDgtOWY5OTEwMzctYjVkYS00NDgzLWI5ZWQtNGFhNThmZGY2MzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDExMDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZWFmODBmZjllNjM0MDRmOWY5Mjk0ZTkzNTE5ZWMyMDY5Y2I1NjQ3MDYzNjZlMThjYThjNTA1Njg2NTU3NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1TetpH48RG2R53F4Gv_bi1ndWs-jqcijFJrOlcASlqg)
> 
> In your case, you can first draw the `unused space` mask. Then, enable the feature and draw the `used space` mask. Wherever the `used space` mask overlaps with the `unused space` mask, the overlapping pixels from the `unused space` will be automatically removed.

Thanks a lot, it worked!! Do appreciate your timely response. Wish you had documentation for these features since we could not find it and had to create this issue. Anyway thanks.

**Comment by klakhov** [comment]
Well, we have docs about this feature [here](https://docs.cvat.ai/docs/manual/advanced/annotation-with-brush-tool/#remove-underlying-pixels). Anyway, as issue is resolved I will close it.
